#ifndef HTML5_TOKENIZER_H
#define HTML5_TOKENIZER_H

#include "html5_parser.h"

// HTML5 tokenizer states from WHATWG spec section 12.2.5
// https://html.spec.whatwg.org/multipage/parsing.html#tokenization
enum Html5TokenizerState {
    // Core states
    HTML5_TOK_DATA,
    HTML5_TOK_RCDATA,
    HTML5_TOK_RAWTEXT,
    HTML5_TOK_SCRIPT_DATA,
    HTML5_TOK_PLAINTEXT,

    // Tag states
    HTML5_TOK_TAG_OPEN,
    HTML5_TOK_END_TAG_OPEN,
    HTML5_TOK_TAG_NAME,
    HTML5_TOK_RCDATA_LESS_THAN_SIGN,
    HTML5_TOK_RCDATA_END_TAG_OPEN,
    HTML5_TOK_RCDATA_END_TAG_NAME,
    HTML5_TOK_RAWTEXT_LESS_THAN_SIGN,
    HTML5_TOK_RAWTEXT_END_TAG_OPEN,
    HTML5_TOK_RAWTEXT_END_TAG_NAME,
    HTML5_TOK_SCRIPT_DATA_LESS_THAN_SIGN,
    HTML5_TOK_SCRIPT_DATA_END_TAG_OPEN,
    HTML5_TOK_SCRIPT_DATA_END_TAG_NAME,
    HTML5_TOK_SCRIPT_DATA_ESCAPE_START,
    HTML5_TOK_SCRIPT_DATA_ESCAPE_START_DASH,
    HTML5_TOK_SCRIPT_DATA_ESCAPED,
    HTML5_TOK_SCRIPT_DATA_ESCAPED_DASH,
    HTML5_TOK_SCRIPT_DATA_ESCAPED_DASH_DASH,
    HTML5_TOK_SCRIPT_DATA_ESCAPED_LESS_THAN_SIGN,
    HTML5_TOK_SCRIPT_DATA_ESCAPED_END_TAG_OPEN,
    HTML5_TOK_SCRIPT_DATA_ESCAPED_END_TAG_NAME,
    HTML5_TOK_SCRIPT_DATA_DOUBLE_ESCAPE_START,
    HTML5_TOK_SCRIPT_DATA_DOUBLE_ESCAPED,
    HTML5_TOK_SCRIPT_DATA_DOUBLE_ESCAPED_DASH,
    HTML5_TOK_SCRIPT_DATA_DOUBLE_ESCAPED_DASH_DASH,
    HTML5_TOK_SCRIPT_DATA_DOUBLE_ESCAPED_LESS_THAN_SIGN,
    HTML5_TOK_SCRIPT_DATA_DOUBLE_ESCAPE_END,

    // Attribute states
    HTML5_TOK_BEFORE_ATTRIBUTE_NAME,
    HTML5_TOK_ATTRIBUTE_NAME,
    HTML5_TOK_AFTER_ATTRIBUTE_NAME,
    HTML5_TOK_BEFORE_ATTRIBUTE_VALUE,
    HTML5_TOK_ATTRIBUTE_VALUE_DOUBLE_QUOTED,
    HTML5_TOK_ATTRIBUTE_VALUE_SINGLE_QUOTED,
    HTML5_TOK_ATTRIBUTE_VALUE_UNQUOTED,
    HTML5_TOK_AFTER_ATTRIBUTE_VALUE_QUOTED,
    HTML5_TOK_SELF_CLOSING_START_TAG,

    // Bogus states
    HTML5_TOK_BOGUS_COMMENT,
    HTML5_TOK_BOGUS_DOCTYPE,

    // Markup declaration open
    HTML5_TOK_MARKUP_DECLARATION_OPEN,

    // Comment states
    HTML5_TOK_COMMENT_START,
    HTML5_TOK_COMMENT_START_DASH,
    HTML5_TOK_COMMENT,
    HTML5_TOK_COMMENT_LESS_THAN_SIGN,
    HTML5_TOK_COMMENT_LESS_THAN_SIGN_BANG,
    HTML5_TOK_COMMENT_LESS_THAN_SIGN_BANG_DASH,
    HTML5_TOK_COMMENT_LESS_THAN_SIGN_BANG_DASH_DASH,
    HTML5_TOK_COMMENT_END_DASH,
    HTML5_TOK_COMMENT_END,
    HTML5_TOK_COMMENT_END_BANG,

    // DOCTYPE states
    HTML5_TOK_DOCTYPE,
    HTML5_TOK_BEFORE_DOCTYPE_NAME,
    HTML5_TOK_DOCTYPE_NAME,
    HTML5_TOK_AFTER_DOCTYPE_NAME,
    HTML5_TOK_AFTER_DOCTYPE_PUBLIC_KEYWORD,
    HTML5_TOK_BEFORE_DOCTYPE_PUBLIC_IDENTIFIER,
    HTML5_TOK_DOCTYPE_PUBLIC_IDENTIFIER_DOUBLE_QUOTED,
    HTML5_TOK_DOCTYPE_PUBLIC_IDENTIFIER_SINGLE_QUOTED,
    HTML5_TOK_AFTER_DOCTYPE_PUBLIC_IDENTIFIER,
    HTML5_TOK_BETWEEN_DOCTYPE_PUBLIC_AND_SYSTEM_IDENTIFIERS,
    HTML5_TOK_AFTER_DOCTYPE_SYSTEM_KEYWORD,
    HTML5_TOK_BEFORE_DOCTYPE_SYSTEM_IDENTIFIER,
    HTML5_TOK_DOCTYPE_SYSTEM_IDENTIFIER_DOUBLE_QUOTED,
    HTML5_TOK_DOCTYPE_SYSTEM_IDENTIFIER_SINGLE_QUOTED,
    HTML5_TOK_AFTER_DOCTYPE_SYSTEM_IDENTIFIER,
    HTML5_TOK_BOGUS_DOCTYPE_STATE,

    // CDATA section
    HTML5_TOK_CDATA_SECTION,
    HTML5_TOK_CDATA_SECTION_BRACKET,
    HTML5_TOK_CDATA_SECTION_END,

    // Character reference states
    HTML5_TOK_CHARACTER_REFERENCE,
    HTML5_TOK_NAMED_CHARACTER_REFERENCE,
    HTML5_TOK_AMBIGUOUS_AMPERSAND,
    HTML5_TOK_NUMERIC_CHARACTER_REFERENCE,
    HTML5_TOK_HEXADECIMAL_CHARACTER_REFERENCE_START,
    HTML5_TOK_DECIMAL_CHARACTER_REFERENCE_START,
    HTML5_TOK_HEXADECIMAL_CHARACTER_REFERENCE,
    HTML5_TOK_DECIMAL_CHARACTER_REFERENCE,
    HTML5_TOK_NUMERIC_CHARACTER_REFERENCE_END
};

// Tokenizer interface
Html5Token* html5_tokenize_next(Html5Parser* parser);

// Helper functions for tokenizer implementation
void html5_emit_token(Html5Parser* parser, Html5Token* token);
void html5_switch_tokenizer_state(Html5Parser* parser, Html5TokenizerState new_state);
char html5_consume_next_char(Html5Parser* parser);
char html5_peek_char(Html5Parser* parser, size_t offset);
bool html5_is_eof(Html5Parser* parser);

#endif // HTML5_TOKENIZER_H
