flowchart LR
N0@{shape: bang, label: "bang"}
N1@{shape: notch-rect, label: "notch"}
N2@{shape: cloud, label: "cloud"}
N3@{shape: hourglass, label: "hourglass"}
N4@{shape: bolt, label: "bolt"}
N5@{shape: lean-r, label: "lean right"}
N6@{shape: lean-l, label: "lean left"}
N7@{shape: delay, label: "delay"}
N8@{shape: h-cyl, label: "horizontal cylinder"}
N9@{shape: curv-trap, label: "curved trapezoid"}
N10@{shape: doc, label: "document"}
N11@{shape: tri, label: "triangle"}
N12@{shape: flip-tri, label: "flipped triangle"}
N13@{shape: notch-pent, label: "notched pentagon"}
N14@{shape: tag-rect, label: "tag"}
N15@{shape: f-circ, label: "filled circle"}
N16@{shape: sl-rect, label: "slanted"}
N17@{shape: text, label: "text"}
N18@{shape: brace, label: "brace"}
N19@{shape: brace-r, label: "right brace"}
N20@{shape: braces, label: "braces"}
N21@{shape: fork, label: "fork"}
N22@{shape: win-pane, label: "window pane"}
N23@{shape: lin-rect, label: "lined rectangle"}
N24@{shape: lin-cyl, label: "lined cylinder"}
