-- Generated by utils/generate_premake.py for macOS
-- Lambda Build System Premake5 Configuration
-- Platform: macOS
-- DO NOT EDIT MANUALLY - Regenerate using: python3 utils/generate_premake.py

workspace "Lambda"
    configurations { "Debug", "Release" }
    platforms { "native" }
    location "build/premake"
    startproject "lambda"
    toolset "gcc"
    
    -- Global settings
    cppdialect "C++17"
    cdialect "C99"
    warnings "Extra"
    
    filter "configurations:Debug"
        defines { "DEBUG" }
        symbols "On"
        optimize "Off"
    
    -- AddressSanitizer disabled for Linux platform
    
    filter "configurations:Release"
        defines { "NDEBUG" }
        optimize "On"
    
    -- Native Linux build settings
    toolset "gcc"
    defines { "LINUX", "_GNU_SOURCE", "NATIVE_LINUX_BUILD" }
    
    
    filter {}

project "lambda-lib"
    kind "StaticLib"
    language "C"
    targetdir "build/lib"
    objdir "build/obj/%{prj.name}"
    
    -- Meta-library: combines source files from dependencies
    files {
        "lib/mem-pool/src/variable.c",
        "lib/mem-pool/src/buffer.c",
        "lib/mem-pool/src/utils.c",
        "lib/strbuf.c",
        "lib/stringbuf.c",
        "lib/strview.c",
        "lib/string.c",
        "lib/num_stack.c",
        "lib/datetime.c",
        "lib/url.c",
        "lib/url_parser.c",
        "lib/log.c",
        "lib/cmdedit.c",
        "lib/cmdedit_utf8.c",
        "lambda/input/mime-detect.c",
        "lambda/input/mime-types.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/usr/local/lib",
    }
    
    links {
        "utf8proc",
    }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
    }
    
    defines {
        "UTF8PROC_STATIC",
    }
    

project "lambda-input-full-c"
    kind "SharedLib"
    language "C"
    targetdir "build/lib"
    objdir "build/obj/%{prj.name}"
    
    files {
        "lambda/parse.c",
        "lambda/input/css_tokenizer.c",
        "lambda/input/css_parser.c",
        "lambda/input/css_properties.c",
        "lib/arraylist.c",
        "lib/hashmap.c",
        "lib/file.c",
        "lib/log.c",
        "lib/utf.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "lambda/tree-sitter-lambda/bindings/c",
        "lambda/tree-sitter/lib/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "mac-deps/curl-8.10.1/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
    }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto"
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    links {
        "CoreFoundation.framework",
        "SystemConfiguration.framework",
        "z",
        "lambda-lib",
    }
    

project "lambda-input-full-cpp"
    kind "SharedLib"
    language "C++"
    targetdir "build/lib"
    objdir "build/obj/%{prj.name}"
    
    files {
        "lambda/print.cpp",
        "lambda/utf_string.cpp",
        "lambda/name_pool.cpp",
        "lambda/lambda-data.cpp",
        "lambda/build_ast.cpp",
        "lambda/validator.cpp",
        "lambda/validator/ast_validate.cpp",
        "lambda/validator/error_reporting.cpp",
        "test/test_stubs.cpp",
        "lambda/parse.c",
        "lambda/input/css_tokenizer.c",
        "lambda/input/css_parser.c",
        "lambda/input/css_properties.c",
        "lib/arraylist.c",
        "lib/hashmap.c",
        "lib/file.c",
        "lib/log.c",
        "lib/utf.c",
    }
    
    files {
        "lambda/input/input*.cpp",
    }
    
    files {
        "lambda/format/format*.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "lambda/tree-sitter-lambda/bindings/c",
        "lambda/tree-sitter/lib/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "mac-deps/curl-8.10.1/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
    }
    
    filter "files:**.c"
        buildoptions {
            "-pedantic",
            "-fdiagnostics-color=auto",
        }
    
    filter "files:**.cpp"
        buildoptions {
            "-pedantic",
            "-fdiagnostics-color=auto",
            "-std=c++17",
        }
    
    filter {}
    
    libdirs {
        "/opt/homebrew/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    links {
        "CoreFoundation.framework",
        "SystemConfiguration.framework",
        "z",
        "lambda-lib",
    }
    

project "lambda-input-full"
    kind "SharedLib"
    language "C++"
    targetdir "build/lib"
    objdir "build/obj/%{prj.name}"
    
    -- Wrapper library with empty source file
    files {
        "utils/empty.cpp",
    }
    
    links {
        "lambda-input-full-c",
        "lambda-input-full-cpp",
    }
    

project "lambda"
    kind "ConsoleApp"
    language "C++"
    targetdir "."
    objdir "build/obj/%{prj.name}"
    targetname "lambda"
    targetextension ".exe"
    
    files {
        "lambda/parse.c",
        "lib/strbuf.c",
        "lib/stringbuf.c",
        "lib/strview.c",
        "lib/arraylist.c",
        "lib/file.c",
        "lib/hashmap.c",
        "lib/log.c",
        "lib/cmdedit.c",
        "lib/cmdedit_utf8.c",
        "lib/mem-pool/src/variable.c",
        "lib/mem-pool/src/buffer.c",
        "lib/mem-pool/src/utils.c",
        "lib/url.c",
        "lib/url_parser.c",
        "lib/utf.c",
        "lib/num_stack.c",
        "lib/string.c",
        "lib/datetime.c",
        "lambda/lambda-data.cpp",
        "lambda/lambda-data-runtime.cpp",
        "lambda/runner.cpp",
        "lambda/transpile.cpp",
        "lambda/transpile-mir.cpp",
        "lambda/build_ast.cpp",
        "lambda/name_pool.cpp",
        "lambda/mir.c",
        "lambda/pack.cpp",
        "lambda/print.cpp",
        "lambda/lambda-eval.cpp",
        "lambda/lambda-eval-num.cpp",
        "lambda/lambda-proc.cpp",
        "lambda/utf_string.cpp",
        "lambda/lambda-mem.cpp",
        "lambda/validator.cpp",
        "lambda/validator/ast_validate.cpp",
        "lambda/validator/error_reporting.cpp",
        "lambda/input/css_tokenizer.c",
        "lambda/input/css_properties.c",
        "lambda/input/css_parser.c",
        "typeset/typeset.c",
        "typeset/view/view_tree.c",
        "typeset/integration/latex_bridge.cpp",
        "typeset/integration/latex_bridge_enhanced.cpp",
        "typeset/typeset_latex.cpp",
        "typeset/latex_typeset_enhanced.cpp",
        "typeset/output/pdf_renderer.c",
        "typeset/output/pdf_renderer_enhanced.c",
        "lambda/main-repl.cpp",
        "lambda/main.cpp",
        "lambda/input/mime-types.c",
        "lambda/input/css_tokenizer.c",
        "lambda/input/mime-detect.c",
        "lambda/input/css_parser.c",
        "lambda/input/css_properties.c",
        "lambda/input/input-jsx.cpp",
        "lambda/input/input-latex.cpp",
        "lambda/input/input_file_cache.cpp",
        "lambda/input/input-vcf.cpp",
        "lambda/input/input-man.cpp",
        "lambda/input/input.cpp",
        "lambda/input/input-ics.cpp",
        "lambda/input/input-json.cpp",
        "lambda/input/input-css.cpp",
        "lambda/input/input-pdf.cpp",
        "lambda/input/input_cache_util.cpp",
        "lambda/input/input_sysinfo.cpp",
        "lambda/input/input-math-ascii.cpp",
        "lambda/input/input-markup.cpp",
        "lambda/input/input-csv.cpp",
        "lambda/input/input_pool.cpp",
        "lambda/input/input-adoc.cpp",
        "lambda/input/input_http.cpp",
        "lambda/input/input-org.cpp",
        "lambda/input/input-mark.cpp",
        "lambda/input/input-toml.cpp",
        "lambda/input/input-mdx.cpp",
        "lambda/input/input_dir.cpp",
        "lambda/input/input-yaml.cpp",
        "lambda/input/input-html.cpp",
        "lambda/input/input-eml.cpp",
        "lambda/input/input-rtf.cpp",
        "lambda/input/input-math.cpp",
        "lambda/input/input-prop.cpp",
        "lambda/input/input-ini.cpp",
        "lambda/input/input-xml.cpp",
        "lambda/input/input-common.cpp",
        "lambda/format/format-md.cpp",
        "lambda/format/format-toml.cpp",
        "lambda/format/format-jsx.cpp",
        "lambda/format/format-text.cpp",
        "lambda/format/format.cpp",
        "lambda/format/format-prop.cpp",
        "lambda/format/format-math.cpp",
        "lambda/format/format-yaml.cpp",
        "lambda/format/format-css.cpp",
        "lambda/format/format-math-ascii.cpp",
        "lambda/format/format-html.cpp",
        "lambda/format/format-mdx.cpp",
        "lambda/format/format-rst.cpp",
        "lambda/format/format-org.cpp",
        "lambda/format/format-ini.cpp",
        "lambda/format/format-xml.cpp",
        "lambda/format/format-latex.cpp",
        "lambda/format/format-json.cpp",
        "lambda/format/format-wiki.cpp",
    }
    
    includedirs {
        ".",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    linkoptions {
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "/usr/local/lib/libmir.a",
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
        "/opt/homebrew/lib/libhpdf.a",
        "/opt/homebrew/lib/libnghttp2.a",
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
        "/opt/homebrew/lib/libhpdf.a",
    }
    
    -- Dynamic libraries
    filter "platforms:native"
        links {
            "z",
        }
    
        linkoptions {
            "-framework CoreFoundation",
            "-framework CoreServices",
            "-framework SystemConfiguration",
        }
    
    filter {}
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
    }
    
    -- C++ specific options
    filter "files:**.cpp"
        buildoptions { "-std=c++17" }
    
    -- C specific options
    filter "files:**.c"
        buildoptions { "-std=c99" }
    
    filter {}
    
    defines {
        "_GNU_SOURCE",
    }
    

project "test_strbuf_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_strbuf_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
    }
    

project "test_stringbuf_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_stringbuf_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
    }
    

project "test_strview_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_strview_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
    }
    

project "test_variable_pool_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_variable_pool_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
    }
    

project "test_num_stack_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_num_stack_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
    }
    

project "test_datetime_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_datetime_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
    }
    

project "test_url_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_url_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
    }
    

project "test_url_extra_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_url_extra_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
    }
    

project "test_cmdedit_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_cmdedit_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "gtest",
        "gtest_main",
        "utf8proc",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
        "/opt/homebrew/lib/libutf8proc.a",
    }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-DCMDEDIT_TESTING",
        "-Wno-implicit-function-declaration",
        "-DUTF8PROC_STATIC",
    }
    

project "test_mime_detect_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_mime_detect_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_math_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_math_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_math_ascii_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_math_ascii_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_markup_roundtrip_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_markup_roundtrip_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_input_roundtrip_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_input_roundtrip_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_dir_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_dir_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_http_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_http_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_sysinfo_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_sysinfo_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_jsx_roundtrip_new_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_jsx_roundtrip_new_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_mdx_roundtrip_new_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_mdx_roundtrip_new_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_css_tokenizer_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_css_tokenizer_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_css_parser_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_css_parser_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_css_integration_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_css_integration_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_css_files_safe_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_css_files_safe_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_css_frameworks_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_css_frameworks_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_mdx_roundtrip_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_mdx_roundtrip_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_jsx_roundtrip_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_jsx_roundtrip_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-fms-extensions",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_validator_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_validator_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_ast_validator_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_ast_validator_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libmpdec.a",
        "/opt/homebrew/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "-Wl,-force_load,/opt/homebrew/lib/libnghttp2.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/lib/libssl.a",
        "/opt/homebrew/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add tree-sitter libraries using linkoptions to append to LIBS section
    linkoptions {
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
    }
    
    filter {}
    linkoptions {
        "-Wl,-force_load,../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "-Wl,-force_load,../../lambda/tree-sitter/libtree-sitter.a",
    }
    

project "test_lambda_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_lambda_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
    }
    

project "test_lambda_repl_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_lambda_repl_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
    }
    

project "test_lambda_proc_gtest"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_lambda_proc_gtest.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "gtest",
        "gtest_main",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libgtest.a",
        "/opt/homebrew/lib/libgtest_main.a",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
    }
    

project "test_lambda_runner"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/lambda_test_runner.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include/openssl",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "criterion",
        "nanomsg",
        "git2",
    }
    
    buildoptions {
        "-pedantic",
        "-fdiagnostics-color=auto",
        "-std=c++17",
        "-D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES",
        "-D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES_WARNING=0",
    }
    
