-- Generated by utils/generate_premake.py
-- Lambda Test System Premake5 Configuration
-- DO NOT EDIT MANUALLY - Regenerate using: python3 utils/generate_premake.py

workspace "LambdaTests"
    configurations { "Debug", "Release" }
    platforms { "x64" }
    location "build/premake"
    startproject "lambda-lib"
    
    -- Global settings
    cppdialect "C++17"
    cdialect "C99"
    warnings "Extra"
    
    filter "configurations:Debug"
        defines { "DEBUG" }
        symbols "On"
        optimize "Off"
        buildoptions { "-fsanitize=address", "-fno-omit-frame-pointer" }
        linkoptions { "-fsanitize=address" }
    
    filter "configurations:Release"
        defines { "NDEBUG" }
        optimize "On"
    
    filter {}

project "lambda-lib"
    kind "StaticLib"
    language "C"
    targetdir "build/lib"
    objdir "build/obj/%{prj.name}"
    
    -- Meta-library: combines source files from dependencies
    files {
        "lib/mem-pool/src/variable.c",
        "lib/mem-pool/src/buffer.c",
        "lib/mem-pool/src/utils.c",
        "lib/strbuf.c",
        "lib/stringbuf.c",
        "lib/strview.c",
        "lib/string.c",
        "lib/num_stack.c",
        "lib/datetime.c",
        "lib/url.c",
        "lib/url_parser.c",
        "lib/log.c",
        "lambda/input/mime-detect.c",
        "lambda/input/mime-types.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
    }
    
    links {
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic"
    }
    

project "lambda-input-full-c"
    kind "StaticLib"
    language "C"
    targetdir "build/lib"
    objdir "build/obj/%{prj.name}"
    
    files {
        "lambda/parse.c",
        "lib/arraylist.c",
        "lib/hashmap.c",
        "lib/file.c",
        "lib/log.c",
        "lib/utf.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/include",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic"
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "../../mac-deps/nghttp2/lib/libnghttp2.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib/libcriterion.a",
    }
    
    links {
        "CoreFoundation.framework",
        "CoreServices.framework",
        "SystemConfiguration.framework",
        "z",
        "lambda-lib",
    }
    

project "lambda-input-full-cpp"
    kind "StaticLib"
    language "C++"
    targetdir "build/lib"
    objdir "build/obj/%{prj.name}"
    
    files {
        "lambda/print.cpp",
        "lambda/utf_string.cpp",
        "lambda/name_pool.cpp",
        "lambda/lambda-data.cpp",
        "lambda/validator/validate.cpp",
        "lambda/validator/schema_parser.cpp",
        "lambda/validator/validator.cpp",
    }
    
    files {
        "lambda/input/input*.cpp",
    }
    
    files {
        "lambda/format/format*.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/include",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17"
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "../../mac-deps/nghttp2/lib/libnghttp2.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib/libcriterion.a",
    }
    
    links {
        "CoreFoundation.framework",
        "CoreServices.framework",
        "SystemConfiguration.framework",
        "z",
        "lambda-lib",
    }
    

project "lambda-input-full"
    kind "StaticLib"
    language "C++"
    targetdir "build/lib"
    objdir "build/obj/%{prj.name}"
    
    -- Wrapper library with empty source file
    files {
        "utils/empty.cpp",
    }
    
    links {
        "lambda-input-full-c",
        "lambda-input-full-cpp",
    }
    

project "test_strbuf"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_strbuf.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_stringbuf"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_stringbuf.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
    }
    

project "test_strview"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_strview.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_variable_pool"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_variable_pool.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_num_stack"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_num_stack.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_datetime"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_datetime.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_url"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_url.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_url_extra"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_url_extra.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_mime_detect"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_mime_detect.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "../../mac-deps/nghttp2/lib/libnghttp2.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
        "/opt/homebrew/opt/libedit/lib/libedit.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_math"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_math.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    defines {
        "GINAC_AVAILABLE",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libginac.a",
        "/opt/homebrew/lib/libcln.a",
        "/opt/homebrew/lib/libgmp.a",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "../../mac-deps/nghttp2/lib/libnghttp2.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
        "/opt/homebrew/opt/libedit/lib/libedit.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    

project "test_math_ascii"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_math_ascii.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    defines {
        "GINAC_AVAILABLE",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "/opt/homebrew/lib/libginac.a",
        "/opt/homebrew/lib/libcln.a",
        "/opt/homebrew/lib/libgmp.a",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "../../mac-deps/nghttp2/lib/libnghttp2.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
        "/opt/homebrew/opt/libedit/lib/libedit.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    

project "test_markup_roundtrip"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_markup_roundtrip.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "../../mac-deps/nghttp2/lib/libnghttp2.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
        "/opt/homebrew/opt/libedit/lib/libedit.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    

project "test_input_roundtrip"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_input_roundtrip.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "../../mac-deps/nghttp2/lib/libnghttp2.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
        "/opt/homebrew/opt/libedit/lib/libedit.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    

project "test_dir"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_dir.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "../../mac-deps/nghttp2/lib/libnghttp2.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
        "/opt/homebrew/opt/libedit/lib/libedit.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    

project "test_http"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_http.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "../../mac-deps/nghttp2/lib/libnghttp2.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
        "/opt/homebrew/opt/libedit/lib/libedit.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    

project "test_sysinfo"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_sysinfo.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "../../mac-deps/nghttp2/lib/libnghttp2.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
        "/opt/homebrew/opt/libedit/lib/libedit.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    

project "test_jsx_roundtrip"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_jsx_roundtrip.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "../../mac-deps/nghttp2/lib/libnghttp2.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
        "/opt/homebrew/opt/libedit/lib/libedit.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    

project "test_validator"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_validator.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "../../mac-deps/curl-8.10.1/lib/libcurl.a",
        "../../mac-deps/nghttp2/lib/libnghttp2.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
        "/opt/homebrew/opt/libedit/lib/libedit.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
        "ncurses",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    

project "test_lambda"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_lambda.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "criterion",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
    }
    

project "test_lambda_repl"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_lambda_repl.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "criterion",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
    }
    

project "test_lambda_runner"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/lambda_test_runner.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/opt/libedit/include",
        "/opt/homebrew/Cellar/ginac/1.8.9/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    
