-- Generated by utils/generate_premake.py
-- Lambda Test System Premake5 Configuration
-- DO NOT EDIT MANUALLY - Regenerate using: python3 utils/generate_premake.py

workspace "LambdaTests"
    configurations { "Debug", "Release" }
    platforms { "x64" }
    location "build/premake"
    startproject "lambda-lib"
    
    -- Global settings
    cppdialect "C++17"
    cdialect "C99"
    warnings "Extra"
    
    filter "configurations:Debug"
        defines { "DEBUG" }
        symbols "On"
        optimize "Off"
        buildoptions { "-fsanitize=address", "-fno-omit-frame-pointer" }
        linkoptions { "-fsanitize=address" }
    
    filter "configurations:Release"
        defines { "NDEBUG" }
        optimize "On"
    
    filter {}

project "test_strbuf"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_strbuf.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_strview"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_strview.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_variable_pool"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_variable_pool.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_num_stack"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_num_stack.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_datetime"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_datetime.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_url"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_url.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_url_extra"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_url_extra.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-lib",
        "criterion",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_mime_detect"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_mime_detect.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_math"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_math.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    

project "test_markup_roundtrip"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_markup_roundtrip.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-runtime-full-cpp",
        "lambda-runtime-full-c",
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    

project "test_input_roundtrip"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_input_roundtrip.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-runtime-full-cpp",
        "lambda-runtime-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    

project "test_dir"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_dir.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    

project "test_http"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_http.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    

project "test_validator"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_validator.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    

project "test_mir"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_mir.c",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-runtime-full-cpp",
        "lambda-runtime-full-c",
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c99",
    }
    

project "test_lambda"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/test_lambda.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-runtime-full-cpp",
        "lambda-runtime-full-c",
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
    }
    

project "test_lambda_runner"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"
    
    files {
        "test/lambda_test_runner.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "mac-deps/curl-8.10.1/include",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/include",
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
        "mac-deps/nghttp2/include",
        "/opt/homebrew/Cellar/readline/8.3.1/include",
        "/usr/local/include",
        "/opt/homebrew/include",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/opt/homebrew/Cellar/criterion/2.4.2_2/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    links {
        "lambda-runtime-full-cpp",
        "lambda-runtime-full-c",
        "lambda-input-full-cpp",
        "lambda-input-full-c",
        "lambda-lib",
        "criterion",
    }
    
    linkoptions {
        "../../lambda/tree-sitter-lambda/libtree-sitter-lambda.a",
        "../../lambda/tree-sitter/libtree-sitter.a",
        "/opt/homebrew/Cellar/mpdecimal/4.0.1/lib/libmpdec.a",
        "/opt/homebrew/Cellar/utf8proc/2.10.0/lib/libutf8proc.a",
        "/usr/local/lib/libmir.a",
        "mac-deps/curl-8.10.1/lib/libcurl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libssl.a",
        "/opt/homebrew/Cellar/openssl@3/3.5.2/lib/libcrypto.a",
    }
    
    -- Add dynamic libraries
    links {
        "z",
    }
    
    -- Add macOS frameworks
    linkoptions {
        "-framework CoreFoundation",
        "-framework CoreServices",
        "-framework SystemConfiguration",
    }
    
    links { "stdc++" }
    
    buildoptions {
        "-fms-extensions",
        "-fcolor-diagnostics",
        "-pedantic",
        "-std=c++17",
    }
    
