-- Generated by utils/generate_premake.py
-- Lambda Build System Premake5 Configuration
-- DO NOT EDIT MANUALLY - Regenerate using: python3 utils/generate_premake.py

workspace "Lambda-Tests-Linux"
    configurations { "Debug", "Release" }
    platforms { "x64", "Linux_x64" }
    location "build/premake"
    startproject "test"
    toolset "clang"
    
    -- Global settings
    cppdialect "C++17"
    cdialect "C99"
    warnings "Extra"
    
    filter "configurations:Debug"
        defines { "DEBUG" }
        symbols "On"
        optimize "Off"
        buildoptions { "-fsanitize=address", "-fno-omit-frame-pointer" }
        linkoptions { "-fsanitize=address" }
    
    filter "configurations:Release"
        defines { "NDEBUG" }
        optimize "On"
    
    -- Linux cross-compilation settings
    filter "platforms:Linux_x64"
        system "linux"
        architecture "x64"
        toolset "gcc"
        gccprefix "x86_64-linux-gnu-"
        defines { "LINUX", "_GNU_SOURCE", "NATIVE_LINUX_BUILD" }
        buildoptions { "-static", "-O2", "-g", "-pedantic", "-fno-omit-frame-pointer" }
        linkoptions { "-static" }
        libdirs { "linux-deps/lib" }
    
    filter {}


project "lambda-lib-linux"
    kind "StaticLib"
    language "C"
    targetdir "build/lib"
    objdir "build/obj/%{prj.name}"
    
    files {
        "lib/mem-pool/src/variable.c",
        "lib/mem-pool/src/buffer.c",
        "lib/mem-pool/src/utils.c",
        "lib/strbuf.c",
        "lib/stringbuf.c",
        "lib/strview.c",
        "lib/string.c",
        "lib/num_stack.c",
        "lib/datetime.c",
        "lib/url.c",
        "lib/url_parser.c",
        "lib/log.c",
        "lambda/input/mime-detect.c",
        "lambda/utf_string.cpp",
        "lambda/lambda-data.cpp",
        "lambda/lambda-data-runtime.cpp",
        "lambda/runner.cpp",
        "lambda/transpile.cpp",
        "lambda/transpile-mir.cpp",
        "lambda/build_ast.cpp",
        "lambda/name_pool.cpp",
        "lambda/mir.c",
        "lambda/pack.cpp",
        "lambda/print.cpp",
        "lambda/lambda-eval.cpp",
        "lambda/lambda-eval-num.cpp",
        "lambda/lambda-proc.cpp",
        "lambda/utf_string.cpp",
        "lambda/lambda-mem.cpp",
        "lambda/validator.cpp",
        "lambda/validator/ast_validate.cpp",
        "lambda/validator/error_reporting.cpp",
        "lambda/tree-sitter-lambda/src/parser.c",
        "lambda/parse.c",
        "test/test_stubs.cpp",
    }
    
    includedirs {
        "lib/mem-pool/include",
        "linux-deps/include",
        "linux-deps/include/ncurses",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "include",
        ".",
    }
    
    libdirs {
        "linux-deps/lib",
    }
    
    filter "files:**.c"
        buildoptions {
            "-static",
            "-O2",
            "-g",
            "-pedantic",
            "-fno-omit-frame-pointer",
            "-std=c99",
            "-fms-extensions",
            "-fdiagnostics-color=auto",
        }
    
    filter "files:**.cpp"
        buildoptions {
            "-static",
            "-O2",
            "-g",
            "-pedantic",
            "-fno-omit-frame-pointer",
            "-std=c++17",
            "-fms-extensions",
            "-fdiagnostics-color=auto",
        }
    
    filter {}
    defines {
        "LINUX",
        "_GNU_SOURCE",
        "NATIVE_LINUX_BUILD",
        "UNICODE_LEVEL=1",
    }
    
    filter "platforms:Linux_x64"
        system "linux"
        architecture "x64"
        toolset "gcc"
        gccprefix "x86_64-linux-gnu-"
    
    filter {}
    
project "test"
    kind "ConsoleApp"
    language "C++"
    targetdir "."
    objdir "build/obj/%{prj.name}"
    targetname "lambda"
    targetextension ".exe"
    
    files {
    }
    
    includedirs {
        ".",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "lib/mem-pool/include",
        "/usr/local/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    buildoptions {
        "-fms-extensions",
        "-pedantic",
        "-fdiagnostics-color=auto",
    }
    
    -- C++ specific options
    filter "files:**.cpp"
        buildoptions { "-std=c++17" }
    
    -- C specific options
    filter "files:**.c"
        buildoptions { "-std=c99" }
    
    filter {}
    
    defines {
        "_GNU_SOURCE"
    }
    


project "test_strbuf"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"

    files {
        "test/test_strbuf.c",
    }

    includedirs {
        "lib/mem-pool/include",
        "linux-deps/include",
        "linux-deps/include/ncurses",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "include",
        ".",
    }

    libdirs {
        "linux-deps/lib",
    }

    links {
        "lambda-lib-linux",
        "criterion",
        "curl",
        "z",
        "ssl",
        "crypto",
        "edit",
        "ncurses",
        "cln",
        "gmp",
        "pthread",
        "dl",
        "m",
    }

    filter "files:**.c"
        buildoptions {
            "-static",
            "-O2",
            "-g",
            "-pedantic",
            "-fno-omit-frame-pointer",
            "-std=c99",
            "-fms-extensions",
            "-fdiagnostics-color=auto",
        }

    filter "files:**.cpp"
        buildoptions {
            "-static",
            "-O2",
            "-g",
            "-pedantic",
            "-fno-omit-frame-pointer",
            "-std=c++17",
            "-fms-extensions",
            "-fdiagnostics-color=auto",
        }

    defines {
        "LINUX",
        "_GNU_SOURCE",
        "NATIVE_LINUX_BUILD",
        "UNICODE_LEVEL=1",
    }

    filter "platforms:Linux_x64"
        system "linux"
        architecture "x64"
        toolset "gcc"
        gccprefix "x86_64-linux-gnu-"

    filter {}


project "test_stringbuf"
    kind "ConsoleApp"
    language "C++"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"

    files {
        "test/test_stringbuf.cpp",
    }

    includedirs {
        "lib/mem-pool/include",
        "linux-deps/include",
        "linux-deps/include/ncurses",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "include",
        ".",
    }

    libdirs {
        "linux-deps/lib",
    }

    links {
        "lambda-lib-linux",
        "criterion",
        "curl",
        "z",
        "ssl",
        "crypto",
        "edit",
        "ncurses",
        "cln",
        "gmp",
        "pthread",
        "dl",
        "m",
    }

    filter "files:**.c"
        buildoptions {
            "-static",
            "-O2",
            "-g",
            "-pedantic",
            "-fno-omit-frame-pointer",
            "-std=c99",
            "-fms-extensions",
            "-fdiagnostics-color=auto",
        }

    filter "files:**.cpp"
        buildoptions {
            "-static",
            "-O2",
            "-g",
            "-pedantic",
            "-fno-omit-frame-pointer",
            "-std=c++17",
            "-fms-extensions",
            "-fdiagnostics-color=auto",
        }

    defines {
        "LINUX",
        "_GNU_SOURCE",
        "NATIVE_LINUX_BUILD",
        "UNICODE_LEVEL=1",
    }

    filter "platforms:Linux_x64"
        system "linux"
        architecture "x64"
        toolset "gcc"
        gccprefix "x86_64-linux-gnu-"

    filter {}


project "test_strview"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"

    files {
        "test/test_strview.c",
    }

    includedirs {
        "lib/mem-pool/include",
        "linux-deps/include",
        "linux-deps/include/ncurses",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "include",
        ".",
    }

    libdirs {
        "linux-deps/lib",
    }

    links {
        "lambda-lib-linux",
        "criterion",
        "curl",
        "z",
        "ssl",
        "crypto",
        "edit",
        "ncurses",
        "cln",
        "gmp",
        "pthread",
        "dl",
        "m",
    }

    filter "files:**.c"
        buildoptions {
            "-static",
            "-O2",
            "-g",
            "-pedantic",
            "-fno-omit-frame-pointer",
            "-std=c99",
            "-fms-extensions",
            "-fdiagnostics-color=auto",
        }

    filter "files:**.cpp"
        buildoptions {
            "-static",
            "-O2",
            "-g",
            "-pedantic",
            "-fno-omit-frame-pointer",
            "-std=c++17",
            "-fms-extensions",
            "-fdiagnostics-color=auto",
        }

    defines {
        "LINUX",
        "_GNU_SOURCE",
        "NATIVE_LINUX_BUILD",
        "UNICODE_LEVEL=1",
    }

    filter "platforms:Linux_x64"
        system "linux"
        architecture "x64"
        toolset "gcc"
        gccprefix "x86_64-linux-gnu-"

    filter {}


project "test_variable_pool"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"

    files {
        "test/test_variable_pool.c",
    }

    includedirs {
        "lib/mem-pool/include",
        "linux-deps/include",
        "linux-deps/include/ncurses",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "include",
        ".",
    }

    libdirs {
        "linux-deps/lib",
    }

    links {
        "lambda-lib-linux",
        "criterion",
        "curl",
        "z",
        "ssl",
        "crypto",
        "edit",
        "ncurses",
        "cln",
        "gmp",
        "pthread",
        "dl",
        "m",
    }

    filter "files:**.c"
        buildoptions {
            "-static",
            "-O2",
            "-g",
            "-pedantic",
            "-fno-omit-frame-pointer",
            "-std=c99",
            "-fms-extensions",
            "-fdiagnostics-color=auto",
        }

    filter "files:**.cpp"
        buildoptions {
            "-static",
            "-O2",
            "-g",
            "-pedantic",
            "-fno-omit-frame-pointer",
            "-std=c++17",
            "-fms-extensions",
            "-fdiagnostics-color=auto",
        }

    defines {
        "LINUX",
        "_GNU_SOURCE",
        "NATIVE_LINUX_BUILD",
        "UNICODE_LEVEL=1",
    }

    filter "platforms:Linux_x64"
        system "linux"
        architecture "x64"
        toolset "gcc"
        gccprefix "x86_64-linux-gnu-"

    filter {}


project "test_num_stack"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"

    files {
        "test/test_num_stack.c",
    }

    includedirs {
        "lib/mem-pool/include",
        "linux-deps/include",
        "linux-deps/include/ncurses",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "include",
        ".",
    }

    libdirs {
        "linux-deps/lib",
    }

    links {
        "lambda-lib-linux",
        "criterion",
        "curl",
        "z",
        "ssl",
        "crypto",
        "edit",
        "ncurses",
        "cln",
        "gmp",
        "pthread",
        "dl",
        "m",
    }

    filter "files:**.c"
        buildoptions {
            "-static",
            "-O2",
            "-g",
            "-pedantic",
            "-fno-omit-frame-pointer",
            "-std=c99",
            "-fms-extensions",
            "-fdiagnostics-color=auto",
        }

    filter "files:**.cpp"
        buildoptions {
            "-static",
            "-O2",
            "-g",
            "-pedantic",
            "-fno-omit-frame-pointer",
            "-std=c++17",
            "-fms-extensions",
            "-fdiagnostics-color=auto",
        }

    defines {
        "LINUX",
        "_GNU_SOURCE",
        "NATIVE_LINUX_BUILD",
        "UNICODE_LEVEL=1",
    }

    filter "platforms:Linux_x64"
        system "linux"
        architecture "x64"
        toolset "gcc"
        gccprefix "x86_64-linux-gnu-"

    filter {}


project "test_datetime"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"

    files {
        "test/test_datetime.c",
    }

    includedirs {
        "lib/mem-pool/include",
        "linux-deps/include",
        "linux-deps/include/ncurses",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "include",
        ".",
    }

    libdirs {
        "linux-deps/lib",
    }

    links {
        "lambda-lib-linux",
        "criterion",
        "curl",
        "z",
        "ssl",
        "crypto",
        "edit",
        "ncurses",
        "cln",
        "gmp",
        "pthread",
        "dl",
        "m",
    }

    filter "files:**.c"
        buildoptions {
            "-static",
            "-O2",
            "-g",
            "-pedantic",
            "-fno-omit-frame-pointer",
            "-std=c99",
            "-fms-extensions",
            "-fdiagnostics-color=auto",
        }

    filter "files:**.cpp"
        buildoptions {
            "-static",
            "-O2",
            "-g",
            "-pedantic",
            "-fno-omit-frame-pointer",
            "-std=c++17",
            "-fms-extensions",
            "-fdiagnostics-color=auto",
        }

    defines {
        "LINUX",
        "_GNU_SOURCE",
        "NATIVE_LINUX_BUILD",
        "UNICODE_LEVEL=1",
    }

    filter "platforms:Linux_x64"
        system "linux"
        architecture "x64"
        toolset "gcc"
        gccprefix "x86_64-linux-gnu-"

    filter {}


project "test_url"
    kind "ConsoleApp"
    language "C"
    targetdir "test"
    objdir "build/obj/%{prj.name}"
    targetextension ".exe"

    files {
        "test/test_url.c",
    }

    includedirs {
        "lib/mem-pool/include",
        "linux-deps/include",
        "linux-deps/include/ncurses",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "include",
        ".",
    }

    libdirs {
        "linux-deps/lib",
    }

    links {
        "lambda-lib-linux",
        "criterion",
        "curl",
        "z",
        "ssl",
        "crypto",
        "edit",
        "ncurses",
        "cln",
        "gmp",
        "pthread",
        "dl",
        "m",
    }

    filter "files:**.c"
        buildoptions {
            "-static",
            "-O2",
            "-g",
            "-pedantic",
            "-fno-omit-frame-pointer",
            "-std=c99",
            "-fms-extensions",
            "-fdiagnostics-color=auto",
        }

    filter "files:**.cpp"
        buildoptions {
            "-static",
            "-O2",
            "-g",
            "-pedantic",
            "-fno-omit-frame-pointer",
            "-std=c++17",
            "-fms-extensions",
            "-fdiagnostics-color=auto",
        }

    defines {
        "LINUX",
        "_GNU_SOURCE",
        "NATIVE_LINUX_BUILD",
        "UNICODE_LEVEL=1",
    }

    filter "platforms:Linux_x64"
        system "linux"
        architecture "x64"
        toolset "gcc"
        gccprefix "x86_64-linux-gnu-"

    filter {}
