-- Generated by utils/generate_premake.py for macOS
-- Lambda Build System Premake5 Configuration
-- Platform: macOS
-- DO NOT EDIT MANUALLY - Regenerate using: python3 utils/generate_premake.py

workspace "Lambda"
    configurations { "Debug", "Release" }
    platforms { "native" }
    location "build/premake"
    startproject "radiant"
    toolset "clang"
    
    -- Global settings
    cppdialect "C++17"
    cdialect "C99"
    warnings "Extra"
    
    filter "configurations:Debug"
        defines { "DEBUG" }
        symbols "On"
        optimize "Off"
    
    -- AddressSanitizer for non-Linux platforms only (conflicts with -static)
    filter { "configurations:Debug", "not platforms:Linux_x64" }
        buildoptions { "-fsanitize=address", "-fno-omit-frame-pointer" }
        linkoptions { "-fsanitize=address" }
    
    filter "configurations:Release"
        defines { "NDEBUG" }
        optimize "On"
    
    
    filter {}

project "radiant"
    kind "ConsoleApp"
    language "C++"
    targetdir "."
    objdir "build/obj/%{prj.name}"
    targetname "radiant"
    targetextension ".exe"
    
    files {
        "radiant/window.c",
        "radiant/ui_context.c",
        "radiant/parse_html.c",
        "radiant/layout.c",
        "radiant/layout_block.c",
        "radiant/layout_text.c",
        "radiant/layout_flex_nodes.c",
        "radiant/layout_flex.c",
        "radiant/resolve_style.c",
        "radiant/scroller.c",
        "radiant/view_pool.c",
        "radiant/font.c",
        "radiant/surface.c",
        "radiant/render.c",
        "radiant/event.c",
        "lib/strview.c",
        "lib/strbuf.c",
        "lib/hashmap.c",
        "lib/arraylist.c",
        "lib/log.c",
        "lib/mem-pool/src/variable.c",
        "lib/mem-pool/src/buffer.c",
        "lib/mem-pool/src/utils.c",
        "lib/file.c",
        "lib/url.c",
        "lib/url_parser.c",
        "lib/utf.c",
    }
    
    includedirs {
        ".",
        "lambda/tree-sitter/lib/include",
        "lambda/tree-sitter-lambda/bindings/c",
        "lib/mem-pool/include",
        "lexbor/source",
        "/opt/homebrew/Cellar/freetype/2.13.3/include/freetype2",
        "/opt/homebrew/include/fontconfig",
        "/opt/homebrew/opt/sdl2/include/SDL2 -I/opt/homebrew/opt/sdl2_image/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
        "/opt/homebrew/include",
    }
    
    libdirs {
        "/opt/homebrew/lib",
        "/usr/local/lib",
        "build/lib",
    }
    
    linkoptions {
        "../../lexbor/liblexbor_static.a",
        "/opt/homebrew/Cellar/freetype/2.13.3/lib/libfreetype.a",
        "/opt/homebrew/lib/libpng.a",
        "/opt/homebrew/opt/bzip2/lib/libbz2.a",
        "/opt/homebrew/lib/libfontconfig.a",
        "/opt/homebrew/opt/expat/lib/libexpat.a",
        "/opt/homebrew/opt/zlib/lib/libz.a",
        "/opt/homebrew/lib/libintl.a",
        "/opt/homebrew/lib/libglfw3.a",
    }
    
    -- Dynamic libraries
    filter "platforms:native"
        links {
            "SDL2_image",
            "thorvg",
            "iconv",
        }
    
        linkoptions {
            "-framework OpenGL",
            "-framework Cocoa",
            "-framework IOKit",
            "-framework CoreVideo",
        }
    
    filter {}
    
    buildoptions {
        "-pedantic",
        "-fms-extensions",
        "-fcolor-diagnostics",
    }
    
    -- C++ specific options
    filter "files:**.cpp"
        buildoptions { "-std=c++17" }
    
    -- C specific options
    filter "files:**.c"
        buildoptions { "-std=c99" }
    
    filter {}
    
    defines {
        "_GNU_SOURCE",
    }
    
