// Radiant module-owned DOM property dispatch smoke.

var main = document.getElementById("main");
console.log(main.tagName);
console.log(main.localName);
console.log(main.namespaceURI);
console.log(main.prefix === null);
console.log(main.id);
console.log(main.className);
console.log(main.nodeType);

var link = document.createElement("a");
link.setAttribute("href", "/docs");
console.log(link.href);
var image = document.createElement("img");
image.setAttribute("src", "hero.png");
image.setAttribute("alt", "Hero");
console.log(image.src);
console.log(image.alt);
var form = document.createElement("form");
form.setAttribute("novalidate", "");
form.setAttribute("accept-charset", "utf-8");
form.setAttribute("target", "_blank");
console.log(form.noValidate);
console.log(form.acceptCharset);
console.log(form.target);
var input = document.createElement("input");
input.setAttribute("required", "");
input.setAttribute("readonly", "");
input.setAttribute("maxlength", "12");
input.setAttribute("minlength", "2");
input.setAttribute("size", "7");
input.setAttribute("placeholder", "Name");
input.setAttribute("pattern", "[a-z]+");
console.log(input.required);
console.log(input.readOnly);
console.log(input.maxLength);
console.log(input.minLength);
console.log(input.size);
console.log(input.placeholder);
console.log(input.pattern);
var textarea = document.createElement("textarea");
textarea.setAttribute("rows", "4");
textarea.setAttribute("cols", "30");
console.log(textarea.rows);
console.log(textarea.cols);
console.log(textarea.wrap);
var button = document.createElement("button");
button.setAttribute("formtarget", "panel");
button.setAttribute("formnovalidate", "");
console.log(button.formTarget);
console.log(button.formNoValidate);
var details = document.createElement("details");
details.setAttribute("open", "");
console.log(details.open);
var option = document.createElement("option");
option.setAttribute("selected", "");
console.log(option.defaultSelected);
var check = document.createElement("input");
check.setAttribute("type", "checkbox");
check.defaultChecked = true;
console.log(check.hasAttribute("checked"));
console.log(check.defaultChecked);
console.log(check.checked);
check.checked = false;
check.defaultChecked = false;
console.log(check.hasAttribute("checked"));
console.log(check.checked);
var select = document.createElement("select");
var optA = document.createElement("option");
var optB = document.createElement("option");
optA.setAttribute("value", "a");
optB.setAttribute("value", "b");
select.appendChild(optA);
select.appendChild(optB);
optB.defaultSelected = true;
console.log(optB.hasAttribute("selected"));
console.log(optB.defaultSelected);
console.log(optB.selected);
console.log(optA.selected);
console.log(select.value);
select.value = "a";
console.log(select.value);
console.log(optA.selected);
console.log(optB.selected);
select.selectedIndex = 1;
console.log(select.selectedIndex);
console.log(select.value);
console.log(optA.selected);
console.log(optB.selected);
optA.selected = true;
console.log(select.selectedIndex);
console.log(select.value);
console.log(optA.selected);
console.log(optB.selected);
select.multiple = true;
console.log(select.hasAttribute("multiple"));
select.multiple = false;
console.log(select.hasAttribute("multiple"));
console.log(optB.selected);
link.href = "/next";
console.log(link.getAttribute("href"));
console.log(link.href);
input.maxLength = 9;
console.log(input.getAttribute("maxlength"));
console.log(input.maxLength);
textarea.rows = 6;
textarea.wrap = "hard";
console.log(textarea.getAttribute("rows"));
console.log(textarea.rows);
console.log(textarea.getAttribute("wrap"));
console.log(textarea.wrap);
button.formTarget = "modal";
console.log(button.getAttribute("formtarget"));
console.log(button.formTarget);
input.setAttribute("inputmode", "NUMERIC");
input.setAttribute("enterkeyhint", "Go");
console.log(input.inputMode);
console.log(input.enterKeyHint);
input.inputMode = "decimal";
input.enterKeyHint = "send";
console.log(input.getAttribute("inputmode"));
console.log(input.inputMode);
console.log(input.getAttribute("enterkeyhint"));
console.log(input.enterKeyHint);
var editable = document.createElement("div");
var editableChild = document.createElement("span");
editable.setAttribute("contenteditable", "plaintext-only");
editable.appendChild(editableChild);
console.log(editable.contentEditable);
console.log(editable.isContentEditable);
console.log(editableChild.contentEditable);
console.log(editableChild.isContentEditable);
editableChild.setAttribute("contenteditable", "false");
console.log(editableChild.contentEditable);
console.log(editableChild.isContentEditable);
editable.contentEditable = "TRUE";
console.log(editable.getAttribute("contenteditable"));
console.log(editable.contentEditable);
editable.contentEditable = "inherit";
console.log(editable.hasAttribute("contenteditable"));
console.log(editable.contentEditable);
editable.contentEditable = false;
console.log(editable.getAttribute("contenteditable"));
console.log(editable.contentEditable);
editable.contentEditable = "";
console.log(editable.hasAttribute("contenteditable"));
console.log(editable.contentEditable);
input.required = false;
console.log(input.hasAttribute("required"));
input.required = "yes";
console.log(input.getAttribute("required"));
console.log(input.required);
input.readOnly = 0;
console.log(input.hasAttribute("readonly"));
input.multiple = true;
console.log(input.hasAttribute("multiple"));
form.noValidate = false;
console.log(form.hasAttribute("novalidate"));
button.formNoValidate = false;
console.log(button.hasAttribute("formnovalidate"));
details.open = false;
console.log(details.hasAttribute("open"));
details.open = true;
console.log(details.getAttribute("open"));
console.log(details.open);
main.autofocus = true;
console.log(main.hasAttribute("autofocus"));
main.autofocus = false;
console.log(main.hasAttribute("autofocus"));
button.disabled = true;
console.log(button.getAttribute("disabled"));
console.log(button.disabled);
button.disabled = false;
console.log(button.hasAttribute("disabled"));

var text = document.getElementById("intro").firstChild;
console.log(text.nodeType);
console.log(text.nodeName);
console.log(text.nodeValue);
console.log(text.textContent);
console.log(text.length);
console.log(text.parentNode === document.getElementById("intro"));
console.log(text.parentElement === document.getElementById("intro"));
console.log(text.firstChild === null);
console.log(text.childNodes.length);
console.log(text.isConnected);
text.data = "Beta";
console.log(text.nodeValue);
text.appendData("!");
console.log(text.data);
console.log(text.substringData(1, 3));
text.insertData(0, "A");
console.log(text.data);
text.deleteData(1, 1);
console.log(text.data);
text.replaceData(1, 3, "lpha");
console.log(text.textContent);

var comment = document.createComment("note");
console.log(comment.isConnected);
main.appendChild(comment);
console.log(comment.nodeType);
console.log(comment.nodeName);
console.log(comment.data);
console.log(comment.length);
console.log(comment.parentNode === main);
console.log(comment.previousSibling === document.getElementById("intro"));
console.log(comment.nextSibling === null);
console.log(main.firstChild === document.getElementById("intro"));
console.log(main.lastChild === comment);
console.log(main.childNodes.length);
console.log(document.getElementById("intro").nextSibling === comment);
console.log(comment.previousSibling.parentNode === main);
console.log(comment.isConnected);
console.log(main.isConnected);
console.log(text.ownerDocument === document);
console.log(comment.ownerDocument === document);
console.log(main.ownerDocument === document);
console.log(main.childElementCount);
console.log(main.length);
console.log(main.children.length);
console.log(main.children[0] === document.getElementById("intro"));
console.log(main.firstElementChild === document.getElementById("intro"));
console.log(main.lastElementChild === document.getElementById("intro"));
console.log(document.getElementById("intro").nextElementSibling === null);

var tail = document.createElement("span");
tail.id = "tail";
tail.className = "lookup";
main.appendChild(tail);
console.log(main.childElementCount);
console.log(main.length);
console.log(main.children.length);
console.log(main.children[0] === document.getElementById("intro"));
console.log(main.children[1] === tail);
console.log(main.lastElementChild === tail);
console.log(document.getElementById("intro").nextElementSibling === tail);
console.log(tail.previousElementSibling === document.getElementById("intro"));
console.log(tail.isConnected);
var spans = main.getElementsByTagName("span");
console.log(spans.length);
console.log(spans[0] === tail);
console.log(main.getElementsByTagName("*").length);
var lookup = main.getElementsByClassName("lookup");
console.log(lookup.length);
console.log(lookup[0] === tail);
console.log(main.querySelector("#tail") === tail);
console.log(main.querySelectorAll(".lookup").length);
console.log(tail.matches(".lookup"));
console.log(tail.closest("#main") === main);
console.log(main.querySelector(".missing") === null);
console.log(main.getElementById("tail") === tail);
console.log(main.compareDocumentPosition(main));
console.log(main.compareDocumentPosition(tail));
console.log(tail.compareDocumentPosition(main));
console.log(document.getElementById("intro").compareDocumentPosition(tail));
console.log(tail.compareDocumentPosition(document.getElementById("intro")));
var ops = document.createElement("div");
var opA = document.createElement("a");
var opB = document.createElement("b");
var opC = document.createElement("c");
console.log(ops.appendChild(opA) === opA);
ops.appendChild(opC);
console.log(ops.insertBefore(opB, opC) === opB);
console.log(ops.children[0] === opA);
console.log(ops.children[1] === opB);
console.log(ops.children[2] === opC);
console.log(ops.removeChild(opB) === opB);
console.log(opB.parentNode === null);
console.log(ops.children.length);
var moreOps = document.createElement("div");
var oldKid = document.createElement("old-kid");
var newKid = document.createElement("new-kid");
moreOps.appendChild(oldKid);
console.log(moreOps.replaceChild(newKid, oldKid) === oldKid);
console.log(oldKid.parentNode === null);
console.log(moreOps.children[0] === newKid);
var replaceHost = document.createElement("div");
var replaceOne = document.createElement("one");
var replaceTwo = document.createElement("two");
var replaceThree = document.createElement("three");
replaceHost.appendChild(replaceOne);
replaceOne.replaceWith(replaceTwo, replaceThree);
console.log(replaceOne.parentNode === null);
console.log(replaceHost.children[0] === replaceTwo);
console.log(replaceHost.children[1] === replaceThree);
var adjacentParent = document.createElement("div");
var adjacentTarget = document.createElement("target");
var adjacentBefore = document.createElement("before");
var adjacentInside = document.createElement("inside");
var adjacentAfter = document.createElement("after");
adjacentParent.appendChild(adjacentTarget);
console.log(adjacentTarget.insertAdjacentElement("beforebegin", adjacentBefore) === adjacentBefore);
console.log(adjacentTarget.insertAdjacentElement("afterbegin", adjacentInside) === adjacentInside);
console.log(adjacentTarget.insertAdjacentElement("afterend", adjacentAfter) === adjacentAfter);
console.log(adjacentParent.children[0] === adjacentBefore);
console.log(adjacentTarget.firstElementChild === adjacentInside);
console.log(adjacentParent.children[2] === adjacentAfter);
adjacentTarget.insertAdjacentHTML("beforeend", "<span id=\"html-insert\">ok</span>");
console.log(adjacentTarget.lastElementChild.tagName);
console.log(adjacentTarget.lastElementChild.getAttribute("id"));
var variadic = document.createElement("div");
variadic.append("tail");
variadic.prepend("head");
console.log(variadic.childNodes.length);
console.log(variadic.firstChild.data);
console.log(variadic.lastChild.data);
var norm = document.createElement("div");
norm.appendChild(document.createTextNode("a"));
norm.appendChild(document.createTextNode("b"));
norm.normalize();
console.log(norm.childNodes.length);
console.log(norm.firstChild.data);
var cloneSrc = document.createElement("section");
cloneSrc.setAttribute("data-x", "1");
cloneSrc.appendChild(document.createElement("em"));
var clone = cloneSrc.cloneNode(true);
console.log(clone !== cloneSrc);
console.log(clone.getAttribute("data-x"));
console.log(clone.children[0].tagName);
var removable = document.createElement("remove-me");
moreOps.appendChild(removable);
removable.remove();
console.log(removable.parentNode === null);
console.log(moreOps.children.length);
console.log(main.hasChildNodes());
console.log(main.contains(text));
console.log(text.contains(main));
console.log(main.getAttribute("id"));
console.log(main.hasAttribute("class"));
var attrNames = main.getAttributeNames();
console.log(attrNames.indexOf("id") >= 0);
console.log(attrNames.indexOf("class") >= 0);
console.log(attrNames.indexOf("__lambda_ns_uri") === -1);
var attrs = main.attributes;
var sawIdAttr = false;
var sawClassAttr = false;
var sawInternalAttr = false;
for (var i = 0; i < attrs.length; i++) {
    if (attrs[i].name === "id" && attrs[i].value === "main") sawIdAttr = true;
    if (attrs[i].name === "class" && attrs[i].value === "alpha beta") sawClassAttr = true;
    if (attrs[i].name === "__lambda_ns_uri") sawInternalAttr = true;
}
console.log(attrs.length);
console.log(sawIdAttr);
console.log(sawClassAttr);
console.log(sawInternalAttr);
var tpl = document.createElement("template");
var tplChild = document.createElement("span");
tpl.appendChild(tplChild);
console.log(tpl.content === tpl);
console.log(tpl.content.firstChild === tplChild);
main.setAttribute("data-module", 42);
console.log(main.getAttribute("data-module"));
console.log(main.hasAttribute("data-module"));
console.log(main.toggleAttribute("data-module"));
console.log(main.hasAttribute("data-module"));
console.log(main.toggleAttribute("data-module", false));
console.log(main.hasAttribute("data-module"));
main.setAttribute("__lambda_hidden", "secret");
console.log(main.getAttribute("__lambda_hidden") === null);
main.removeAttribute("data-module");
console.log(main.hasAttribute("data-module"));

main.id = "main-updated";
main.className = "gamma delta";
console.log(main.id);
console.log(main.getAttribute("id"));
console.log(document.getElementById("main-updated") === main);
console.log(main.className);
console.log(main.getAttribute("class"));
