var link = document.getElementById('link');
console.log(link.protocol);
console.log(link.host);
console.log(link.hostname);
console.log(link.pathname);
console.log(link.search);
console.log(link.hash);
console.log(link.origin);
console.log(link.href);
link.setAttribute('href', '#');
console.log(link.hash === '');
console.log(link.href.endsWith('#'));
var emptyParts = new URL('https://example.com/?#');
console.log(emptyParts.search === '' && emptyParts.hash === '');
console.log(emptyParts.href === 'https://example.com/?#');
console.log('ANCHOR_URL_DONE');
