// Radiant module-owned DOM property dispatch smoke.

var main = document.getElementById("main");
console.log(main.tagName);
console.log(main.localName);
console.log(main.namespaceURI);
console.log(main.prefix === null);
console.log(main.id);
console.log(main.className);
console.log(main.nodeType);
main.moduleExpando = 123;
console.log(main.moduleExpando);
console.log("moduleExpando" in main);
var mainIdDesc = Object.getOwnPropertyDescriptor(main, "id");
console.log(mainIdDesc.value);
console.log(mainIdDesc.enumerable);
console.log(mainIdDesc.configurable);
var moduleExpandoDesc = Object.getOwnPropertyDescriptor(main, "moduleExpando");
console.log(moduleExpandoDesc.value);
console.log(moduleExpandoDesc.enumerable);
console.log(moduleExpandoDesc.configurable);
var mainOwnNames = Object.getOwnPropertyNames(main);
console.log(mainOwnNames.indexOf("id") >= 0);
console.log(mainOwnNames.indexOf("moduleExpando") > mainOwnNames.indexOf("id"));
var mainKeys = Object.keys(main);
console.log(mainKeys.indexOf("id") >= 0);
console.log(mainKeys.indexOf("moduleExpando") > mainKeys.indexOf("id"));
console.log(typeof Element);
console.log(main.__proto__ === Element.prototype);
Element.prototype.moduleProto = 654;
console.log(main.moduleProto);
console.log(main instanceof Element);
console.log(main instanceof Node);
console.log(delete main.id);
console.log(main.id);
console.log(delete main.moduleExpando);
console.log(main.moduleExpando === undefined);
console.log("moduleExpando" in main);
main.moduleExpando = 321;
console.log(main.moduleExpando);
console.log(document.documentElement.tagName);
console.log(document.body.tagName);
console.log(document.head.tagName);
console.log(document.title);
console.log(document.location === document);
console.log(document.document === document);
console.log(document.href === document.URL);
console.log(typeof document.protocol);
console.log(document.readyState);
console.log(document.compatMode);
console.log(document.characterSet);
console.log(document.charset);
console.log(document.contentType);
console.log(document.nodeType);
console.log(document.nodeName);
console.log(document.activeElement === document.body);
console.log(typeof document.implementation.createHTMLDocument);
console.log(document.fonts === document.fonts);
console.log(typeof document.fonts.ready.then);
document.defaultView = window;
console.log(document.defaultView === window);
document.designMode = "on";
console.log(document.designMode);
document.designMode = "off";
console.log(document.designMode);
var foreignDoc = document.implementation.createHTMLDocument("ForeignTitle");
console.log(foreignDoc.defaultView === null);
console.log(foreignDoc.body.ownerDocument === foreignDoc);
var foreignDiv = foreignDoc.createElement("div");
foreignDiv.setAttribute("id", "foreign-main");
foreignDoc.body.appendChild(foreignDiv);
console.log(foreignDoc.getElementById("foreign-main") === foreignDiv);
console.log(foreignDoc.querySelector("#foreign-main") === foreignDiv);
foreignDoc.moduleExpando = 47;
console.log(foreignDoc.moduleExpando);
console.log(document.ownerDocument === null);
console.log(document.childNodes.length);
console.log(document.childNodes[1] === document.documentElement);
console.log(document.doctype !== null);
console.log(document.getElementsByTagName("p").length);
console.log(document.getElementsByClassName("alpha")[0] === main);
main.setAttribute("name", "mainName");
console.log(document.getElementsByName("mainName")[0] === main);
var liveDocTags = document.getElementsByTagName("p");
var liveDocClasses = document.getElementsByClassName("alpha");
var liveDocNames = document.getElementsByName("mainName");
var liveDocTagBase = liveDocTags.length;
var liveDocClassBase = liveDocClasses.length;
var liveDocNameBase = liveDocNames.length;
var liveDocLookup = document.createElement("p");
liveDocLookup.className = "alpha";
liveDocLookup.setAttribute("name", "mainName");
document.body.appendChild(liveDocLookup);
console.log(liveDocTags.length === liveDocTagBase + 1);
console.log(liveDocTags[liveDocTagBase] === liveDocLookup);
console.log(liveDocClasses.length === liveDocClassBase + 1);
console.log(liveDocNames.length === liveDocNameBase + 1);
liveDocLookup.className = "beta";
console.log(liveDocClasses.length === liveDocClassBase);
liveDocLookup.setAttribute("name", "otherName");
console.log(liveDocNames.length === liveDocNameBase);
document.body.removeChild(liveDocLookup);
console.log(liveDocTags.length === liveDocTagBase);
main.removeAttribute("name");
console.log(document.querySelector("#intro").id);
console.log(document.querySelectorAll(".alpha").length);
console.log(document.querySelector(".missing") === null);
var nsEl = document.createElementNS("http://www.w3.org/2000/svg", "svg");
console.log(nsEl.namespaceURI);
console.log(nsEl.localName);
console.log(nsEl.getAttribute("__lambda_ns_uri") === null);
var madeText = document.createTextNode("Factory");
console.log(madeText.nodeType);
console.log(madeText.data);
var madeComment = document.createComment("factory-comment");
console.log(madeComment.nodeType);
console.log(madeComment.data);
var frag = document.createDocumentFragment();
frag.appendChild(nsEl);
console.log(frag.firstChild === nsEl);
console.log(nsEl.parentNode === frag);
var pi = document.createProcessingInstruction("xml-stylesheet", "href='x'");
console.log(pi.tagName);
var importedMain = document.importNode(main, true);
console.log(importedMain !== main);
console.log(importedMain.id);
console.log(importedMain.firstChild.id);
var docAppend = document.createElement("section");
console.log(document.appendChild(docAppend) === docAppend);
console.log(docAppend.parentNode === document.documentElement);
var adoptedDocAppend = document.adoptNode(docAppend);
console.log(adoptedDocAppend === docAppend);
console.log(docAppend.parentNode === null);
var docTextA = document.createTextNode("x");
var docTextB = document.createTextNode("y");
document.appendChild(docTextA);
document.appendChild(docTextB);
document.normalize();
console.log(docTextA.data);
console.log(docTextB.parentNode === null);
document.adoptNode(docTextA);
console.log(docTextA.parentNode === null);
console.log(document.elementFromPoint(0, 0) !== null);
console.log(document.execCommand("bold") === false);
console.log(document.queryCommandSupported("bold") === false);
console.log(document.queryCommandEnabled("bold") === false);
console.log(document.queryCommandState("bold") === false);
console.log(document.queryCommandValue("bold"));
var moduleRange = document.createRange();
console.log(moduleRange !== null);
console.log(moduleRange.collapsed);
console.log(typeof Range);
console.log(moduleRange.__proto__ === Range.prototype);
Range.prototype.moduleProto = 654;
console.log(moduleRange.moduleProto);
console.log(moduleRange instanceof Range);
moduleRange.moduleExpando = 456;
console.log(moduleRange.moduleExpando);
console.log("moduleExpando" in moduleRange);
console.log(Object.getOwnPropertyDescriptor(moduleRange, "collapsed").value);
console.log(Object.getOwnPropertyDescriptor(moduleRange, "moduleExpando").value);
console.log(Object.keys(moduleRange).indexOf("moduleExpando") > Object.keys(moduleRange).indexOf("collapsed"));
console.log(delete moduleRange.moduleExpando);
console.log(moduleRange.moduleExpando === undefined);
console.log(typeof document.getSelection);
var moduleSelectionA = document.getSelection();
var moduleSelectionB = document.getSelection();
console.log(moduleSelectionA !== null);
console.log(moduleSelectionA === moduleSelectionB);
console.log(moduleSelectionA.rangeCount);
console.log(typeof Selection);
console.log(moduleSelectionA.__proto__ === Selection.prototype);
Selection.prototype.moduleProto = 654;
console.log(moduleSelectionA.moduleProto);
console.log(moduleSelectionA instanceof Selection);
moduleSelectionA.moduleExpando = 789;
console.log(moduleSelectionA.moduleExpando);
console.log("moduleExpando" in moduleSelectionA);
console.log(Object.getOwnPropertyDescriptor(moduleSelectionA, "rangeCount").value);
console.log(Object.getOwnPropertyDescriptor(moduleSelectionA, "moduleExpando").value);
console.log(delete moduleSelectionA.moduleExpando);
console.log(moduleSelectionA.moduleExpando === undefined);
console.log(typeof main.__lambdaBoundaryFromPoint);
console.log(main.__lambdaBoundaryFromPoint(0, 0) === null);
console.log(typeof main.__lambdaTextControlCaretBounds);
console.log(main.__lambdaTextControlCaretBounds() === null);
console.log(main.__lambdaTextControlBoundaryFromPoint(0, 0) === null);
var rect = main.getBoundingClientRect();
console.log(typeof rect.width);
console.log(rect.right === rect.left + rect.width);
var rects = main.getClientRects();
console.log(rects.length);
console.log(typeof rects[0].height);
main.scrollTo(10, 20);
console.log(main.scrollLeft);
console.log(main.scrollTop);
main.scrollBy(5, -10);
console.log(main.scrollLeft);
console.log(main.scrollTop);
main.scroll({ left: -4, top: 7 });
console.log(main.scrollLeft);
console.log(main.scrollTop);
main.scrollIntoView();
console.log(true);
var styleProbe = document.createElement("div");
styleProbe.style.setProperty("color", "blue");
console.log(styleProbe.style.color);
styleProbe.style.setProperty("margin-top", "10px");
console.log(styleProbe.style.marginTop);
console.log(styleProbe.style.removeProperty("color"));
console.log(styleProbe.style.color === "");
console.log(styleProbe.style.marginTop);
console.log(CSS.supports("color", "blue"));
console.log(CSS.escape("1a"));
var sheet = document.styleSheets[0];
console.log(sheet.cssRules.length);
var insertedRule = sheet.insertRule(".module-css { color: green; }", sheet.cssRules.length);
console.log(typeof insertedRule);
var cssRule = sheet.cssRules[insertedRule];
console.log(cssRule.style.getPropertyValue("color"));
cssRule.style.setProperty("margin-top", "4px");
console.log(cssRule.style.marginTop);
console.log(cssRule.style.removeProperty("color"));
console.log(cssRule.style.getPropertyValue("color") === "");
sheet.deleteRule(insertedRule);
console.log(sheet.cssRules.length);

var formsHost = document.createElement("section");
var namedForm = document.createElement("form");
namedForm.setAttribute("name", "moduleNamedForm");
namedForm.setAttribute("id", "moduleFormId");
var sameKeyForm = document.createElement("form");
sameKeyForm.setAttribute("name", "sameKeyForm");
sameKeyForm.setAttribute("id", "sameKeyForm");
formsHost.appendChild(namedForm);
formsHost.appendChild(sameKeyForm);
document.body.appendChild(formsHost);
console.log(document.forms.length);
console.log(document.forms[0] === namedForm);
console.log(document.forms.moduleNamedForm === namedForm);
console.log(document.forms.moduleFormId === namedForm);
console.log(document.forms.sameKeyForm === sameKeyForm);
var liveForms = document.forms;
var liveFormsBase = liveForms.length;
var liveDynamicForm = document.createElement("form");
liveDynamicForm.setAttribute("name", "moduleLiveForm");
formsHost.appendChild(liveDynamicForm);
console.log(liveForms.length === liveFormsBase + 1);
console.log(liveForms[liveFormsBase] === liveDynamicForm);
console.log(liveForms.moduleLiveForm === liveDynamicForm);
liveDynamicForm.setAttribute("name", "moduleLiveFormRenamed");
console.log(liveForms.moduleLiveForm === undefined);
console.log(liveForms.moduleLiveFormRenamed === liveDynamicForm);
formsHost.removeChild(liveDynamicForm);
console.log(liveForms.length === liveFormsBase);
console.log(liveForms.moduleLiveFormRenamed === undefined);

var link = document.createElement("a");
link.setAttribute("href", "/docs");
console.log(link.href);
var image = document.createElement("img");
image.setAttribute("src", "hero.png");
image.setAttribute("alt", "Hero");
console.log(image.src);
console.log(image.alt);
var form = document.createElement("form");
form.setAttribute("novalidate", "");
form.setAttribute("accept-charset", "utf-8");
form.setAttribute("target", "_blank");
console.log(form.noValidate);
console.log(form.acceptCharset);
console.log(form.target);
var moduleFormInput = document.createElement("input");
moduleFormInput.setAttribute("name", "moduleEmail");
var moduleFormButton = document.createElement("button");
moduleFormButton.setAttribute("id", "moduleButtonId");
var moduleFormFieldset = document.createElement("fieldset");
var moduleFormDupA = document.createElement("input");
moduleFormDupA.setAttribute("name", "moduleDup");
var moduleFormDupB = document.createElement("textarea");
moduleFormDupB.setAttribute("name", "moduleDup");
var moduleFormImage = document.createElement("input");
moduleFormImage.setAttribute("type", "image");
moduleFormImage.setAttribute("name", "moduleImage");
moduleFormFieldset.appendChild(moduleFormDupA);
form.appendChild(moduleFormInput);
form.appendChild(moduleFormButton);
form.appendChild(moduleFormFieldset);
form.appendChild(moduleFormDupB);
form.appendChild(moduleFormImage);
console.log(form.elements.length);
console.log(form.length);
console.log(form.elements[0] === moduleFormInput);
console.log(form.elements[2] === moduleFormFieldset);
console.log(form.moduleEmail === moduleFormInput);
console.log(form.moduleButtonId === moduleFormButton);
console.log(form.moduleDup.length);
console.log(form.moduleDup[0] === moduleFormDupA);
console.log(form.moduleDup[1] === moduleFormDupB);
var liveFormElements = form.elements;
var liveFormElementsBase = liveFormElements.length;
var liveExtraControl = document.createElement("textarea");
liveExtraControl.setAttribute("name", "moduleLiveControl");
form.appendChild(liveExtraControl);
console.log(liveFormElements.length === liveFormElementsBase + 1);
console.log(liveFormElements[liveFormElementsBase] === liveExtraControl);
console.log(liveFormElements.moduleLiveControl === liveExtraControl);
liveExtraControl.setAttribute("name", "moduleLiveControlRenamed");
console.log(liveFormElements.moduleLiveControl === undefined);
console.log(liveFormElements.moduleLiveControlRenamed === liveExtraControl);
form.removeChild(liveExtraControl);
console.log(liveFormElements.length === liveFormElementsBase);
console.log(liveFormElements.moduleLiveControlRenamed === undefined);
var moduleFormRequired = document.createElement("input");
moduleFormRequired.setAttribute("required", "");
form.appendChild(moduleFormRequired);
var moduleFormInvalidCount = 0;
moduleFormRequired.addEventListener("invalid", function(e) {
  moduleFormInvalidCount++;
  console.log(e.type);
  console.log(e.cancelable);
});
console.log(form.checkValidity());
console.log(moduleFormInvalidCount);
moduleFormRequired.value = "filled";
console.log(form.reportValidity());
var moduleSubmitCount = 0;
form.addEventListener("submit", function(e) {
  moduleSubmitCount++;
  console.log(e.submitter === null);
});
console.log(!!form.submit);
console.log(moduleSubmitCount);
console.log(form.submit() === undefined);
console.log(moduleSubmitCount);
console.log(form.requestSubmit() === undefined);
console.log(moduleSubmitCount);
var invalidSubmitForm = document.createElement("form");
var invalidSubmitInput = document.createElement("input");
invalidSubmitInput.setAttribute("required", "");
invalidSubmitForm.appendChild(invalidSubmitInput);
document.body.appendChild(invalidSubmitForm);
var invalidSubmitEvents = 0;
var invalidSubmitInvalidEvents = 0;
invalidSubmitForm.addEventListener("submit", function() { invalidSubmitEvents++; });
invalidSubmitInput.addEventListener("invalid", function() { invalidSubmitInvalidEvents++; });
console.log(invalidSubmitForm.requestSubmit() === undefined);
console.log(invalidSubmitInvalidEvents);
console.log(invalidSubmitEvents);
var beforeSubmitHref = document.href;
var navForm = document.createElement("form");
navForm.setAttribute("action", "/module-submit");
var navInput = document.createElement("input");
navInput.setAttribute("name", "q");
navInput.value = "A B";
var navButton = document.createElement("button");
navButton.setAttribute("name", "go");
navButton.setAttribute("value", "yes");
navForm.appendChild(navInput);
navForm.appendChild(navButton);
document.body.appendChild(navForm);
var navSubmitEvents = 0;
navForm.addEventListener("submit", function(e) {
  navSubmitEvents++;
  console.log(e.submitter === navButton);
});
console.log(navForm.requestSubmit(navButton) === undefined);
console.log(navSubmitEvents);
console.log(document.location.pathname);
console.log(document.location.search);
history.replaceState(null, "", beforeSubmitHref);
var moduleResetInput = document.createElement("input");
moduleResetInput.setAttribute("value", "default");
moduleResetInput.value = "changed";
form.appendChild(moduleResetInput);
var moduleResetCanceled = false;
form.addEventListener("reset", function(e) {
  console.log(e.type);
  console.log(e.cancelable);
  console.log(e.isTrusted);
  if (!moduleResetCanceled) {
    moduleResetCanceled = true;
    e.preventDefault();
  }
});
form.reset();
console.log(moduleResetInput.value);
form.reset();
console.log(moduleResetInput.value);
var input = document.createElement("input");
input.setAttribute("required", "");
input.setAttribute("readonly", "");
input.setAttribute("maxlength", "12");
input.setAttribute("minlength", "2");
input.setAttribute("size", "7");
input.setAttribute("placeholder", "Name");
input.setAttribute("pattern", "[a-z]+");
console.log(input.required);
console.log(input.readOnly);
console.log(input.maxLength);
console.log(input.minLength);
console.log(input.size);
console.log(input.placeholder);
console.log(input.pattern);
var textarea = document.createElement("textarea");
textarea.setAttribute("rows", "4");
textarea.setAttribute("cols", "30");
console.log(textarea.rows);
console.log(textarea.cols);
console.log(textarea.wrap);
input.value = "a\nb";
console.log(input.value);
input.selectionStart = 1;
input.selectionEnd = 2;
input.selectionDirection = "backward";
console.log(input.selectionStart);
console.log(input.selectionEnd);
console.log(input.selectionDirection);
input.setSelectionRange(0, 2, "forward");
console.log(input.selectionStart);
console.log(input.selectionEnd);
console.log(input.selectionDirection);
input.setRangeText("Z", 0, 1, "end");
console.log(input.value);
console.log(input.selectionStart);
console.log(input.selectionEnd);
input.select();
console.log(input.selectionStart);
console.log(input.selectionEnd);
input.defaultValue = "seed";
console.log(input.getAttribute("value"));
console.log(input.value);
textarea.defaultValue = "Area";
console.log(textarea.defaultValue);
console.log(textarea.value);
var button = document.createElement("button");
button.setAttribute("formtarget", "panel");
button.setAttribute("formnovalidate", "");
console.log(button.formTarget);
console.log(button.formNoValidate);
var clicked = 0;
button.addEventListener("click", function () { clicked = clicked + 1; });
button.click();
console.log(clicked);
button.disabled = true;
button.click();
console.log(clicked);
var customCount = 0;
function markCustom() { customCount = customCount + 1; }
button.addEventListener("custom", markCustom);
button.dispatchEvent({ type: "custom", bubbles: false });
console.log(customCount);
button.removeEventListener("custom", markCustom);
button.dispatchEvent({ type: "custom", bubbles: false });
console.log(customCount);
var docCustomCount = 0;
function markDocCustom() { docCustomCount = docCustomCount + 1; }
document.addEventListener("doccustom", markDocCustom);
document.dispatchEvent({ type: "doccustom", bubbles: false });
console.log(docCustomCount);
document.removeEventListener("doccustom", markDocCustom);
document.dispatchEvent({ type: "doccustom", bubbles: false });
console.log(docCustomCount);
var winCustomCount = 0;
function markWinCustom() { winCustomCount = winCustomCount + 1; }
addEventListener("wincustom", markWinCustom);
window.dispatchEvent({ type: "wincustom", bubbles: false });
console.log(winCustomCount);
window.removeEventListener("wincustom", markWinCustom);
dispatchEvent({ type: "wincustom", bubbles: false });
console.log(winCustomCount);
input.focus();
console.log(document.activeElement === input);
input.blur();
console.log(document.activeElement === input);
var details = document.createElement("details");
details.setAttribute("open", "");
console.log(details.open);
var option = document.createElement("option");
option.setAttribute("selected", "");
console.log(option.defaultSelected);
var check = document.createElement("input");
check.setAttribute("type", "checkbox");
check.defaultChecked = true;
console.log(check.hasAttribute("checked"));
console.log(check.defaultChecked);
console.log(check.checked);
check.checked = false;
check.defaultChecked = false;
console.log(check.hasAttribute("checked"));
console.log(check.checked);
var select = document.createElement("select");
var optA = document.createElement("option");
var optB = document.createElement("option");
optA.setAttribute("value", "a");
optB.setAttribute("value", "b");
select.appendChild(optA);
select.appendChild(optB);
optB.defaultSelected = true;
console.log(optB.hasAttribute("selected"));
console.log(optB.defaultSelected);
console.log(optB.selected);
console.log(optA.selected);
console.log(select.value);
select.value = "a";
console.log(select.value);
console.log(optA.selected);
console.log(optB.selected);
select.selectedIndex = 1;
console.log(select.selectedIndex);
console.log(select.value);
console.log(optA.selected);
console.log(optB.selected);
optA.selected = true;
console.log(select.selectedIndex);
console.log(select.value);
console.log(optA.selected);
console.log(optB.selected);
console.log(select.length);
console.log(select[0] === optA);
console.log(select.options.length);
console.log(select.options[1] === optB);
console.log(select.options.selectedIndex);
var liveSelectOptions = select.options;
console.log(select.selectedOptions.length);
console.log(select.selectedOptions[0] === optA);
optA.setAttribute("id", "moduleOptA");
console.log(select.namedItem("moduleOptA") === optA);
var optC = document.createElement("option");
optC.setAttribute("value", "c");
select.add(optC);
console.log(select.length);
console.log(select[2] === optC);
console.log(liveSelectOptions.length === 3);
console.log(liveSelectOptions[2] === optC);
console.log(liveSelectOptions.selectedIndex === 0);
select.remove(1);
console.log(select.length);
console.log(optB.parentNode === null);
console.log(select.options[1] === optC);
console.log(liveSelectOptions.length === 2);
console.log(liveSelectOptions[1] === optC);
document.body.appendChild(select);
select.remove();
console.log(select.parentNode === document.body);
select.multiple = true;
console.log(select.hasAttribute("multiple"));
select.multiple = false;
console.log(select.hasAttribute("multiple"));
console.log(optB.selected);
optA.value = "aa";
console.log(optA.getAttribute("value"));
console.log(optA.value);
optA.text = "Alpha";
console.log(optA.text);
console.log(optA.childNodes.length);
select.length = 3;
console.log(select.length);
console.log(select.children.length);
select.length = 1;
console.log(select.length);
console.log(select.children.length);
console.log(select.value);
check.value = "checked-value";
console.log(check.getAttribute("value"));
console.log(check.value);
link.href = "/next";
console.log(link.getAttribute("href"));
console.log(link.href);
input.maxLength = 9;
console.log(input.getAttribute("maxlength"));
console.log(input.maxLength);
textarea.rows = 6;
textarea.wrap = "hard";
console.log(textarea.getAttribute("rows"));
console.log(textarea.rows);
console.log(textarea.getAttribute("wrap"));
console.log(textarea.wrap);
button.formTarget = "modal";
console.log(button.getAttribute("formtarget"));
console.log(button.formTarget);
input.setAttribute("inputmode", "NUMERIC");
input.setAttribute("enterkeyhint", "Go");
console.log(input.inputMode);
console.log(input.enterKeyHint);
input.inputMode = "decimal";
input.enterKeyHint = "send";
console.log(input.getAttribute("inputmode"));
console.log(input.inputMode);
console.log(input.getAttribute("enterkeyhint"));
console.log(input.enterKeyHint);
var editable = document.createElement("div");
var editableChild = document.createElement("span");
editable.setAttribute("contenteditable", "plaintext-only");
editable.appendChild(editableChild);
console.log(editable.contentEditable);
console.log(editable.isContentEditable);
console.log(editableChild.contentEditable);
console.log(editableChild.isContentEditable);
editableChild.setAttribute("contenteditable", "false");
console.log(editableChild.contentEditable);
console.log(editableChild.isContentEditable);
editable.contentEditable = "TRUE";
console.log(editable.getAttribute("contenteditable"));
console.log(editable.contentEditable);
editable.contentEditable = "inherit";
console.log(editable.hasAttribute("contenteditable"));
console.log(editable.contentEditable);
editable.contentEditable = false;
console.log(editable.getAttribute("contenteditable"));
console.log(editable.contentEditable);
editable.contentEditable = "";
console.log(editable.hasAttribute("contenteditable"));
console.log(editable.contentEditable);
var iframe = document.createElement("iframe");
iframe.srcdoc = "<p>Hi</p>";
console.log(iframe.getAttribute("srcdoc"));
document.body.appendChild(iframe);
var frameDoc = iframe.contentDocument;
console.log(frameDoc === iframe.contentWindow);
console.log(frameDoc.defaultView === frameDoc);
console.log(frameDoc.window === frameDoc);
console.log(frameDoc.self === frameDoc);
console.log(frameDoc.document === frameDoc);
console.log(typeof frameDoc.getSelection);
var frameP = frameDoc.querySelector("p");
console.log(frameP.textContent);
frameDoc.moduleExpando = 83;
console.log(frameDoc.moduleExpando);
console.log(frameDoc.getComputedStyle(frameP) === null);
input.autocapitalize = "WORDS";
console.log(input.getAttribute("autocapitalize"));
console.log(input.autocapitalize);
input.autocorrect = false;
console.log(input.getAttribute("autocorrect"));
console.log(input.autocorrect);
editable.spellcheck = false;
console.log(editable.getAttribute("spellcheck"));
console.log(editable.spellcheck);
editable.writingSuggestions = false;
console.log(editable.getAttribute("writingsuggestions"));
console.log(editable.writingSuggestions);
input.required = false;
console.log(input.hasAttribute("required"));
input.required = "yes";
console.log(input.getAttribute("required"));
console.log(input.required);
input.readOnly = 0;
console.log(input.hasAttribute("readonly"));
input.multiple = true;
console.log(input.hasAttribute("multiple"));
form.noValidate = false;
console.log(form.hasAttribute("novalidate"));
button.formNoValidate = false;
console.log(button.hasAttribute("formnovalidate"));
details.open = false;
console.log(details.hasAttribute("open"));
details.open = true;
console.log(details.getAttribute("open"));
console.log(details.open);
main.autofocus = true;
console.log(main.hasAttribute("autofocus"));
main.autofocus = false;
console.log(main.hasAttribute("autofocus"));
button.disabled = true;
console.log(button.getAttribute("disabled"));
console.log(button.disabled);
button.disabled = false;
console.log(button.hasAttribute("disabled"));

var text = document.getElementById("intro").firstChild;
console.log(text.nodeType);
console.log(text.nodeName);
console.log(text.nodeValue);
console.log(text.textContent);
console.log(text.length);
console.log(text.parentNode === document.getElementById("intro"));
console.log(text.parentElement === document.getElementById("intro"));
console.log(text.firstChild === null);
console.log(text.childNodes.length);
console.log(text.isConnected);
text.data = "Beta";
console.log(text.nodeValue);
text.appendData("!");
console.log(text.data);
console.log(text.substringData(1, 3));
text.insertData(0, "A");
console.log(text.data);
text.deleteData(1, 1);
console.log(text.data);
text.replaceData(1, 3, "lpha");
console.log(text.textContent);

var comment = document.createComment("note");
console.log(comment.isConnected);
main.appendChild(comment);
console.log(comment.nodeType);
console.log(comment.nodeName);
console.log(comment.data);
console.log(comment.length);
console.log(comment.parentNode === main);
console.log(comment.previousSibling === document.getElementById("intro"));
console.log(comment.nextSibling === null);
console.log(main.firstChild === document.getElementById("intro"));
console.log(main.lastChild === comment);
console.log(main.childNodes.length);
console.log(document.getElementById("intro").nextSibling === comment);
console.log(comment.previousSibling.parentNode === main);
console.log(comment.isConnected);
console.log(main.isConnected);
console.log(text.ownerDocument === document);
console.log(comment.ownerDocument === document);
console.log(main.ownerDocument === document);
console.log(main.childElementCount);
console.log(main.length);
console.log(main.children.length);
console.log(main.children[0] === document.getElementById("intro"));
console.log(main.firstElementChild === document.getElementById("intro"));
console.log(main.lastElementChild === document.getElementById("intro"));
console.log(document.getElementById("intro").nextElementSibling === null);

var liveChildren = main.children;
var liveChildNodes = main.childNodes;
console.log(liveChildren.length);
console.log(liveChildNodes.length);
var tail = document.createElement("span");
tail.id = "tail";
tail.className = "lookup";
main.appendChild(tail);
console.log(main.childElementCount);
console.log(main.length);
console.log(main.children.length);
console.log(main.children[0] === document.getElementById("intro"));
console.log(main.children[1] === tail);
console.log(liveChildren.length);
console.log(liveChildren[1] === tail);
console.log(liveChildren.namedItem("tail") === tail);
console.log(liveChildNodes.length);
console.log(liveChildNodes[2] === tail);
console.log(main.lastElementChild === tail);
console.log(document.getElementById("intro").nextElementSibling === tail);
console.log(tail.previousElementSibling === document.getElementById("intro"));
console.log(tail.isConnected);
var spans = main.getElementsByTagName("span");
console.log(spans.length);
console.log(spans[0] === tail);
console.log(main.getElementsByTagName("*").length);
var lookup = main.getElementsByClassName("lookup");
console.log(lookup.length);
console.log(lookup[0] === tail);
var liveElementSpans = main.getElementsByTagName("span");
var liveElementLookup = main.getElementsByClassName("lookup");
var liveElementTail = document.createElement("span");
liveElementTail.className = "lookup";
main.appendChild(liveElementTail);
console.log(liveElementSpans.length === 2);
console.log(liveElementSpans[1] === liveElementTail);
console.log(liveElementLookup.length === 2);
liveElementTail.className = "other";
console.log(liveElementLookup.length === 1);
main.removeChild(liveElementTail);
console.log(liveElementSpans.length === 1);
console.log(main.querySelector("#tail") === tail);
console.log(main.querySelectorAll(".lookup").length);
console.log(tail.matches(".lookup"));
console.log(tail.closest("#main") === main);
console.log(main.querySelector(".missing") === null);
console.log(main.getElementById("tail") === tail);
console.log(main.compareDocumentPosition(main));
console.log(main.compareDocumentPosition(tail));
console.log(tail.compareDocumentPosition(main));
console.log(document.getElementById("intro").compareDocumentPosition(tail));
console.log(tail.compareDocumentPosition(document.getElementById("intro")));
var ops = document.createElement("div");
var opA = document.createElement("a");
var opB = document.createElement("b");
var opC = document.createElement("c");
console.log(ops.appendChild(opA) === opA);
ops.appendChild(opC);
console.log(ops.insertBefore(opB, opC) === opB);
console.log(ops.children[0] === opA);
console.log(ops.children[1] === opB);
console.log(ops.children[2] === opC);
console.log(ops.removeChild(opB) === opB);
console.log(opB.parentNode === null);
console.log(ops.children.length);
var moreOps = document.createElement("div");
var oldKid = document.createElement("old-kid");
var newKid = document.createElement("new-kid");
moreOps.appendChild(oldKid);
console.log(moreOps.replaceChild(newKid, oldKid) === oldKid);
console.log(oldKid.parentNode === null);
console.log(moreOps.children[0] === newKid);
var replaceHost = document.createElement("div");
var replaceOne = document.createElement("one");
var replaceTwo = document.createElement("two");
var replaceThree = document.createElement("three");
replaceHost.appendChild(replaceOne);
replaceOne.replaceWith(replaceTwo, replaceThree);
console.log(replaceOne.parentNode === null);
console.log(replaceHost.children[0] === replaceTwo);
console.log(replaceHost.children[1] === replaceThree);
var adjacentParent = document.createElement("div");
var adjacentTarget = document.createElement("target");
var adjacentBefore = document.createElement("before");
var adjacentInside = document.createElement("inside");
var adjacentAfter = document.createElement("after");
adjacentParent.appendChild(adjacentTarget);
console.log(adjacentTarget.insertAdjacentElement("beforebegin", adjacentBefore) === adjacentBefore);
console.log(adjacentTarget.insertAdjacentElement("afterbegin", adjacentInside) === adjacentInside);
console.log(adjacentTarget.insertAdjacentElement("afterend", adjacentAfter) === adjacentAfter);
console.log(adjacentParent.children[0] === adjacentBefore);
console.log(adjacentTarget.firstElementChild === adjacentInside);
console.log(adjacentParent.children[2] === adjacentAfter);
adjacentTarget.insertAdjacentHTML("beforeend", "<span id=\"html-insert\">ok</span>");
console.log(adjacentTarget.lastElementChild.tagName);
console.log(adjacentTarget.lastElementChild.getAttribute("id"));
var variadic = document.createElement("div");
variadic.append("tail");
variadic.prepend("head");
console.log(variadic.childNodes.length);
console.log(variadic.firstChild.data);
console.log(variadic.lastChild.data);
var norm = document.createElement("div");
norm.appendChild(document.createTextNode("a"));
norm.appendChild(document.createTextNode("b"));
norm.normalize();
console.log(norm.childNodes.length);
console.log(norm.firstChild.data);
var cloneSrc = document.createElement("section");
cloneSrc.setAttribute("data-x", "1");
cloneSrc.appendChild(document.createElement("em"));
var clone = cloneSrc.cloneNode(true);
console.log(clone !== cloneSrc);
console.log(clone.getAttribute("data-x"));
console.log(clone.children[0].tagName);
var removable = document.createElement("remove-me");
moreOps.appendChild(removable);
removable.remove();
console.log(removable.parentNode === null);
console.log(moreOps.children.length);
console.log(main.hasChildNodes());
console.log(main.contains(text));
console.log(text.contains(main));
console.log(main.getAttribute("id"));
console.log(main.hasAttribute("class"));
var attrNames = main.getAttributeNames();
console.log(attrNames.indexOf("id") >= 0);
console.log(attrNames.indexOf("class") >= 0);
console.log(attrNames.indexOf("__lambda_ns_uri") === -1);
var attrs = main.attributes;
var sawIdAttr = false;
var sawClassAttr = false;
var sawInternalAttr = false;
for (var i = 0; i < attrs.length; i++) {
    if (attrs[i].name === "id" && attrs[i].value === "main") sawIdAttr = true;
    if (attrs[i].name === "class" && attrs[i].value === "alpha beta") sawClassAttr = true;
    if (attrs[i].name === "__lambda_ns_uri") sawInternalAttr = true;
}
console.log(attrs.length);
console.log(sawIdAttr);
console.log(sawClassAttr);
console.log(sawInternalAttr);
var tpl = document.createElement("template");
var tplChild = document.createElement("span");
tpl.appendChild(tplChild);
console.log(tpl.content === tpl);
console.log(tpl.content.firstChild === tplChild);
main.setAttribute("data-module", 42);
console.log(main.getAttribute("data-module"));
console.log(main.hasAttribute("data-module"));
console.log(main.toggleAttribute("data-module"));
console.log(main.hasAttribute("data-module"));
console.log(main.toggleAttribute("data-module", false));
console.log(main.hasAttribute("data-module"));
main.setAttribute("__lambda_hidden", "secret");
console.log(main.getAttribute("__lambda_hidden") === null);
main.removeAttribute("data-module");
console.log(main.hasAttribute("data-module"));

main.id = "main-updated";
main.className = "gamma delta";
console.log(main.id);
console.log(main.getAttribute("id"));
console.log(document.getElementById("main-updated") === main);
console.log(main.className);
console.log(main.getAttribute("class"));
console.log(document.assign("/pending") === undefined);
console.log(document.replace("/pending-2") === undefined);
console.log(document.reload() === undefined);
console.log(document.focus() === undefined);
console.log(document.blur() === undefined);
console.log(document.write("Doc<br>Write") === null);
console.log(document.body.lastChild.data);
console.log(document.body.lastChild.previousSibling.tagName);
console.log(document.open() === document);
console.log(document.body.childNodes.length);
console.log(document.close() === undefined);
console.log(document.write("After") === null);
console.log(document.body.textContent);
