var source = document.implementation.createHTMLDocument('source');
var article = source.createElement('article');
article.id = 'source-id';
article.className = 'one two';
article.setAttribute('data-storage', 'source');
article.style.cssText = 'color: red; --storage: first';
article.appendChild(source.createTextNode('source text'));
var text = article.firstChild;
var attribute = article.getAttributeNode('data-storage');
document.body.appendChild(article);
console.log(article.ownerDocument === document, text.ownerDocument === document, attribute.ownerDocument === document);
article.id = 'destination-id';
article.className = 'three four';
attribute.value = 'destination';
article.style.setProperty('color', 'blue');
article.style.setProperty('--storage', 'second');
text.nodeValue = 'destination text';
console.log(article.id, article.className, article.textContent, article.style.color, article.style.getPropertyValue('--storage'));
console.log(article.getAttributeNode('data-storage') === attribute, attribute.value);
source.body.appendChild(article);
console.log(article.ownerDocument === source, text.ownerDocument === source, attribute.ownerDocument === source);
text.nodeValue = 'returned text';
article.setAttribute('data-storage', 'returned');
console.log(article.textContent, attribute.value);
document.body.appendChild(article);
article.remove();
for (var i = 0; i < 100; i++) {
    var discarded = source.createElement('aside');
    discarded.id = 'discarded-' + i;
    discarded.className = 'temporary source';
    discarded.setAttribute('data-storage', 'source');
    discarded.textContent = 'discarded:' + i;
    document.body.appendChild(discarded);
    discarded.id = 'adopted-' + i;
    discarded.className = 'temporary adopted';
    discarded.setAttribute('data-storage', 'destination');
    discarded.firstChild.nodeValue = 'updated:' + i;
    discarded.remove();
    discarded = null;
    var allocation = {value: 'allocation:' + i};
}
console.log(article.tagName, article.id, article.textContent, attribute.value, article.ownerDocument === document);
