// Complete Radiant families from utils/check_state_machine.py.
pub let complete_families = [
    {family: "SM_FAMILY_DOCUMENT", label: "document", state_enum: "DocLifecycleState",
     active: ["DOC_LIFECYCLE_UNINITIALIZED", "DOC_LIFECYCLE_LOADING",
              "DOC_LIFECYCLE_COMMITTED", "DOC_LIFECYCLE_UNLOADED"],
     initial: ["DOC_LIFECYCLE_UNINITIALIZED"],
     events: ["SM_EV_DOC_LOAD", "SM_EV_DOC_COMMIT", "SM_EV_DOC_UNLOAD"]},
    {family: "SM_FAMILY_FOCUS", label: "focus", state_enum: "FocusFsmState",
     active: ["FOCUS_NO_DOCUMENT", "FOCUS_DOC_ACTIVE_NONE", "FOCUS_ELEMENT",
              "FOCUS_TEXT_CONTROL", "FOCUS_CONTENTEDITABLE"],
     initial: ["FOCUS_NO_DOCUMENT", "FOCUS_DOC_ACTIVE_NONE"],
     events: ["SM_EV_FOCUS_ELEMENT", "SM_EV_BLUR_CURRENT", "SM_EV_FOCUS_MOVE_FWD",
              "SM_EV_FOCUS_MOVE_BACK", "SM_EV_UI_FOCUS_WITH_BLUR",
              "SM_EV_UI_FOCUS_WITH_CHANGE", "SM_EV_UI_BLUR_WITH_BLUR",
              "SM_EV_UI_BLUR_WITH_CHANGE"]},
    {family: "SM_FAMILY_SELECTION", label: "selection", state_enum: "SelectionFsmState",
     active: ["SEL_EMPTY", "SEL_CARET_COLLAPSED", "SEL_RANGE_FORWARD",
              "SEL_RANGE_BACKWARD", "SEL_POINTER_SELECTING"],
     initial: ["SEL_EMPTY"],
     events: ["SM_EV_COLLAPSE_TO_BOUNDARY", "SM_EV_START_POINTER_SELECTION",
              "SM_EV_UI_START_POINTER_SELECTION", "SM_EV_END_POINTER_SELECTION",
              "SM_EV_EXTEND_TO_BOUNDARY", "SM_EV_EXTEND_TO_VIEW",
              "SM_EV_SET_BASE_AND_EXTENT", "SM_EV_SELECT_ALL",
              "SM_EV_COLLAPSE_TO_START", "SM_EV_COLLAPSE_TO_END",
              "SM_EV_CLEAR_SELECTION"]},
    {family: "SM_FAMILY_IME", label: "ime", state_enum: "ImeFsmState",
     active: ["IME_IDLE", "IME_COMPOSING"], initial: ["IME_IDLE"],
     events: ["SM_EV_COMPOSITION_START", "SM_EV_COMPOSITION_UPDATE",
              "SM_EV_COMPOSITION_COMMIT", "SM_EV_COMPOSITION_CANCEL"]},
    {family: "SM_FAMILY_HOVER", label: "hover", state_enum: "HoverFsmState",
     active: ["HOVER_NONE", "HOVER_TARGET"], initial: ["HOVER_NONE"],
     events: ["SM_EV_HOVER_SET", "SM_EV_HOVER_CLEAR"]},
    {family: "SM_FAMILY_ACTIVE", label: "active", state_enum: "ActiveFsmState",
     active: ["ACTIVE_NONE", "ACTIVE_PRESSED"], initial: ["ACTIVE_NONE"],
     events: ["SM_EV_ACTIVE_SET", "SM_EV_ACTIVE_CLEAR"]},
    {family: "SM_FAMILY_DRAG_DROP", label: "drag_drop", state_enum: "DragFsmState",
     active: ["DRAG_IDLE", "DRAG_PENDING", "DRAG_ACTIVE", "DRAG_OVER_TARGET"],
     initial: ["DRAG_IDLE"],
     events: ["SM_EV_DRAG_SET_STATE", "SM_EV_DRAG_BEGIN_DROP", "SM_EV_DRAG_UPDATE_MOTION",
              "SM_EV_DRAG_SET_DROP_ACTIVE", "SM_EV_DRAG_SET_DROP_TARGET",
              "SM_EV_DRAG_CLEAR_DROP"]},
    {family: "SM_FAMILY_SCROLL", label: "scroll", state_enum: "ScrollFsmState",
     active: ["SCROLL_IDLE", "SCROLL_BAR_HOVER", "SCROLL_BAR_DRAGGING"],
     initial: ["SCROLL_IDLE"],
     events: ["SM_EV_SCROLL_SET_POSITION", "SM_EV_SCROLL_SET_MAX",
              "SM_EV_SCROLLBAR_HOVER", "SM_EV_SCROLLBAR_BEGIN_DRAG",
              "SM_EV_SCROLLBAR_CLEAR_DRAG"]},
    {family: "SM_FAMILY_FORM_CHECKABLE", label: "form_checkable", state_enum: "CheckableFsmState",
     active: ["CHK_UNCHECKED", "CHK_CHECKED"], initial: ["CHK_UNCHECKED"],
     events: ["SM_EV_FORM_SET_CHECKED", "SM_EV_FORM_UNCHECK_RADIO_GROUP",
              "SM_EV_FORM_SET_DISABLED", "SM_EV_FORM_SET_REQUIRED"]},
    {family: "SM_FAMILY_FORM_SELECT", label: "form_select", state_enum: "SelectFsmState",
     active: ["SELCTL_CLOSED", "SELCTL_OPEN"], initial: ["SELCTL_CLOSED"],
     events: ["SM_EV_FORM_SET_SELECTED_INDEX", "SM_EV_FORM_SET_HOVER_INDEX",
              "SM_EV_FORM_SET_DISABLED", "SM_EV_FORM_SET_REQUIRED",
              "SM_EV_DROPDOWN_OPEN", "SM_EV_DROPDOWN_CLOSE"]},
    {family: "SM_FAMILY_FORM_RANGE", label: "form_range", state_enum: "RangeFsmState",
     active: ["RANGE_VALUE"], initial: ["RANGE_VALUE"],
     events: ["SM_EV_FORM_SET_RANGE_VALUE", "SM_EV_FORM_SET_DISABLED",
              "SM_EV_FORM_SET_REQUIRED"]},
    {family: "SM_FAMILY_FORM_TEXT", label: "form_text", state_enum: "TextFsmState",
     active: ["TEXT_EMPTY", "TEXT_VALUE", "TEXT_SELECTION"], initial: ["TEXT_EMPTY"],
     events: ["SM_EV_FORM_SET_VALUE", "SM_EV_FORM_REPLACE_TEXT", "SM_EV_FORM_HISTORY",
              "SM_EV_FORM_SET_SELECTION", "SM_EV_FORM_SET_DISABLED",
              "SM_EV_FORM_SET_READONLY", "SM_EV_FORM_SET_REQUIRED"]},
    {family: "SM_FAMILY_DROPDOWN", label: "dropdown", state_enum: "DropdownFsmState",
     active: ["DD_CLOSED", "DD_OPEN"], initial: ["DD_CLOSED"],
     events: ["SM_EV_DROPDOWN_OPEN", "SM_EV_DROPDOWN_CLOSE",
              "SM_EV_DROPDOWN_SET_GEOMETRY"]},
    {family: "SM_FAMILY_CONTEXT_MENU", label: "context_menu", state_enum: "ContextMenuFsmState",
     active: ["CM_CLOSED", "CM_OPEN", "CM_HOVER"], initial: ["CM_CLOSED"],
     events: ["SM_EV_CONTEXT_MENU_OPEN", "SM_EV_CONTEXT_MENU_CLOSE",
              "SM_EV_CONTEXT_MENU_HOVER"]}
]
