# Test string % formatting
print("Hello, %s!" % "World")
print("Name: %s, Age: %d" % ("Alice", 30))
print("Pi is %.2f" % 3.14159)
print("Hex: %x" % 255)
print("Octal: %o" % 8)
print("Score: %d%%" % 100)
print("%-10s|" % "left")
print("%010d" % 42)

# Test str.format()
print("{} + {} = {}".format(1, 2, 3))
print("{0} and {1}".format("hello", "world"))
print("{:05d}".format(42))
print("{:.2f}".format(3.14159))
print("{:>10}".format("right"))
print("{:<10}|".format("left"))
print("{:^10}".format("center"))
print("{:x}".format(255))
print("{:b}".format(10))
