// TeX engine conformance (Lambda_Pkg_Latex3 §9.9 step 1): the expected
// output is pdfTeX's own, regenerated by
// test/latex/fixtures/tex_engine/make_reference.py.

fn conformance(name) {
    let source = input("test/latex/fixtures/tex_engine/" ++ name ++ ".tex", "text") ^ { "" };
    let report = parse(source, {type: "tex", ini: true}) ^ { {messages: []} };
    ["== " ++ name ++ " ==", *[for (line in report.messages where starts_with(line, "LT:")) line]]
}

join([for (name in ["expansion", "conditionals", "registers", "etex", "tokens", "pdfstrings"],
    line in conformance(name)) line], "\n")
