#include "../jube/jube.h"

#include "py_async.h"
#include "py_bigint.h"
#include "py_class.h"
#include "py_runtime.h"
#include "py_stdlib.h"

// Jube owns the host catalog boundary; this local cast only erases the
// language helper's concrete signature for the reviewed native-module ABI.
#define PY_RUNTIME_IMPORT(fn) ((fn_ptr)(fn))
#define FPTR(fn) PY_RUNTIME_IMPORT(fn)

// Python owns this catalog. The host copies these descriptors into its normal
// MIR import map at module activation, preserving cached direct call targets
// and the conservative MAY_GC default used by the former core-owned entries.
static const JubeRuntimeImport python_runtime_imports[] = {
    {"py_to_int", (fn_ptr)py_to_int},
    {"py_to_float", PY_RUNTIME_IMPORT(py_to_float)},
    {"py_to_str", FPTR(py_to_str)},
    {"py_to_bool", FPTR(py_to_bool)},
    {"py_is_truthy", FPTR(py_is_truthy)},
    {"py_add", FPTR(py_add)},
    {"py_subtract", FPTR(py_subtract)},
    {"py_multiply", FPTR(py_multiply)},
    {"py_divide", FPTR(py_divide)},
    {"py_floor_divide", FPTR(py_floor_divide)},
    {"py_modulo", FPTR(py_modulo)},
    {"py_power", FPTR(py_power)},
    {"py_negate", FPTR(py_negate)},
    {"py_positive", FPTR(py_positive)},
    {"py_bit_not", FPTR(py_bit_not)},
    {"py_bit_and", FPTR(py_bit_and)},
    {"py_bit_or", FPTR(py_bit_or)},
    {"py_bit_xor", FPTR(py_bit_xor)},
    {"py_lshift", FPTR(py_lshift)},
    {"py_rshift", FPTR(py_rshift)},
    {"py_bigint_from_int64", FPTR(py_bigint_from_int64)},
    {"py_bigint_from_cstr", FPTR(py_bigint_from_cstr)},
    {"py_eq", FPTR(py_eq)},
    {"py_ne", FPTR(py_ne)},
    {"py_lt", FPTR(py_lt)},
    {"py_le", FPTR(py_le)},
    {"py_gt", FPTR(py_gt)},
    {"py_ge", FPTR(py_ge)},
    {"py_is", FPTR(py_is)},
    {"py_is_not", FPTR(py_is_not)},
    {"py_contains", FPTR(py_contains)},
    {"py_match_is_sequence", FPTR(py_match_is_sequence)},
    {"py_match_is_mapping", FPTR(py_match_is_mapping)},
    {"py_match_mapping_rest", FPTR(py_match_mapping_rest)},
    {"py_getattr", FPTR(py_getattr)},
    {"py_setattr", FPTR(py_setattr)},
    {"py_hasattr", FPTR(py_hasattr)},
    {"py_delattr", FPTR(py_delattr)},
    {"py_new_object", FPTR(py_new_object)},
    {"py_class_new", FPTR(py_class_new)},
    {"py_class_new_meta", FPTR(py_class_new_meta)},
    {"py_type_new", FPTR(py_type_new)},
    {"py_new_instance", FPTR(py_new_instance)},
    {"py_bind_method", FPTR(py_bind_method)},
    {"py_is_bound_method", FPTR(py_is_bound_method)},
    {"py_is_class", FPTR(py_is_class)},
    {"py_is_instance", FPTR(py_is_instance)},
    {"py_get_class", FPTR(py_get_class)},
    {"py_mro_lookup", FPTR(py_mro_lookup)},
    {"py_super", FPTR(py_super)},
    {"py_isinstance_v3", FPTR(py_isinstance_v3)},
    {"py_issubclass_v3", FPTR(py_issubclass_v3)},
    {"py_list_new", FPTR(py_list_new)},
    {"py_list_append", FPTR(py_list_append)},
    {"py_list_get", FPTR(py_list_get)},
    {"py_list_set", FPTR(py_list_set)},
    {"py_list_length", FPTR(py_list_length)},
    {"py_dict_new", FPTR(py_dict_new)},
    {"py_dict_get", FPTR(py_dict_get)},
    {"py_dict_set", FPTR(py_dict_set)},
    {"py_tuple_new", FPTR(py_tuple_new)},
    {"py_tuple_set", FPTR(py_tuple_set)},
    {"py_subscript_get", FPTR(py_subscript_get)},
    {"py_subscript_set", FPTR(py_subscript_set)},
    {"py_slice_get", FPTR(py_slice_get)},
    {"py_slice_set", FPTR(py_slice_set)},
    {"py_format_value", FPTR(py_format_value)},
    {"py_exception_get_type", FPTR(py_exception_get_type)},
    {"py_builtin_open", FPTR(py_builtin_open)},
    {"py_build_list_from_args", FPTR(py_build_list_from_args)},
    {"py_args_save", FPTR(py_args_save)},
    {"py_args_push", FPTR(py_args_push)},
    {"py_args_store", FPTR(py_args_store)},
    {"py_args_restore", FPTR(py_args_restore)},
    {"py_get_iterator", FPTR(py_get_iterator)},
    {"py_iterator_next", FPTR(py_iterator_next)},
    {"py_range_new", FPTR(py_range_new)},
    {"py_new_function", FPTR(py_new_function)},
    {"py_new_closure", FPTR(py_new_closure)},
    {"py_new_closure_with_env", FPTR(py_new_closure_with_env)},
    {"py_alloc_env", FPTR(py_alloc_env)},
    {"py_closure_get_env", FPTR(py_closure_get_env)},
    {"py_env_store", FPTR(py_env_store)},
    {"py_env_load", FPTR(py_env_load)},
    {"py_set_kwargs_flag", FPTR(py_set_kwargs_flag)},
    {"py_dict_merge", FPTR(py_dict_merge)},
    {"py_call_function", FPTR(py_call_function)},
    {"py_call_function_kw", FPTR(py_call_function_kw)},
    {"py_raise", FPTR(py_raise)},
    {"py_check_exception", FPTR(py_check_exception)},
    {"py_clear_exception", FPTR(py_clear_exception)},
    {"py_new_exception", FPTR(py_new_exception)},
    {"py_context_enter", FPTR(py_context_enter)},
    {"py_context_exit", FPTR(py_context_exit)},
    {"py_resolve_name_item", FPTR(py_resolve_name_item)},
    {"py_set_module_var", FPTR(py_set_module_var)},
    {"py_get_module_var", FPTR(py_get_module_var)},
    {"py_reset_module_vars", FPTR(py_reset_module_vars)},
    {"py_print", FPTR(py_print)},
    {"py_print_ex", FPTR(py_print_ex)},
    {"py_builtin_len", FPTR(py_builtin_len)},
    {"py_builtin_type", FPTR(py_builtin_type)},
    {"py_builtin_isinstance", FPTR(py_builtin_isinstance)},
    {"py_builtin_range", FPTR(py_builtin_range)},
    {"py_builtin_int", FPTR(py_builtin_int)},
    {"py_builtin_float", FPTR(py_builtin_float)},
    {"py_builtin_str", FPTR(py_builtin_str)},
    {"py_builtin_bool", FPTR(py_builtin_bool)},
    {"py_builtin_abs", FPTR(py_builtin_abs)},
    {"py_builtin_min", FPTR(py_builtin_min)},
    {"py_builtin_max", FPTR(py_builtin_max)},
    {"py_builtin_sum", FPTR(py_builtin_sum)},
    {"py_builtin_enumerate", FPTR(py_builtin_enumerate)},
    {"py_builtin_zip", FPTR(py_builtin_zip)},
    {"py_builtin_sorted", FPTR(py_builtin_sorted)},
    {"py_builtin_reversed", FPTR(py_builtin_reversed)},
    {"py_builtin_repr", FPTR(py_builtin_repr)},
    {"py_builtin_hash", FPTR(py_builtin_hash)},
    {"py_builtin_id", FPTR(py_builtin_id)},
    {"py_builtin_input", FPTR(py_builtin_input)},
    {"py_builtin_ord", FPTR(py_builtin_ord)},
    {"py_builtin_chr", FPTR(py_builtin_chr)},
    {"py_builtin_map", FPTR(py_builtin_map)},
    {"py_builtin_filter", FPTR(py_builtin_filter)},
    {"py_builtin_list", FPTR(py_builtin_list)},
    {"py_builtin_dict", FPTR(py_builtin_dict)},
    {"py_builtin_set", FPTR(py_builtin_set)},
    {"py_builtin_tuple", FPTR(py_builtin_tuple)},
    {"py_builtin_round", FPTR(py_builtin_round)},
    {"py_builtin_all", FPTR(py_builtin_all)},
    {"py_builtin_any", FPTR(py_builtin_any)},
    {"py_builtin_bin", FPTR(py_builtin_bin)},
    {"py_builtin_oct", FPTR(py_builtin_oct)},
    {"py_builtin_hex", FPTR(py_builtin_hex)},
    {"py_builtin_divmod", FPTR(py_builtin_divmod)},
    {"py_builtin_pow", FPTR(py_builtin_pow)},
    {"py_builtin_callable", FPTR(py_builtin_callable)},
    {"py_builtin_property", FPTR(py_builtin_property)},
    {"py_property_setter", FPTR(py_property_setter)},
    {"py_property_deleter", FPTR(py_property_deleter)},
    {"py_builtin_sorted_ex", FPTR(py_builtin_sorted_ex)},
    {"py_list_sort_ex", FPTR(py_list_sort_ex)},
    {"py_string_method", FPTR(py_string_method)},
    {"py_list_method", FPTR(py_list_method)},
    {"py_dict_method", FPTR(py_dict_method)},
    {"py_runtime_set_input", FPTR(py_runtime_set_input)},
    {"py_stop_iteration", FPTR(py_stop_iteration)},
    {"py_is_stop_iteration", FPTR(py_is_stop_iteration)},
    {"py_gen_create", FPTR(py_gen_create)},
    {"py_gen_get_frame_c", FPTR(py_gen_get_frame_c)},
    {"py_gen_next", FPTR(py_gen_next)},
    {"py_gen_send", FPTR(py_gen_send)},
    {"py_coro_create", FPTR(py_coro_create)},
    {"py_coro_set_return", FPTR(py_coro_set_return)},
    {"py_coro_get_return", FPTR(py_coro_get_return)},
    {"py_coro_drive", FPTR(py_coro_drive)},
    {"py_asyncio_run", FPTR(py_asyncio_run)},
    {"py_asyncio_sleep", FPTR(py_asyncio_sleep)},
    {"py_asyncio_gather", FPTR(py_asyncio_gather)},
};

extern "C" bool python_jube_register_runtime_imports(
        const JubeRuntimeCatalogAPI* runtime_catalog) {
    return runtime_catalog && runtime_catalog->register_imports &&
        runtime_catalog->register_imports(python_runtime_imports,
        (int)(sizeof(python_runtime_imports) / sizeof(python_runtime_imports[0])),
        "lang-python") == 0;
}
