#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 97
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 0
#define TOKEN_COUNT 42
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 7

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_LBRACE = 2,
  anon_sym_COMMA = 3,
  anon_sym_RBRACE = 4,
  anon_sym_COLON = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  anon_sym_DQUOTE = 8,
  sym_string_content = 9,
  anon_sym_SQUOTE = 10,
  sym_symbol_content = 11,
  sym_escape_sequence = 12,
  sym_number = 13,
  sym_true = 14,
  sym_false = 15,
  sym_null = 16,
  sym_comment = 17,
  anon_sym_LPAREN = 18,
  anon_sym_RPAREN = 19,
  anon_sym_and = 20,
  anon_sym_or = 21,
  anon_sym_PLUS = 22,
  anon_sym_DASH = 23,
  anon_sym_STAR = 24,
  anon_sym_SLASH = 25,
  anon_sym_PERCENT = 26,
  anon_sym_STAR_STAR = 27,
  anon_sym_LT = 28,
  anon_sym_LT_EQ = 29,
  anon_sym_EQ_EQ = 30,
  anon_sym_BANG_EQ = 31,
  anon_sym_GT_EQ = 32,
  anon_sym_GT = 33,
  anon_sym_to = 34,
  anon_sym_in = 35,
  anon_sym_not = 36,
  anon_sym_fn = 37,
  anon_sym_EQ = 38,
  anon_sym_let = 39,
  anon_sym_if = 40,
  anon_sym_else = 41,
  sym_document = 42,
  sym_object = 43,
  sym_pair = 44,
  sym_array = 45,
  sym_string = 46,
  aux_sym__string_content = 47,
  sym_symbol = 48,
  aux_sym__symbol_content = 49,
  sym_expression = 50,
  sym_primary_expr = 51,
  sym_binary_expr = 52,
  sym_unary_expr = 53,
  sym_fn_definition = 54,
  sym_assignment_expr = 55,
  sym_let_expr = 56,
  sym_if_expr = 57,
  aux_sym_document_repeat1 = 58,
  aux_sym_object_repeat1 = 59,
  aux_sym_array_repeat1 = 60,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [anon_sym_SQUOTE] = "'",
  [sym_symbol_content] = "symbol_content",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number] = "number",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_null] = "null",
  [sym_comment] = "comment",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_GT] = ">",
  [anon_sym_to] = "to",
  [anon_sym_in] = "in",
  [anon_sym_not] = "not",
  [anon_sym_fn] = "fn",
  [anon_sym_EQ] = "=",
  [anon_sym_let] = "let",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [sym_document] = "document",
  [sym_object] = "object",
  [sym_pair] = "pair",
  [sym_array] = "array",
  [sym_string] = "string",
  [aux_sym__string_content] = "_string_content",
  [sym_symbol] = "symbol",
  [aux_sym__symbol_content] = "_symbol_content",
  [sym_expression] = "expression",
  [sym_primary_expr] = "primary_expr",
  [sym_binary_expr] = "binary_expr",
  [sym_unary_expr] = "unary_expr",
  [sym_fn_definition] = "fn_definition",
  [sym_assignment_expr] = "assignment_expr",
  [sym_let_expr] = "let_expr",
  [sym_if_expr] = "if_expr",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_symbol_content] = sym_symbol_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number] = sym_number,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_null] = sym_null,
  [sym_comment] = sym_comment,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_to] = anon_sym_to,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [sym_document] = sym_document,
  [sym_object] = sym_object,
  [sym_pair] = sym_pair,
  [sym_array] = sym_array,
  [sym_string] = sym_string,
  [aux_sym__string_content] = aux_sym__string_content,
  [sym_symbol] = sym_symbol,
  [aux_sym__symbol_content] = aux_sym__symbol_content,
  [sym_expression] = sym_expression,
  [sym_primary_expr] = sym_primary_expr,
  [sym_binary_expr] = sym_binary_expr,
  [sym_unary_expr] = sym_unary_expr,
  [sym_fn_definition] = sym_fn_definition,
  [sym_assignment_expr] = sym_assignment_expr,
  [sym_let_expr] = sym_let_expr,
  [sym_if_expr] = sym_if_expr,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_symbol_content] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_to] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__string_content] = {
    .visible = false,
    .named = false,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__symbol_content] = {
    .visible = false,
    .named = false,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_primary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_fn_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_let_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_if_expr] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_body = 2,
  field_cond = 3,
  field_else = 4,
  field_key = 5,
  field_left = 6,
  field_name = 7,
  field_operator = 8,
  field_right = 9,
  field_then = 10,
  field_value = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_body] = "body",
  [field_cond] = "cond",
  [field_else] = "else",
  [field_key] = "key",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_then] = "then",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 3},
  [4] = {.index = 7, .length = 2},
  [5] = {.index = 9, .length = 2},
  [6] = {.index = 11, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_argument, 1},
    {field_operator, 0},
  [2] =
    {field_key, 0},
    {field_value, 2},
  [4] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [7] =
    {field_cond, 2},
    {field_then, 4},
  [9] =
    {field_body, 5},
    {field_name, 1},
  [11] =
    {field_cond, 2},
    {field_else, 6},
    {field_then, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 42,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 29,
  [52] = 34,
  [53] = 40,
  [54] = 36,
  [55] = 39,
  [56] = 38,
  [57] = 37,
  [58] = 58,
  [59] = 31,
  [60] = 60,
  [61] = 61,
  [62] = 61,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 67,
  [69] = 66,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 73,
  [77] = 77,
  [78] = 74,
  [79] = 79,
  [80] = 77,
  [81] = 70,
  [82] = 75,
  [83] = 79,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
};

static TSCharacterRange sym_identifier_character_set_1[] = {
  {'$', '$'}, {'A', 'Z'}, {'\\', '\\'}, {'_', '_'}, {'a', 'z'}, {0x7f, 0x9f}, {0xa1, 0x167f}, {0x1681, 0x1fff},
  {0x200c, 0x2027}, {0x202a, 0x202e}, {0x2030, 0x205e}, {0x2061, 0x2fff}, {0x3001, 0xfefe}, {0xff00, 0x10ffff},
};

static TSCharacterRange sym_identifier_character_set_2[] = {
  {'$', '$'}, {'0', '9'}, {'A', 'Z'}, {'\\', '\\'}, {'_', '_'}, {'a', 'z'}, {0x7f, 0x9f}, {0xa1, 0x167f},
  {0x1681, 0x1fff}, {0x200c, 0x2027}, {0x202a, 0x202e}, {0x2030, 0x205e}, {0x2061, 0x2fff}, {0x3001, 0xfefe}, {0xff00, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '!', 9,
        '"', 30,
        '%', 59,
        '\'', 37,
        '(', 52,
        ')', 53,
        '*', 57,
        '+', 54,
        ',', 25,
        '-', 56,
        '/', 58,
        '0', 46,
        ':', 27,
        '<', 61,
        '=', 69,
        '>', 66,
        '[', 28,
        '\\', 11,
        ']', 29,
        '{', 24,
        '}', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (set_contains(sym_identifier_character_set_2, 15, lookahead)) ADVANCE(67);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '\'') ADVANCE(37);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 9,
        '%', 59,
        ')', 53,
        '*', 57,
        '+', 54,
        ',', 25,
        '-', 55,
        '/', 58,
        '<', 61,
        '=', 10,
        '>', 66,
        '\\', 12,
        ']', 29,
        '}', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (set_contains(sym_identifier_character_set_1, 14, lookahead)) ADVANCE(67);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(37);
      if (lookahead == '/') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(51);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(50);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(64);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(63);
      END_STATE();
    case 11:
      ADVANCE_MAP(
        'u', 45,
        '"', 44,
        '/', 44,
        '\\', 44,
        'b', 44,
        'f', 44,
        'n', 44,
        'r', 44,
        't', 44,
      );
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == '{') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 15:
      ADVANCE_MAP(
        '"', 44,
        '/', 44,
        '\\', 44,
        'b', 44,
        'f', 44,
        'n', 44,
        'r', 44,
        't', 44,
        'u', 44,
      );
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(67);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 21:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '!', 9,
        '"', 30,
        '%', 59,
        '\'', 37,
        '(', 52,
        ')', 53,
        '*', 57,
        '+', 54,
        ',', 25,
        '-', 56,
        '/', 58,
        '0', 46,
        ':', 27,
        '<', 61,
        '=', 69,
        '>', 66,
        '[', 28,
        '\\', 12,
        ']', 29,
        '{', 24,
        '}', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (set_contains(sym_identifier_character_set_2, 15, lookahead)) ADVANCE(67);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '"', 30,
        '\'', 37,
        '(', 52,
        '+', 54,
        ',', 25,
        '-', 56,
        '/', 5,
        '0', 46,
        ':', 27,
        '=', 68,
        '[', 28,
        '\\', 12,
        ']', 29,
        '{', 24,
        '}', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(22);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (set_contains(sym_identifier_character_set_2, 15, lookahead)) ADVANCE(67);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '*') ADVANCE(33);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '*') ADVANCE(32);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '*') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '/') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_symbol_content);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '/') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(43);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_symbol_content);
      if (lookahead == '*') ADVANCE(39);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_symbol_content);
      if (lookahead == '*') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_symbol_content);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(43);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_symbol_content);
      if (lookahead == '\r' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_symbol_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (lookahead == '{') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(48);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(48);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '0') ADVANCE(46);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(60);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(51);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(65);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(12);
      if (set_contains(sym_identifier_character_set_2, 15, lookahead)) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(63);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'e', 2,
        'f', 3,
        'i', 4,
        'l', 5,
        'n', 6,
        'o', 7,
        't', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(11);
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(13);
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(16);
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_to);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 22},
  [2] = {.lex_state = 22},
  [3] = {.lex_state = 22},
  [4] = {.lex_state = 22},
  [5] = {.lex_state = 22},
  [6] = {.lex_state = 22},
  [7] = {.lex_state = 22},
  [8] = {.lex_state = 22},
  [9] = {.lex_state = 22},
  [10] = {.lex_state = 22},
  [11] = {.lex_state = 22},
  [12] = {.lex_state = 22},
  [13] = {.lex_state = 22},
  [14] = {.lex_state = 22},
  [15] = {.lex_state = 22},
  [16] = {.lex_state = 22},
  [17] = {.lex_state = 22},
  [18] = {.lex_state = 22},
  [19] = {.lex_state = 22},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 22},
  [50] = {.lex_state = 22},
  [51] = {.lex_state = 22},
  [52] = {.lex_state = 22},
  [53] = {.lex_state = 22},
  [54] = {.lex_state = 22},
  [55] = {.lex_state = 22},
  [56] = {.lex_state = 22},
  [57] = {.lex_state = 22},
  [58] = {.lex_state = 22},
  [59] = {.lex_state = 22},
  [60] = {.lex_state = 22},
  [61] = {.lex_state = 22},
  [62] = {.lex_state = 22},
  [63] = {.lex_state = 22},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 3},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 3},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 22},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 22},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 22},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_to] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(95),
    [sym_object] = STATE(50),
    [sym_array] = STATE(50),
    [sym_string] = STATE(50),
    [sym_symbol] = STATE(50),
    [sym_fn_definition] = STATE(50),
    [aux_sym_document_repeat1] = STATE(50),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [sym_true] = ACTIONS(15),
    [sym_false] = ACTIONS(15),
    [sym_null] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_RBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(43), 1,
      sym_expression,
    STATE(77), 1,
      aux_sym_array_repeat1,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [66] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    ACTIONS(45), 1,
      anon_sym_RBRACK,
    STATE(42), 1,
      sym_expression,
    STATE(80), 1,
      aux_sym_array_repeat1,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [132] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(44), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(47), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [193] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(48), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [250] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(30), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [307] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(45), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [364] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(23), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [421] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(22), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [478] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(20), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [535] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(26), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [592] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(27), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [649] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(21), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [706] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(28), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [763] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(46), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [820] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(32), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [877] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(33), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [934] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(47), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [991] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(41), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    STATE(35), 1,
      sym_expression,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(19), 4,
      sym_true,
      sym_false,
      sym_null,
      sym_identifier,
    STATE(41), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
    STATE(24), 5,
      sym_primary_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_let_expr,
      sym_if_expr,
  [1048] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(51), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 15,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
      anon_sym_else,
  [1083] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(57), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 16,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
      anon_sym_else,
  [1114] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(59), 1,
      anon_sym_and,
    ACTIONS(51), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(61), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(63), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(65), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
    ACTIONS(49), 6,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_else,
  [1157] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(51), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(61), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(63), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(65), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
    ACTIONS(49), 7,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_else,
  [1198] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(69), 17,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_STAR_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
      anon_sym_else,
  [1227] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(73), 17,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_STAR_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
      anon_sym_else,
  [1256] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(57), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 16,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
      anon_sym_else,
  [1287] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(51), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(61), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(49), 13,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
      anon_sym_else,
  [1324] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(51), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(61), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(63), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(65), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
    ACTIONS(49), 9,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_else,
  [1363] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 17,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_STAR_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
      anon_sym_else,
  [1392] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(81), 17,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_STAR_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
      anon_sym_else,
  [1421] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 17,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_STAR_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
      anon_sym_else,
  [1450] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(59), 1,
      anon_sym_and,
    ACTIONS(91), 1,
      anon_sym_or,
    ACTIONS(51), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(61), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(63), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(65), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
    ACTIONS(89), 5,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_else,
  [1495] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(59), 1,
      anon_sym_and,
    ACTIONS(91), 1,
      anon_sym_or,
    ACTIONS(95), 1,
      anon_sym_else,
    ACTIONS(51), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(61), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(63), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(65), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
    ACTIONS(93), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1542] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(97), 17,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_STAR_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
      anon_sym_else,
  [1571] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(59), 1,
      anon_sym_and,
    ACTIONS(91), 1,
      anon_sym_or,
    ACTIONS(51), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(61), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(63), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(65), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
    ACTIONS(101), 5,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_else,
  [1616] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(103), 17,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_STAR_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
      anon_sym_else,
  [1645] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(107), 17,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_STAR_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
      anon_sym_else,
  [1674] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(111), 17,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_STAR_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
      anon_sym_else,
  [1703] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(115), 17,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_STAR_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
      anon_sym_else,
  [1732] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(119), 17,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_STAR_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
      anon_sym_else,
  [1761] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(123), 17,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_STAR_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
      anon_sym_else,
  [1790] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(59), 1,
      anon_sym_and,
    ACTIONS(91), 1,
      anon_sym_or,
    ACTIONS(127), 1,
      anon_sym_RBRACK,
    STATE(70), 1,
      aux_sym_array_repeat1,
    ACTIONS(51), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(61), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(63), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(65), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
  [1837] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(59), 1,
      anon_sym_and,
    ACTIONS(91), 1,
      anon_sym_or,
    ACTIONS(129), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      aux_sym_array_repeat1,
    ACTIONS(51), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(61), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(63), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(65), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
  [1884] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(59), 1,
      anon_sym_and,
    ACTIONS(91), 1,
      anon_sym_or,
    ACTIONS(51), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(61), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(63), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(131), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(65), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
  [1926] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(59), 1,
      anon_sym_and,
    ACTIONS(91), 1,
      anon_sym_or,
    ACTIONS(133), 1,
      anon_sym_RPAREN,
    ACTIONS(51), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(61), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(63), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(65), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
  [1967] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(59), 1,
      anon_sym_and,
    ACTIONS(91), 1,
      anon_sym_or,
    ACTIONS(135), 1,
      anon_sym_RPAREN,
    ACTIONS(51), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(61), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(63), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(65), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
  [2008] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(59), 1,
      anon_sym_and,
    ACTIONS(91), 1,
      anon_sym_or,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    ACTIONS(51), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(61), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(63), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(65), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
  [2049] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_STAR_STAR,
    ACTIONS(59), 1,
      anon_sym_and,
    ACTIONS(91), 1,
      anon_sym_or,
    ACTIONS(139), 1,
      anon_sym_RPAREN,
    ACTIONS(51), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(61), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(63), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(65), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_to,
      anon_sym_in,
  [2090] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    ACTIONS(143), 1,
      anon_sym_LBRACE,
    ACTIONS(146), 1,
      anon_sym_LBRACK,
    ACTIONS(149), 1,
      anon_sym_DQUOTE,
    ACTIONS(152), 1,
      anon_sym_SQUOTE,
    ACTIONS(158), 1,
      anon_sym_fn,
    ACTIONS(155), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(49), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
      sym_fn_definition,
      aux_sym_document_repeat1,
  [2126] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    ACTIONS(163), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(49), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
      sym_fn_definition,
      aux_sym_document_repeat1,
  [2162] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
      anon_sym_fn,
  [2181] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
      anon_sym_fn,
  [2200] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
      anon_sym_fn,
  [2218] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
      anon_sym_fn,
  [2236] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
      anon_sym_fn,
  [2254] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
      anon_sym_fn,
  [2272] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
      anon_sym_fn,
  [2290] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(165), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(84), 4,
      sym_object,
      sym_array,
      sym_string,
      sym_symbol,
  [2318] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
      anon_sym_fn,
  [2336] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
      anon_sym_fn,
  [2352] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(169), 1,
      sym_identifier,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    STATE(74), 1,
      sym_pair,
    STATE(91), 2,
      sym_string,
      sym_symbol,
  [2375] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(169), 1,
      sym_identifier,
    ACTIONS(173), 1,
      anon_sym_RBRACE,
    STATE(78), 1,
      sym_pair,
    STATE(91), 2,
      sym_string,
      sym_symbol,
  [2398] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(169), 1,
      sym_identifier,
    STATE(85), 1,
      sym_pair,
    STATE(91), 2,
      sym_string,
      sym_symbol,
  [2418] = 4,
    ACTIONS(175), 1,
      anon_sym_SQUOTE,
    ACTIONS(180), 1,
      sym_comment,
    STATE(64), 1,
      aux_sym__symbol_content,
    ACTIONS(177), 2,
      sym_symbol_content,
      sym_escape_sequence,
  [2432] = 4,
    ACTIONS(180), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      aux_sym__string_content,
    ACTIONS(184), 2,
      sym_string_content,
      sym_escape_sequence,
  [2446] = 4,
    ACTIONS(180), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_SQUOTE,
    STATE(64), 1,
      aux_sym__symbol_content,
    ACTIONS(189), 2,
      sym_symbol_content,
      sym_escape_sequence,
  [2460] = 4,
    ACTIONS(180), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      aux_sym__string_content,
    ACTIONS(193), 2,
      sym_string_content,
      sym_escape_sequence,
  [2474] = 4,
    ACTIONS(180), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      aux_sym__string_content,
    ACTIONS(193), 2,
      sym_string_content,
      sym_escape_sequence,
  [2488] = 4,
    ACTIONS(180), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_SQUOTE,
    STATE(64), 1,
      aux_sym__symbol_content,
    ACTIONS(189), 2,
      sym_symbol_content,
      sym_escape_sequence,
  [2502] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_RBRACK,
    STATE(72), 1,
      aux_sym_array_repeat1,
  [2515] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_COMMA,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym_object_repeat1,
  [2528] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_RBRACK,
    ACTIONS(206), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym_array_repeat1,
  [2541] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_COMMA,
    ACTIONS(211), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym_object_repeat1,
  [2554] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_COMMA,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(73), 1,
      aux_sym_object_repeat1,
  [2567] = 3,
    ACTIONS(180), 1,
      sym_comment,
    STATE(68), 1,
      aux_sym__string_content,
    ACTIONS(215), 2,
      sym_string_content,
      sym_escape_sequence,
  [2578] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym_object_repeat1,
  [2591] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(129), 1,
      anon_sym_RBRACK,
    STATE(72), 1,
      aux_sym_array_repeat1,
  [2604] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_COMMA,
    ACTIONS(219), 1,
      anon_sym_RBRACE,
    STATE(76), 1,
      aux_sym_object_repeat1,
  [2617] = 3,
    ACTIONS(180), 1,
      sym_comment,
    STATE(69), 1,
      aux_sym__symbol_content,
    ACTIONS(221), 2,
      sym_symbol_content,
      sym_escape_sequence,
  [2628] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(127), 1,
      anon_sym_RBRACK,
    STATE(72), 1,
      aux_sym_array_repeat1,
  [2641] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(223), 1,
      anon_sym_RBRACK,
    STATE(72), 1,
      aux_sym_array_repeat1,
  [2654] = 3,
    ACTIONS(180), 1,
      sym_comment,
    STATE(67), 1,
      aux_sym__string_content,
    ACTIONS(225), 2,
      sym_string_content,
      sym_escape_sequence,
  [2665] = 3,
    ACTIONS(180), 1,
      sym_comment,
    STATE(66), 1,
      aux_sym__symbol_content,
    ACTIONS(227), 2,
      sym_symbol_content,
      sym_escape_sequence,
  [2676] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2684] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2692] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      sym_identifier,
    STATE(93), 1,
      sym_assignment_expr,
  [2702] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_LPAREN,
  [2709] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_LPAREN,
  [2716] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_LBRACE,
  [2723] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
  [2730] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_COLON,
  [2737] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_EQ,
  [2744] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
  [2751] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_LPAREN,
  [2758] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
  [2765] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 66,
  [SMALL_STATE(4)] = 132,
  [SMALL_STATE(5)] = 193,
  [SMALL_STATE(6)] = 250,
  [SMALL_STATE(7)] = 307,
  [SMALL_STATE(8)] = 364,
  [SMALL_STATE(9)] = 421,
  [SMALL_STATE(10)] = 478,
  [SMALL_STATE(11)] = 535,
  [SMALL_STATE(12)] = 592,
  [SMALL_STATE(13)] = 649,
  [SMALL_STATE(14)] = 706,
  [SMALL_STATE(15)] = 763,
  [SMALL_STATE(16)] = 820,
  [SMALL_STATE(17)] = 877,
  [SMALL_STATE(18)] = 934,
  [SMALL_STATE(19)] = 991,
  [SMALL_STATE(20)] = 1048,
  [SMALL_STATE(21)] = 1083,
  [SMALL_STATE(22)] = 1114,
  [SMALL_STATE(23)] = 1157,
  [SMALL_STATE(24)] = 1198,
  [SMALL_STATE(25)] = 1227,
  [SMALL_STATE(26)] = 1256,
  [SMALL_STATE(27)] = 1287,
  [SMALL_STATE(28)] = 1324,
  [SMALL_STATE(29)] = 1363,
  [SMALL_STATE(30)] = 1392,
  [SMALL_STATE(31)] = 1421,
  [SMALL_STATE(32)] = 1450,
  [SMALL_STATE(33)] = 1495,
  [SMALL_STATE(34)] = 1542,
  [SMALL_STATE(35)] = 1571,
  [SMALL_STATE(36)] = 1616,
  [SMALL_STATE(37)] = 1645,
  [SMALL_STATE(38)] = 1674,
  [SMALL_STATE(39)] = 1703,
  [SMALL_STATE(40)] = 1732,
  [SMALL_STATE(41)] = 1761,
  [SMALL_STATE(42)] = 1790,
  [SMALL_STATE(43)] = 1837,
  [SMALL_STATE(44)] = 1884,
  [SMALL_STATE(45)] = 1926,
  [SMALL_STATE(46)] = 1967,
  [SMALL_STATE(47)] = 2008,
  [SMALL_STATE(48)] = 2049,
  [SMALL_STATE(49)] = 2090,
  [SMALL_STATE(50)] = 2126,
  [SMALL_STATE(51)] = 2162,
  [SMALL_STATE(52)] = 2181,
  [SMALL_STATE(53)] = 2200,
  [SMALL_STATE(54)] = 2218,
  [SMALL_STATE(55)] = 2236,
  [SMALL_STATE(56)] = 2254,
  [SMALL_STATE(57)] = 2272,
  [SMALL_STATE(58)] = 2290,
  [SMALL_STATE(59)] = 2318,
  [SMALL_STATE(60)] = 2336,
  [SMALL_STATE(61)] = 2352,
  [SMALL_STATE(62)] = 2375,
  [SMALL_STATE(63)] = 2398,
  [SMALL_STATE(64)] = 2418,
  [SMALL_STATE(65)] = 2432,
  [SMALL_STATE(66)] = 2446,
  [SMALL_STATE(67)] = 2460,
  [SMALL_STATE(68)] = 2474,
  [SMALL_STATE(69)] = 2488,
  [SMALL_STATE(70)] = 2502,
  [SMALL_STATE(71)] = 2515,
  [SMALL_STATE(72)] = 2528,
  [SMALL_STATE(73)] = 2541,
  [SMALL_STATE(74)] = 2554,
  [SMALL_STATE(75)] = 2567,
  [SMALL_STATE(76)] = 2578,
  [SMALL_STATE(77)] = 2591,
  [SMALL_STATE(78)] = 2604,
  [SMALL_STATE(79)] = 2617,
  [SMALL_STATE(80)] = 2628,
  [SMALL_STATE(81)] = 2641,
  [SMALL_STATE(82)] = 2654,
  [SMALL_STATE(83)] = 2665,
  [SMALL_STATE(84)] = 2676,
  [SMALL_STATE(85)] = 2684,
  [SMALL_STATE(86)] = 2692,
  [SMALL_STATE(87)] = 2702,
  [SMALL_STATE(88)] = 2709,
  [SMALL_STATE(89)] = 2716,
  [SMALL_STATE(90)] = 2723,
  [SMALL_STATE(91)] = 2730,
  [SMALL_STATE(92)] = 2737,
  [SMALL_STATE(93)] = 2744,
  [SMALL_STATE(94)] = 2751,
  [SMALL_STATE(95)] = 2758,
  [SMALL_STATE(96)] = 2765,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3, 0, 3),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expr, 3, 0, 3),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_expr, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary_expr, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expr, 2, 0, 1),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expr, 2, 0, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_expr, 5, 0, 4),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expr, 5, 0, 4),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expr, 7, 0, 6),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 4, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_expr, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary_expr, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expr, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_definition, 7, 0, 5),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__symbol_content, 2, 0, 0),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__symbol_content, 2, 0, 0), SHIFT_REPEAT(64),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__string_content, 2, 0, 0),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__string_content, 2, 0, 0), SHIFT_REPEAT(65),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 2),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [249] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lambda(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
