// Phase 1 smoke test (multi-page): verifies pdf_to_svg works for each page
// of a 3-page PDF generated by libharu in the gtest fixture.
//
// Procedural form because the pdf API is `pn` (drives the content-stream
// interpreter via var/while).

import pdf: lambda.package.pdf.pdf

pn main() {
    let doc^err = input("test/input/advanced_test.pdf", 'pdf')
    let n = pdf.pdf_page_count(doc)
    var pages = []
    var i = 0
    while (i < n) {
        let xml = format(pdf.pdf_to_svg(doc, i, null), 'xml')
        pages = pages ++ [{
            has_svg: contains(xml, "<svg "),
            has_background: contains(xml, "<rect x=\"0\" y=\"0\""),
            path_count: string_count(xml, "<path "),
            text_count: string_count(xml, "<text ")
        }]
        i = i + 1
    }
    print({
        page_count: n,
        pages: pages
    })
}

fn contains(s, sub) {
    let parts = split(s, sub)
    (len(parts) >= 2)
}

fn string_count(s, sub) {
    let parts = split(s, sub)
    len(parts) - 1
}
