// Divergence report — the conformance gauge (informational, never a gate).
//
// Runs the same convertible Chromium tests as the harvester, but instead of
// recording our output, compares OUR result to CHROMIUM's expected at the
// text-content level (both stripped identically), and reports the match rate +
// a categorized sample of divergences. This shows exactly where our editor
// differs from a real browser — the highest-signal artifact for the port.
//
// Run with:  npx vite-node tools/divergence-report.ts [categories…]

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { JSDOM } from 'jsdom'
import { extractAsserts, parseTester, convertInput, eventsJsonOf, expectedPlainText, walk, type Op } from './chromium-adapt.ts'

const jsdom = new JSDOM()
;(globalThis as unknown as { DOMParser: typeof DOMParser }).DOMParser = jsdom.window.DOMParser as unknown as typeof DOMParser

const { serializeDocToHtml } = await import('../src/view/html-parser.ts')
const { docSchema } = await import('../src/schemas/doc.ts')
const { runFixtureCase } = await import('../test/helpers/fixture-runner.ts')

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const CHROMIUM = path.resolve(__dirname, '../../../../lambda-test/editing')
const REPORT = path.resolve(__dirname, '../../../vibe/Chromium_Divergence_Report.md')
const CATEGORIES = process.argv.slice(2).length ? process.argv.slice(2)
  : ['inserting', 'deleting', 'execCommand', 'style', 'input', 'selection', 'pasteboard']

const strict = (s: string): string => s.replace(/\r/g, '').replace(/[ \t]+\n/g, '\n').replace(/\n+/g, '\n').trim()
const collapsed = (s: string): string => s.replace(/\s+/g, ' ').trim()

type Verdict = 'exact' | 'whitespace' | 'content' | 'error'
interface Row { cat: string; name: string; ops: string; our: string; chrome: string; verdict: Verdict }

// Run a converted test and classify our output text vs Chromium's expected.
function classify(inputHtml: string, ops: Op[], expectedHtml: string): { verdict: Verdict; our: string; chrome: string } {
  const chrome = expectedPlainText(expectedHtml)
  let our: string
  try {
    const r = runFixtureCase({ name: '', dir: '', inputHtml, eventsJson: eventsJsonOf(ops), outputHtml: inputHtml })
    our = expectedPlainText(serializeDocToHtml(r.actualDoc, { schema: docSchema }))
  } catch {
    return { verdict: 'error', our: '<error>', chrome }
  }
  if (strict(our) === strict(chrome)) return { verdict: 'exact', our, chrome }
  if (collapsed(our) === collapsed(chrome)) return { verdict: 'whitespace', our, chrome }
  return { verdict: 'content', our, chrome }
}

function opsSummary(ops: Op[]): string {
  return ops.map(o => o.command + (o.args && 'text' in o.args ? `(${JSON.stringify(o.args['text'])})`
    : o.args && 'mark' in o.args ? `(${o.args['mark']})`
    : o.args && 'html' in o.args ? `(html)` : '')).join(' → ').slice(0, 80)
}

const rows: Row[] = []
const perCat: Record<string, Record<Verdict, number>> = {}
const bump = (cat: string, v: Verdict): void => {
  perCat[cat] ??= { exact: 0, whitespace: 0, content: 0, error: 0 }
  perCat[cat]![v]++
}

for (const cat of CATEGORIES) {
  const files: string[] = []
  walk(path.join(CHROMIUM, cat), files)
  for (const file of files) {
    const src = fs.readFileSync(file, 'utf8')
    if (!src.includes('assert_selection')) continue
    const base = path.basename(file, '.html')
    let n = 0
    for (const a of extractAsserts(src)) {
      const ops = parseTester(a.tester)
      if (ops === null) continue
      const inputHtml = convertInput(a.input)
      if (inputHtml === null) continue
      const { verdict, our, chrome } = classify(inputHtml, ops, a.expected)
      bump(cat, verdict)
      rows.push({ cat, name: `${base}-${a.name || n++}`, ops: opsSummary(ops), our, chrome, verdict })
    }
  }
}

// ---- assemble the report ------------------------------------------------
const total = rows.length
const tally = (v: Verdict): number => rows.filter(r => r.verdict === v).length
const pct = (n: number): string => total === 0 ? '0%' : `${(100 * n / total).toFixed(1)}%`
const conform = tally('exact') + tally('whitespace')

const L: string[] = []
L.push('# Chromium Editing — Divergence Report')
L.push('')
L.push('Conformance gauge (informational, never a gate). For every Chromium `assert_selection`')
L.push('test we can express (input convertible to our schema, ops supported), we replay it through')
L.push('our editor and compare the **plain text** of our result to Chromium\'s **expected**, both')
L.push('stripped identically (tags/markers removed, block ends → newlines). Generated by')
L.push('`tools/divergence-report.ts`.')
L.push('')
L.push('## Overall')
L.push('')
L.push(`- **Compared:** ${total} tests`)
L.push(`- **Exact text match:** ${tally('exact')} (${pct(tally('exact'))})`)
L.push(`- **Whitespace-only divergence:** ${tally('whitespace')} (${pct(tally('whitespace'))}) — same text, different spacing`)
L.push(`- **Text-conformant (exact + whitespace):** ${conform} (${pct(conform)})`)
L.push(`- **Content divergence:** ${tally('content')} (${pct(tally('content'))}) — our result differs in non-whitespace content`)
L.push(`- **Errors:** ${tally('error')} (${pct(tally('error'))}) — our editor threw on the sequence`)
L.push('')
L.push('## By category')
L.push('')
L.push('| Category | Compared | Exact | Whitespace | Content | Error | Text-conformant |')
L.push('|---|---:|---:|---:|---:|---:|---:|')
for (const cat of CATEGORIES) {
  const c = perCat[cat]
  if (!c) continue
  const t = c.exact + c.whitespace + c.content + c.error
  const cf = t === 0 ? '—' : `${(100 * (c.exact + c.whitespace) / t).toFixed(0)}%`
  L.push(`| ${cat} | ${t} | ${c.exact} | ${c.whitespace} | ${c.content} | ${c.error} | ${cf} |`)
}
L.push('')
L.push('## Key findings — the divergence classes')
L.push('')
L.push('Reading the content divergences, they cluster into a few stable behaviours where our')
L.push('PM/Slate-class model intentionally or not-yet matches a browser:')
L.push('')
L.push('1. **Cross-block backspace-merge (`joinBackward`) — IMPLEMENTED.** `deleteContentBackward`')
L.push('   at the *start* of a block now merges it into the previous block (descending into a')
L.push('   previous list’s last item / heading, keeping the target tag). This included fixing a')
L.push('   tree-corruption bug where a selection spanning only a block boundary was treated as a')
L.push('   range over the doc root. Lifted `deleting` conformance ~41% → ~61%.')
L.push('2. **Select-all + delete — IMPLEMENTED.** A multi-block (e.g. whole-document) text range now')
L.push('   deletes, keeping the start block’s prefix + end block’s suffix and leaving a single')
L.push('   (often empty) block.')
L.push('3. **Whitespace / `&nbsp;` fixup — intentional difference (now the dominant divergence).**')
L.push('   Chrome rewrites runs of spaces and leading/trailing spaces into `\\u00A0` to defeat HTML')
L.push('   collapsing; we store raw text. After (1)–(2), nearly all remaining `inserting` and')
L.push('   `deleting` divergences are this. A PM-class editor deliberately does not replicate it —')
L.push('   informational, not a bug.')
L.push('4. **`insertHTML` of `<div>` blocks — structural.** Chrome flattens pasted `<div>`s inline')
L.push('   in some contexts; we treat them as blocks (extra newline). Tied to our schema not')
L.push('   modelling `<div>`.')
L.push('5. **Caret-movement landing points / forward join.** A few sequences differ because our')
L.push('   headless caret movement lands on different stops, or because `deleteContentForward` at a')
L.push('   block *end* does not yet `joinForward`. The next actionable item.')
L.push('')
L.push('Status: the two structural gaps the previous report flagged — **(1) joinBackward** and')
L.push('**(2) select-all delete** — are now implemented. Remaining divergences are the intentional')
L.push('whitespace model (3), the `<div>` schema gap (4), and `joinForward` (5).')
L.push('')

function sampleBlock(title: string, verdict: Verdict, limit: number): void {
  const sample = rows.filter(r => r.verdict === verdict).slice(0, limit)
  if (sample.length === 0) return
  L.push(`## ${title}`)
  L.push('')
  for (const r of sample) {
    L.push(`- **${r.cat}/${r.name}** — \`${r.ops}\``)
    L.push(`  - ours:   \`${JSON.stringify(strict(r.our))}\``)
    L.push(`  - chrome: \`${JSON.stringify(strict(r.chrome))}\``)
  }
  L.push('')
}
sampleBlock('Content divergences (sample)', 'content', 30)
sampleBlock('Whitespace-only divergences (sample)', 'whitespace', 12)
sampleBlock('Errors (sample)', 'error', 12)

const out = L.join('\n') + '\n'
fs.writeFileSync(REPORT, out)
console.log(out)
console.log(`\n(written to ${path.relative(path.resolve(__dirname, '../../..'), REPORT)})`)
