#!/usr/bin/env python3
"""
Generate the unified HTML entity table from the WHATWG spec.

Downloads entities.json from the WHATWG spec and generates:
  - lambda/input/html_entities_table.inc : sorted HtmlEntityEntry array

Usage:
    python3 utils/generate_html5_entities.py                  # fetch from web
    python3 utils/generate_html5_entities.py entities.json     # use local file

Output is written to: lambda/input/html_entities_table.inc
"""

import json
import os
import sys
import urllib.request


def codepoints_to_utf8_string(codepoints):
    """Convert list of codepoints to UTF-8 bytes."""
    return ''.join(chr(cp) for cp in codepoints).encode('utf-8')


def escape_c_string(utf8_bytes):
    """Escape UTF-8 bytes for C string literal."""
    result = []
    for b in utf8_bytes:
        if 0x20 <= b <= 0x7E and b not in (ord('"'), ord('\\')):
            result.append(chr(b))
        else:
            result.append(f'\\x{b:02X}')
    return ''.join(result)


def main():
    # Load entity list — from local file or from web
    if len(sys.argv) > 1 and os.path.isfile(sys.argv[1]):
        with open(sys.argv[1], 'r') as f:
            entities = json.load(f)
    else:
        url = "https://html.spec.whatwg.org/entities.json"
        try:
            with urllib.request.urlopen(url) as response:
                entities = json.loads(response.read().decode('utf-8'))
        except Exception as e:
            print(f"Error fetching entities: {e}", file=sys.stderr)
            sys.exit(1)

    # Process: keep only semicolon-terminated entries (canonical), strip the ;
    processed = {}
    for name, data in entities.items():
        if not name.startswith('&'):
            continue
        entity_name = name[1:]  # remove leading &
        if not entity_name.endswith(';'):
            continue
        clean_name = entity_name[:-1]  # remove trailing ;

        codepoints = data.get('codepoints', [])
        if not codepoints:
            continue

        try:
            utf8_bytes = codepoints_to_utf8_string(codepoints)
            utf8_escaped = escape_c_string(utf8_bytes)
        except Exception as e:
            print(f"// Error processing {name}: {e}", file=sys.stderr)
            continue

        processed[clean_name] = utf8_escaped

    # Sort alphabetically for binary search
    sorted_names = sorted(processed.keys())

    # Determine output path
    script_dir = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(script_dir, '..', 'lambda', 'input', 'html_entities_table.inc')
    out_path = os.path.normpath(out_path)

    with open(out_path, 'w') as f:
        f.write("// Auto-generated HTML5 named entity table from WHATWG spec\n")
        f.write("// Source: https://html.spec.whatwg.org/entities.json\n")
        f.write(f"// Total entities: {len(sorted_names)}\n")
        f.write("// Generated by utils/generate_html5_entities.py\n")
        f.write("//\n")
        f.write("// DO NOT EDIT — regenerate with:\n")
        f.write("//   python3 utils/generate_html5_entities.py\n")
        f.write("\n")

        # -- Main entity table (sorted by name for binary search) --
        f.write("static const HtmlEntityEntry html_entity_table[] = {\n")
        for name in sorted_names:
            safe_name = name.replace('\\', '\\\\').replace('"', '\\"')
            f.write(f'    {{"{safe_name}", "{processed[name]}"}},\n')
        f.write("};\n\n")
        f.write(f"static const size_t HTML_ENTITY_COUNT = {len(sorted_names)};\n")

    print(f"Wrote {len(sorted_names)} entities to {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
