#!/usr/bin/env python3
"""Generate strong bidi classes from Unicode's DerivedBidiClass.txt."""

import argparse
import hashlib
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parent.parent
CLASS = {"L": 1, "Left_To_Right": 1, "R": 2, "Right_To_Left": 2,
         "AL": 2, "Arabic_Letter": 2}


def bounds(span):
    parts = span.split("..")
    return int(parts[0], 16), int(parts[-1], 16) + 1


def generate(source):
    version = re.search(r"DerivedBidiClass-([\d.]+)\.txt", source)
    if not version:
        raise ValueError("expected a Unicode DerivedBidiClass source")
    classes = bytearray([1]) * 0x110000
    # Specific @missing defaults override the general L default before explicit records.
    for span, kind in re.findall(r"# @missing:\s*([\dA-F.]+);\s*(\w+)", source):
        start, end = bounds(span)
        classes[start:end] = bytes([CLASS.get(kind, 0)]) * (end - start)
    for line in source.splitlines():
        record = line.split("#", 1)[0].strip()
        if not record:
            continue
        span, kind = (part.strip() for part in record.split(";"))
        start, end = bounds(span)
        classes[start:end] = bytes([CLASS.get(kind, 0)]) * (end - start)
    ranges = []
    start = 0
    for end in range(1, len(classes) + 1):
        if end < len(classes) and classes[start] == classes[end]:
            continue
        if classes[start] != 1:
            ranges.append((start, end - 1, 1 if classes[start] == 2 else 0))
        start = end
    header = [
        "// generated by utils/generate_unicode_bidi.py; do not edit.",
        f"// Unicode {version[1]} DerivedBidiClass.txt; SHA-256: {hashlib.sha256(source.encode()).hexdigest()}",
        f"// source: https://www.unicode.org/Public/{version[1]}/ucd/extracted/DerivedBidiClass.txt",
        "// Unicode data license: lib/UNICODE_LICENSE.txt (https://www.unicode.org/license.txt).",
        "// unlisted valid code points have bidi class L, including their specified @missing defaults.",
        "typedef struct { uint32_t first, last; int8_t strong; } UtfBidiStrongRange;",
        "static const UtfBidiStrongRange utf_bidi_non_ltr_ranges[] = {",
    ]
    header.extend(f"    {{0x{start:04X}, 0x{end:04X}, {kind}}}," for start, end, kind in ranges)
    header.extend(["};", ""])
    return "\n".join(header)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("--output", type=Path, default=ROOT / "lib/utf_bidi_data.h")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generate(args.source.read_text(encoding="utf-8"))
    if args.check:
        if not args.output.exists() or args.output.read_text() != text:
            raise SystemExit("Unicode bidi data differs; regenerate the header")
    else:
        args.output.write_text(text)
    print(f"UNICODE_BIDI: {'checked' if args.check else 'generated'} {args.output}")


if __name__ == "__main__":
    main()
