#!/usr/bin/env python3
"""Emit the unconditional full case mappings of Unicode SpecialCasing.txt as a
C table for lambda/core/utf_string.cpp (utf8_case_map).

Usage: python3 utils/generate_special_casing.py path/to/SpecialCasing.txt

Only unconditional entries are emitted. Conditional ones are either
locale-specific (tr, az, lt), which Lambda's locale-independent mapping leaves
out, or Final_Sigma, which utf8_case_map implements in code. A code point not
in the table maps by its simple UnicodeData mapping (utf8proc).
"""
import sys


def seq(field):
    return [int(cp, 16) for cp in field.split()]


def main(path):
    version = None
    rows = []
    for line in open(path, encoding='utf-8'):
        if version is None and line.startswith('# SpecialCasing-'):
            version = line[2:].strip()
        body = line.split('#', 1)[0].strip()
        if not body:
            continue
        fields = [f.strip() for f in body.split(';')]
        code, lower, _title, upper = fields[:4]
        condition = fields[4] if len(fields) > 4 else ''
        if condition:
            continue
        rows.append((int(code, 16), seq(lower), seq(upper)))
    rows.sort()
    print(f'// Generated by utils/generate_special_casing.py from {version}.')
    for cp, lower, upper in rows:
        def arr(values):
            return '{' + ', '.join(f'0x{v:04X}' for v in values) + '}'
        print(f'    {{0x{cp:04X}, {len(lower)}, {len(upper)}, {arr(lower)}, {arr(upper)}}},')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
