#!/usr/bin/env python3
"""Generate the shared emoji lookup from the versioned, offline catalog snapshot."""

import argparse
import json
from pathlib import Path
import re


def generate(root):
    catalog = json.loads((root / "lib/emoji_shortcodes_data.json").read_text())
    entries = {}
    for category in ("unicode", "images", "legacy"):
        for name, value in catalog[category].items():
            if not re.fullmatch(r"[a-z0-9_+\-]+", name) or name in entries:
                raise ValueError(f"invalid or duplicate emoji alias: {name}")
            if category == "images" and not value.startswith(
                "https://github.githubassets.com/images/icons/emoji/"
            ):
                raise ValueError(f"unexpected emoji image source: {value}")
            entries[name] = (None, value) if category == "images" else (value, None)

    def literal(value):
        return "nullptr" if value is None else json.dumps(value, ensure_ascii=False)

    lines = [
        "// generated by utils/generate_emoji_shortcodes.py; do not edit",
        f"// gemoji revision: {catalog['sources']['gemoji_revision']}",
        f"// GitHub emoji catalog snapshot: {catalog['sources']['github_snapshot_date']}",
        "// Unicode alias data license: EMOJI_LICENSE.txt",
        "static const EmojiShortcode emoji_table[] = {",
    ]
    for name, (utf8, image) in sorted(entries.items()):
        lines.append(f"    {{{literal(name)}, {literal(utf8)}, {literal(image)}}},")
    lines += ["};", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify generated data is current")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    output = root / "lib/emoji_shortcodes_table.inc"
    generated = generate(root)
    if args.check:
        if not output.exists() or output.read_text() != generated:
            parser.error("emoji lookup is stale; run utils/generate_emoji_shortcodes.py")
    else:
        output.write_text(generated)


if __name__ == "__main__":
    main()
