#!/usr/bin/env python3
"""Generate CSS :lang() canonicalization data from the IANA subtag registry."""

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
KINDS = {"language": 1, "script": 2, "region": 3, "variant": 4, "tag": 5}


def generate(source):
    date = source.splitlines()[0].removeprefix("File-Date: ")
    aliases, extlangs = [], []
    for block in source.split("%%")[1:]:
        fields = {}
        for line in block.splitlines():
            if line and not line.startswith(" ") and ": " in line:
                key, value = line.split(": ", 1)
                fields.setdefault(key, []).append(value.lower())
        kind = fields["Type"][0]
        name = fields.get("Subtag", fields.get("Tag"))[0]
        preferred = fields.get("Preferred-Value", [None])[0]
        if kind == "extlang":
            prefixes = fields["Prefix"]
            if len(prefixes) != 1 or "-" in prefixes[0] or preferred != name:
                raise ValueError(f"unsupported extlang record: {name}")
            extlangs.append((name, prefixes[0]))
        elif kind == "grandfathered" or preferred:
            if kind in KINDS and preferred and "-" in preferred:
                raise ValueError(f"multi-subtag preferred value: {name}")
            aliases.append((KINDS.get(kind, KINDS["tag"]), name, preferred))
    mappings = {(kind, name): preferred for kind, name, preferred in aliases if preferred}
    for kind, name in mappings:
        seen = set()
        while (kind, name) in mappings:
            if name in seen:
                raise ValueError(f"cyclic preferred values: {name}")
            seen.add(name)
            name = mappings[kind, name]
    lines = [
        "// generated by utils/generate_css_language_data.py; do not edit.",
        f"// IANA registry File-Date: {date}; SHA-256: {hashlib.sha256(source.encode()).hexdigest()}",
        "// source: https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry",
        "// only factual identifiers, preferred values and extlang prefixes are retained.",
        "struct CssLanguageAlias { unsigned char kind; const char* name; const char* preferred; };",
        "static const CssLanguageAlias css_language_aliases[] = {",
    ]
    for kind, name, preferred in sorted(aliases):
        value = f'"{preferred}"' if preferred else "nullptr"
        lines.append(f'    {{{kind}, "{name}", {value}}},')
    lines += ["};", "struct CssLanguageExtlang { const char* name; const char* prefix; };",
              "static const CssLanguageExtlang css_language_extlangs[] = {"]
    lines += [f'    {{"{name}", "{prefix}"}},' for name, prefix in sorted(extlangs)]
    return "\n".join(lines + ["};", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("--output", type=Path,
                        default=ROOT / "lambda/input/css/css_language_data.h")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate(args.source.read_text(encoding="utf-8"))
    if args.check:
        if not args.output.exists() or args.output.read_text() != generated:
            raise SystemExit("CSS language data differs; regenerate the header")
    else:
        args.output.write_text(generated)
    print(f"CSS_LANGUAGE_DATA: {'checked' if args.check else 'generated'} {args.output}")


if __name__ == "__main__":
    main()
