#include "utf_string.h"
#include "../lambda-data.hpp"
#include <utf8proc.h>
#include <string.h>
#include <stdlib.h>
#include "../../lib/log.h"
#include "../../lib/memtrack.h"

void init_utf8proc_support(void) {
    // utf8proc is initialized automatically, no setup needed
}

void cleanup_utf8proc_support(void) {
    // utf8proc doesn't require explicit cleanup
}

static char* normalize_utf8proc_with_options(const char* str, int len, int* out_len, utf8proc_option_t options) {
    if (!str || len <= 0) {
        if (out_len) *out_len = 0;
        return NULL;
    }

    utf8proc_uint8_t* result = NULL;
    utf8proc_ssize_t result_len = utf8proc_map(
        (const utf8proc_uint8_t*)str,
        len,
        &result,
        (utf8proc_option_t)(UTF8PROC_STABLE | options)
    );

    if (result_len < 0) {
        if (out_len) *out_len = 0;
        return NULL;
    }

    if (out_len) *out_len = (int)result_len;
    return (char*)result;
}

char* normalize_utf8proc_nfc(const char* str, int len, int* out_len) {
    return normalize_utf8proc_with_options(str, len, out_len, UTF8PROC_COMPOSE);
}

char* normalize_utf8proc_nfd(const char* str, int len, int* out_len) {
    return normalize_utf8proc_with_options(str, len, out_len, UTF8PROC_DECOMPOSE);
}

char* normalize_utf8proc_casefold(const char* str, int len, int* out_len) {
    return normalize_utf8proc_with_options(str, len, out_len, (utf8proc_option_t)(UTF8PROC_COMPOSE | UTF8PROC_CASEFOLD));
}

UnicodeCompareResult string_compare_unicode(const char* str1, int len1, const char* str2, int len2) {
    if (!str1 || !str2) {
        return UTF8PROC_COMPARE_ERROR;
    }

    // this opt-in helper normalizes and case-folds before comparison; it is not
    // Lambda's core bytewise order (S6.2.2) or a full UCA collation.
    int fold1_len, fold2_len;
    char* fold1 = normalize_utf8proc_casefold(str1, len1, &fold1_len);
    char* fold2 = normalize_utf8proc_casefold(str2, len2, &fold2_len);

    if (!fold1 || !fold2) {
        if (fold1) raw_free(fold1);  // RAWALLOC_OK: utf8proc internal allocation
        if (fold2) raw_free(fold2);  // RAWALLOC_OK: utf8proc internal allocation
        return UTF8PROC_COMPARE_ERROR;
    }
    log_debug("fold1: origin %s vs. %s", str1, fold1);
    log_debug("fold2: origin %s vs. %s", str2, fold2);

    // compare the normalized bytes after case folding
    int min_len = fold1_len < fold2_len ? fold1_len : fold2_len;
    int cmp = memcmp(fold1, fold2, min_len);

    UnicodeCompareResult result;
    if (cmp == 0) {
        if (fold1_len == fold2_len) {
            result = UTF8PROC_COMPARE_EQUAL;
        } else if (fold1_len < fold2_len) {
            result = UTF8PROC_COMPARE_LESS;
        } else {
            result = UTF8PROC_COMPARE_GREATER;
        }
    } else if (cmp < 0) {
        result = UTF8PROC_COMPARE_LESS;
    } else {
        result = UTF8PROC_COMPARE_GREATER;
    }

    raw_free(fold1);  raw_free(fold2);  // RAWALLOC_OK: utf8proc internal allocation
    return result;
}

bool string_equal_unicode(const char* str1, int len1, const char* str2, int len2) {
    return string_compare_unicode(str1, len1, str2, len2) == UTF8PROC_COMPARE_EQUAL;
}

char* normalize_utf8proc_nfkc(const char* str, int len, int* out_len) {
    return normalize_utf8proc_with_options(str, len, out_len, (utf8proc_option_t)(UTF8PROC_COMPOSE | UTF8PROC_COMPAT));
}

char* normalize_utf8proc_nfkd(const char* str, int len, int* out_len) {
    return normalize_utf8proc_with_options(str, len, out_len, (utf8proc_option_t)(UTF8PROC_DECOMPOSE | UTF8PROC_COMPAT));
}

void free_utf8proc_result(char* str) {
    // utf8proc_map allocates outside Lambda memtrack, so normalized buffers must bypass mem_free().
    raw_free(str);  // RAWALLOC_OK: paired with utf8proc_map allocation
}

// --- case mapping (S17.7.2) --------------------------------------------------
//
// Unicode default case conversion, locale-independent, as ECMAScript's
// toLowerCase/toUpperCase define it: a code point with a full mapping in
// SpecialCasing.txt maps by it, any other by its simple UnicodeData mapping
// (utf8proc), and a capital sigma at the end of a word lowercases to final ς.
// Lambda's lower/upper and LambdaJS's toLowerCase/toUpperCase share it.

typedef struct Utf8SpecialCase {
    uint32_t cp;
    uint8_t lower_len;
    uint8_t upper_len;
    uint32_t lower[3];
    uint32_t upper[3];
} Utf8SpecialCase;

// Unconditional full mappings, sorted by code point. The conditional ones are
// locale-specific (tr, az, lt), which a locale-independent mapping leaves out,
// or Final_Sigma, which utf8_case_map applies in code.
static const Utf8SpecialCase UTF8_SPECIAL_CASES[] = {
// Generated by utils/generate_special_casing.py from SpecialCasing-16.0.0.txt.
    {0x00DF, 1, 2, {0x00DF}, {0x0053, 0x0053}},
    {0x0130, 2, 1, {0x0069, 0x0307}, {0x0130}},
    {0x0149, 1, 2, {0x0149}, {0x02BC, 0x004E}},
    {0x01F0, 1, 2, {0x01F0}, {0x004A, 0x030C}},
    {0x0390, 1, 3, {0x0390}, {0x0399, 0x0308, 0x0301}},
    {0x03B0, 1, 3, {0x03B0}, {0x03A5, 0x0308, 0x0301}},
    {0x0587, 1, 2, {0x0587}, {0x0535, 0x0552}},
    {0x1E96, 1, 2, {0x1E96}, {0x0048, 0x0331}},
    {0x1E97, 1, 2, {0x1E97}, {0x0054, 0x0308}},
    {0x1E98, 1, 2, {0x1E98}, {0x0057, 0x030A}},
    {0x1E99, 1, 2, {0x1E99}, {0x0059, 0x030A}},
    {0x1E9A, 1, 2, {0x1E9A}, {0x0041, 0x02BE}},
    {0x1F50, 1, 2, {0x1F50}, {0x03A5, 0x0313}},
    {0x1F52, 1, 3, {0x1F52}, {0x03A5, 0x0313, 0x0300}},
    {0x1F54, 1, 3, {0x1F54}, {0x03A5, 0x0313, 0x0301}},
    {0x1F56, 1, 3, {0x1F56}, {0x03A5, 0x0313, 0x0342}},
    {0x1F80, 1, 2, {0x1F80}, {0x1F08, 0x0399}},
    {0x1F81, 1, 2, {0x1F81}, {0x1F09, 0x0399}},
    {0x1F82, 1, 2, {0x1F82}, {0x1F0A, 0x0399}},
    {0x1F83, 1, 2, {0x1F83}, {0x1F0B, 0x0399}},
    {0x1F84, 1, 2, {0x1F84}, {0x1F0C, 0x0399}},
    {0x1F85, 1, 2, {0x1F85}, {0x1F0D, 0x0399}},
    {0x1F86, 1, 2, {0x1F86}, {0x1F0E, 0x0399}},
    {0x1F87, 1, 2, {0x1F87}, {0x1F0F, 0x0399}},
    {0x1F88, 1, 2, {0x1F80}, {0x1F08, 0x0399}},
    {0x1F89, 1, 2, {0x1F81}, {0x1F09, 0x0399}},
    {0x1F8A, 1, 2, {0x1F82}, {0x1F0A, 0x0399}},
    {0x1F8B, 1, 2, {0x1F83}, {0x1F0B, 0x0399}},
    {0x1F8C, 1, 2, {0x1F84}, {0x1F0C, 0x0399}},
    {0x1F8D, 1, 2, {0x1F85}, {0x1F0D, 0x0399}},
    {0x1F8E, 1, 2, {0x1F86}, {0x1F0E, 0x0399}},
    {0x1F8F, 1, 2, {0x1F87}, {0x1F0F, 0x0399}},
    {0x1F90, 1, 2, {0x1F90}, {0x1F28, 0x0399}},
    {0x1F91, 1, 2, {0x1F91}, {0x1F29, 0x0399}},
    {0x1F92, 1, 2, {0x1F92}, {0x1F2A, 0x0399}},
    {0x1F93, 1, 2, {0x1F93}, {0x1F2B, 0x0399}},
    {0x1F94, 1, 2, {0x1F94}, {0x1F2C, 0x0399}},
    {0x1F95, 1, 2, {0x1F95}, {0x1F2D, 0x0399}},
    {0x1F96, 1, 2, {0x1F96}, {0x1F2E, 0x0399}},
    {0x1F97, 1, 2, {0x1F97}, {0x1F2F, 0x0399}},
    {0x1F98, 1, 2, {0x1F90}, {0x1F28, 0x0399}},
    {0x1F99, 1, 2, {0x1F91}, {0x1F29, 0x0399}},
    {0x1F9A, 1, 2, {0x1F92}, {0x1F2A, 0x0399}},
    {0x1F9B, 1, 2, {0x1F93}, {0x1F2B, 0x0399}},
    {0x1F9C, 1, 2, {0x1F94}, {0x1F2C, 0x0399}},
    {0x1F9D, 1, 2, {0x1F95}, {0x1F2D, 0x0399}},
    {0x1F9E, 1, 2, {0x1F96}, {0x1F2E, 0x0399}},
    {0x1F9F, 1, 2, {0x1F97}, {0x1F2F, 0x0399}},
    {0x1FA0, 1, 2, {0x1FA0}, {0x1F68, 0x0399}},
    {0x1FA1, 1, 2, {0x1FA1}, {0x1F69, 0x0399}},
    {0x1FA2, 1, 2, {0x1FA2}, {0x1F6A, 0x0399}},
    {0x1FA3, 1, 2, {0x1FA3}, {0x1F6B, 0x0399}},
    {0x1FA4, 1, 2, {0x1FA4}, {0x1F6C, 0x0399}},
    {0x1FA5, 1, 2, {0x1FA5}, {0x1F6D, 0x0399}},
    {0x1FA6, 1, 2, {0x1FA6}, {0x1F6E, 0x0399}},
    {0x1FA7, 1, 2, {0x1FA7}, {0x1F6F, 0x0399}},
    {0x1FA8, 1, 2, {0x1FA0}, {0x1F68, 0x0399}},
    {0x1FA9, 1, 2, {0x1FA1}, {0x1F69, 0x0399}},
    {0x1FAA, 1, 2, {0x1FA2}, {0x1F6A, 0x0399}},
    {0x1FAB, 1, 2, {0x1FA3}, {0x1F6B, 0x0399}},
    {0x1FAC, 1, 2, {0x1FA4}, {0x1F6C, 0x0399}},
    {0x1FAD, 1, 2, {0x1FA5}, {0x1F6D, 0x0399}},
    {0x1FAE, 1, 2, {0x1FA6}, {0x1F6E, 0x0399}},
    {0x1FAF, 1, 2, {0x1FA7}, {0x1F6F, 0x0399}},
    {0x1FB2, 1, 2, {0x1FB2}, {0x1FBA, 0x0399}},
    {0x1FB3, 1, 2, {0x1FB3}, {0x0391, 0x0399}},
    {0x1FB4, 1, 2, {0x1FB4}, {0x0386, 0x0399}},
    {0x1FB6, 1, 2, {0x1FB6}, {0x0391, 0x0342}},
    {0x1FB7, 1, 3, {0x1FB7}, {0x0391, 0x0342, 0x0399}},
    {0x1FBC, 1, 2, {0x1FB3}, {0x0391, 0x0399}},
    {0x1FC2, 1, 2, {0x1FC2}, {0x1FCA, 0x0399}},
    {0x1FC3, 1, 2, {0x1FC3}, {0x0397, 0x0399}},
    {0x1FC4, 1, 2, {0x1FC4}, {0x0389, 0x0399}},
    {0x1FC6, 1, 2, {0x1FC6}, {0x0397, 0x0342}},
    {0x1FC7, 1, 3, {0x1FC7}, {0x0397, 0x0342, 0x0399}},
    {0x1FCC, 1, 2, {0x1FC3}, {0x0397, 0x0399}},
    {0x1FD2, 1, 3, {0x1FD2}, {0x0399, 0x0308, 0x0300}},
    {0x1FD3, 1, 3, {0x1FD3}, {0x0399, 0x0308, 0x0301}},
    {0x1FD6, 1, 2, {0x1FD6}, {0x0399, 0x0342}},
    {0x1FD7, 1, 3, {0x1FD7}, {0x0399, 0x0308, 0x0342}},
    {0x1FE2, 1, 3, {0x1FE2}, {0x03A5, 0x0308, 0x0300}},
    {0x1FE3, 1, 3, {0x1FE3}, {0x03A5, 0x0308, 0x0301}},
    {0x1FE4, 1, 2, {0x1FE4}, {0x03A1, 0x0313}},
    {0x1FE6, 1, 2, {0x1FE6}, {0x03A5, 0x0342}},
    {0x1FE7, 1, 3, {0x1FE7}, {0x03A5, 0x0308, 0x0342}},
    {0x1FF2, 1, 2, {0x1FF2}, {0x1FFA, 0x0399}},
    {0x1FF3, 1, 2, {0x1FF3}, {0x03A9, 0x0399}},
    {0x1FF4, 1, 2, {0x1FF4}, {0x038F, 0x0399}},
    {0x1FF6, 1, 2, {0x1FF6}, {0x03A9, 0x0342}},
    {0x1FF7, 1, 3, {0x1FF7}, {0x03A9, 0x0342, 0x0399}},
    {0x1FFC, 1, 2, {0x1FF3}, {0x03A9, 0x0399}},
    {0xFB00, 1, 2, {0xFB00}, {0x0046, 0x0046}},
    {0xFB01, 1, 2, {0xFB01}, {0x0046, 0x0049}},
    {0xFB02, 1, 2, {0xFB02}, {0x0046, 0x004C}},
    {0xFB03, 1, 3, {0xFB03}, {0x0046, 0x0046, 0x0049}},
    {0xFB04, 1, 3, {0xFB04}, {0x0046, 0x0046, 0x004C}},
    {0xFB05, 1, 2, {0xFB05}, {0x0053, 0x0054}},
    {0xFB06, 1, 2, {0xFB06}, {0x0053, 0x0054}},
    {0xFB13, 1, 2, {0xFB13}, {0x0544, 0x0546}},
    {0xFB14, 1, 2, {0xFB14}, {0x0544, 0x0535}},
    {0xFB15, 1, 2, {0xFB15}, {0x0544, 0x053B}},
    {0xFB16, 1, 2, {0xFB16}, {0x054E, 0x0546}},
    {0xFB17, 1, 2, {0xFB17}, {0x0544, 0x053D}},
};

static const Utf8SpecialCase* utf8_special_case(uint32_t cp) {
    size_t lo = 0, hi = sizeof(UTF8_SPECIAL_CASES) / sizeof(UTF8_SPECIAL_CASES[0]);
    if (cp < UTF8_SPECIAL_CASES[0].cp) return NULL;
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        if (UTF8_SPECIAL_CASES[mid].cp < cp) lo = mid + 1;
        else hi = mid;
    }
    size_t count = sizeof(UTF8_SPECIAL_CASES) / sizeof(UTF8_SPECIAL_CASES[0]);
    return lo < count && UTF8_SPECIAL_CASES[lo].cp == cp ? &UTF8_SPECIAL_CASES[lo] : NULL;
}

// Unicode Cased: an upper-, lower- or titlecase letter, or anything else with
// a case mapping (Other_Lowercase, Other_Uppercase)
static bool utf8_cp_is_cased(utf8proc_int32_t cp) {
    utf8proc_category_t category = utf8proc_category(cp);
    if (category == UTF8PROC_CATEGORY_LU || category == UTF8PROC_CATEGORY_LL ||
            category == UTF8PROC_CATEGORY_LT) {
        return true;
    }
    return utf8proc_tolower(cp) != utf8proc_toupper(cp);
}

// Unicode Case_Ignorable: marks, format controls, modifier letters and
// symbols, and the Word_Break MidLetter, MidNumLet and Single_Quote characters
static bool utf8_cp_is_case_ignorable(utf8proc_int32_t cp) {
    utf8proc_category_t category = utf8proc_category(cp);
    if (category == UTF8PROC_CATEGORY_MN || category == UTF8PROC_CATEGORY_ME ||
            category == UTF8PROC_CATEGORY_CF || category == UTF8PROC_CATEGORY_LM ||
            category == UTF8PROC_CATEGORY_SK) {
        return true;
    }
    switch (cp) {
        case 0x0027: case 0x002e: case 0x003a: case 0x00b7:
        case 0x0387: case 0x05f4: case 0x2019: case 0x2027:
        case 0xfe13: case 0xfe55: case 0xff07: case 0xff0e:
        case 0xff1a:
            return true;
    }
    return false;
}

// Final_Sigma's right context: whether a cased letter follows, skipping
// case-ignorable ones
static bool utf8_cased_follows(const char* chars, size_t len, size_t pos) {
    while (pos < len) {
        utf8proc_int32_t cp = 0;
        utf8proc_ssize_t width = utf8proc_iterate((const utf8proc_uint8_t*)chars + pos,
            (utf8proc_ssize_t)(len - pos), &cp);
        if (width <= 0) return false;
        if (!utf8_cp_is_case_ignorable(cp)) return utf8_cp_is_cased(cp);
        pos += (size_t)width;
    }
    return false;
}

bool utf8_case_map(const char* chars, size_t len, bool to_upper, StrBuf* out) {
    bool changed = false;
    bool after_cased = false;  // Final_Sigma's left context
    size_t pos = 0;
    while (pos < len) {
        utf8proc_int32_t cp = 0;
        utf8proc_ssize_t width = utf8proc_iterate((const utf8proc_uint8_t*)chars + pos,
            (utf8proc_ssize_t)(len - pos), &cp);
        if (width <= 0) {
            // not a scalar value (invalid UTF-8, or a lone surrogate): keep the byte
            strbuf_append_char(out, chars[pos]);
            pos++;
            continue;
        }
        const Utf8SpecialCase* special = utf8_special_case((uint32_t)cp);
        if (special) {
            const uint32_t* mapped = to_upper ? special->upper : special->lower;
            uint8_t count = to_upper ? special->upper_len : special->lower_len;
            for (uint8_t i = 0; i < count; i++) strbuf_append_utf8(out, mapped[i]);
            if (count != 1 || mapped[0] != (uint32_t)cp) changed = true;
        } else {
            utf8proc_int32_t mapped = to_upper ? utf8proc_toupper(cp) : utf8proc_tolower(cp);
            if (!to_upper && cp == 0x03a3 && after_cased &&
                    !utf8_cased_follows(chars, len, pos + (size_t)width)) {
                mapped = 0x03c2;
            }
            if (mapped != cp) {
                strbuf_append_utf8(out, (uint32_t)mapped);
                changed = true;
            } else {
                strbuf_append_str_n(out, chars + pos, (size_t)width);
            }
        }
        if (!utf8_cp_is_case_ignorable(cp)) after_cased = utf8_cp_is_cased(cp);
        pos += (size_t)width;
    }
    return changed;
}
