// Generated by utils/generate_well_known_names.py; do not edit.
#include "js_well_known_names.h"

const WellKnownNameRecord g_well_known_js_names[] = {
    { { 0xF25D9F4Fu, UINT32_MAX, 0, NAME_KEY_STRING, 0, 0x00020001u }, 11u, 0x05u, "constructor" },
    { { 0xB8440699u, UINT32_MAX, 0, NAME_KEY_STRING, 0, 0x00020002u }, 9u, 0x05u, "prototype" },
    { { 0x8D39BDE6u, UINT32_MAX, 0, NAME_KEY_STRING, 0, 0x00020003u }, 4u, 0x05u, "name" },
    { { 0x16C039C5u, UINT32_MAX, 0, NAME_KEY_STRING, 0, 0x00020004u }, 8u, 0x05u, "toString" },
    { { 0xA8BBE7BBu, UINT32_MAX, 0, NAME_KEY_STRING, 0, 0x00020005u }, 7u, 0x05u, "valueOf" },
    { { 0x35A9C377u, UINT32_MAX, 0, NAME_KEY_SYMBOL, 0, 0x00020006u }, 15u, 0x05u, "Symbol.iterator" },
    { { 0xA285F3C5u, UINT32_MAX, 0, NAME_KEY_SYMBOL, 0, 0x00020007u }, 18u, 0x05u, "Symbol.toPrimitive" },
    { { 0x8B6EEEB8u, UINT32_MAX, 0, NAME_KEY_SYMBOL, 0, 0x00020008u }, 18u, 0x05u, "Symbol.hasInstance" },
    { { 0x0BA6B63Bu, UINT32_MAX, 0, NAME_KEY_SYMBOL, 0, 0x00020009u }, 18u, 0x05u, "Symbol.toStringTag" },
    { { 0x6868708Du, UINT32_MAX, 0, NAME_KEY_SYMBOL, 0, 0x0002000Au }, 20u, 0x05u, "Symbol.asyncIterator" },
    { { 0x2452D681u, UINT32_MAX, 0, NAME_KEY_SYMBOL, 0, 0x0002000Bu }, 14u, 0x05u, "Symbol.species" },
    { { 0x44DE0CEEu, UINT32_MAX, 0, NAME_KEY_SYMBOL, 0, 0x0002000Cu }, 12u, 0x05u, "Symbol.match" },
    { { 0x63CD700Bu, UINT32_MAX, 0, NAME_KEY_SYMBOL, 0, 0x0002000Du }, 14u, 0x05u, "Symbol.replace" },
    { { 0x89F8F5A1u, UINT32_MAX, 0, NAME_KEY_SYMBOL, 0, 0x0002000Eu }, 13u, 0x05u, "Symbol.search" },
    { { 0x15E6653Bu, UINT32_MAX, 0, NAME_KEY_SYMBOL, 0, 0x0002000Fu }, 12u, 0x05u, "Symbol.split" },
    { { 0xE3498670u, UINT32_MAX, 0, NAME_KEY_SYMBOL, 0, 0x00020010u }, 18u, 0x05u, "Symbol.unscopables" },
    { { 0xBCE1D1E2u, UINT32_MAX, 0, NAME_KEY_SYMBOL, 0, 0x00020011u }, 25u, 0x05u, "Symbol.isConcatSpreadable" },
    { { 0x1A1A507Du, UINT32_MAX, 0, NAME_KEY_SYMBOL, 0, 0x00020012u }, 15u, 0x05u, "Symbol.matchAll" },
    { { 0x1817E5D8u, UINT32_MAX, 0, NAME_KEY_SYMBOL, 0, 0x00020013u }, 19u, 0x05u, "Symbol.asyncDispose" },
    { { 0x8BFB67BEu, UINT32_MAX, 0, NAME_KEY_SYMBOL, 0, 0x00020014u }, 14u, 0x05u, "Symbol.dispose" },
};
const size_t g_well_known_js_name_count = sizeof(g_well_known_js_names) / sizeof(g_well_known_js_names[0]);
