#!/usr/bin/env python3
"""Regenerates BOTH committed T0 lists from one sweep, so they cannot drift.

`test/lambda/interp_p0_subset.txt` and `test/lambda/interp_excluded.txt` are a
partition of the corpus: every script is in exactly one. Refreshing them
separately is how they go out of sync — the subset gains a script that is still
listed as excluded, and `InterpFallback.ExcludedScriptsAreCountedNotInterpreted`
fails. Always run this after `tier_sweep.py`, never one half by hand.

Usage: python3 test/interp/refresh_lists.py [--sweep temp/sweep_full.tsv]
"""
import argparse
import collections
import os
import re
import subprocess
import sys

PROC_DIRS = ("test/lambda/proc", "test/lambda/conc", "test/lambda/pdf")
FALLBACK_RE = re.compile(r"interp: fallback file=\S+ reason=node:(\S+)")

SUBSET_HEADER = """# T0 interpreter — interpreted-script list (LAMBDA_TIER=interp)
#
# Generated by `python3 test/interp/tier_sweep.py` over the FULL baseline corpus
# followed by `python3 test/interp/refresh_lists.py`, then reviewed and
# committed. Every script here runs entirely under the AST interpreter
# (fallback=0) and produces output byte-identical to the JIT tier, which is the
# shared golden oracle (SI3 / D3.3.1's third leg).
#
# format: <script>\t<direct|run>
# `run` scripts are procedural and must be invoked as `lambda.exe run <script>`
# — invoking them directly executes no `main` and silently compares empty
# output, which is exactly how a real run-mode defect stayed hidden.
"""

EXCLUDED_HEADER = """# T0 interpreter — exclusion list (LAMBDA_TIER=interp)
#
# Scripts whose pre-scan finds a construct the walker does not execute. Each
# runs on the whole-module JIT path instead, counted in the run summary
# (`interp: … fallback=N`) — there are no silent caps (design risk R4).
#
# This file, interp_p0_subset.txt, and interp_inconclusive.txt partition the
# classified corpus; regenerate all three with this script.
#
# `node:none` means the pre-scan never ran: the script does not compile on
# either tier, or its whole import cone was rejected before it was reached.
#
# `node:AST_NODE_PROC` is usually the task-backed boundary rather than the `pn`
# spelling: a procedure the concurrency analysis marks await-capable runs its
# body through the boxed MIR satellite, and that membrane fails closed on local
# `var`/assignment statements and on indirect Lambda calls (D8.1.1v4, D3.3.1).
# A `pn main` that starts or waits on a task and also keeps mutable locals is
# therefore expected here, not a walker defect.
#
# format: <script>\tnode:<first unsupported kind>
"""

INCONCLUSIVE_HEADER = """# T0 interpreter — inconclusive differential rows
#
# Scripts for which the bounded differential sweep could not establish a
# verdict. They are neither interpreted-subset matches nor counted
# interpreter fallbacks.
#
# format: <script>\t<reason>
"""


def mode_of(script):
    return "run" if os.path.dirname(script) in PROC_DIRS else "direct"


def reject_reason(script, timeout):
    argv = ["./lambda.exe", "run", script] if mode_of(script) == "run" \
        else ["./lambda.exe", script]
    env = dict(os.environ)
    env["LAMBDA_TIER"] = "interp"
    try:
        subprocess.run(argv, env=env, capture_output=True, timeout=timeout)
    except Exception:
        pass
    try:
        with open("log.txt", errors="replace") as f:
            hits = FALLBACK_RE.findall(f.read())
    except OSError:
        hits = []
    return hits[-1] if hits else "none"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sweep", default="temp/sweep_full.tsv")
    ap.add_argument("--timeout", type=int, default=25)
    args = ap.parse_args()

    if not os.path.exists(args.sweep):
        print(f"missing {args.sweep}; run test/interp/tier_sweep.py first")
        return 1

    rows = [l.rstrip("\n").split("\t") for l in open(args.sweep)
            if not l.startswith("#") and l.strip()]
    # Preserve a reviewed golden-drift ruling across a later tier sweep. The
    # sweep compares T0 with JIT, while the committed subset gate also compares
    # both against the checked-in golden; a stale golden must not be promoted
    # back into the subset until that oracle is repaired.
    golden_drift = {}
    try:
        with open("test/lambda/interp_inconclusive.txt") as f:
            for line in f:
                if line.startswith("test/"):
                    fields = line.rstrip("\n").split("\t")
                    if len(fields) > 1 and fields[1] == "golden_drift":
                        golden_drift[fields[0]] = fields[1]
    except OSError:
        pass
    match = [r[0] for r in rows
             if r[1] == "match" and r[0] not in golden_drift]
    fallback = [r[0] for r in rows
                if r[1] == "fallback" and r[0] not in golden_drift]
    mismatch = [r[0] for r in rows if r[1] == "mismatch"]
    inconclusive = [(r[0], r[1]) for r in rows
                    if r[1] not in ("match", "fallback", "mismatch")
                    and r[0] not in golden_drift]
    inconclusive.extend(golden_drift.items())

    if mismatch:
        # A divergence is a T0 bug by definition (SI3). Refusing to commit lists
        # built from a diverging sweep keeps a broken state from looking gated.
        print(f"refusing to refresh: {len(mismatch)} script(s) diverge")
        for s in mismatch:
            print("  " + s)
        return 1

    with open("test/lambda/interp_p0_subset.txt", "w") as f:
        f.write(SUBSET_HEADER)
        for s in match:
            f.write(f"{s}\t{mode_of(s)}\n")

    reasons = []
    for s in fallback:
        reasons.append((s, reject_reason(s, args.timeout)))
    with open("test/lambda/interp_excluded.txt", "w") as f:
        f.write(EXCLUDED_HEADER)
        for s, r in reasons:
            f.write(f"{s}\tnode:{r}\n")

    with open("test/lambda/interp_inconclusive.txt", "w") as f:
        f.write(INCONCLUSIVE_HEADER)
        for s, verdict in inconclusive:
            f.write(f"{s}\t{verdict}\n")

    print(f"subset={len(match)} excluded={len(fallback)} "
          f"inconclusive={len(inconclusive)} "
          f"procedural={sum(1 for s in match if mode_of(s) == 'run')}")
    for kind, count in collections.Counter(r for _, r in reasons).most_common(10):
        print(f"  {count:4d}  {kind}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
