// Generated by utils/generate_well_known_names.py; do not edit.
#pragma once

// Pure interface metadata; usable across the Jube module boundary.

#define CSS_STYLE_PROPERTIES_FIELDS(X) \
    X(display) \
    X(width) \
    X(height) \
    X(color) \
    X(background) \
    X(font) \
    X(position) \
    X(top) \
    X(right) \
    X(bottom) \
    X(left) \
    X(z_index) \
    X(float) \
    X(clear) \
    X(overflow) \
    X(overflow_x) \
    X(overflow_y) \
    X(visibility) \
    X(clip) \
    X(clip_path) \
    X(direction) \
    X(unicode_bidi) \
    X(writing_mode) \
    X(min_width) \
    X(min_height) \
    X(max_width) \
    X(max_height) \
    X(margin_top) \
    X(margin_right) \
    X(margin_bottom) \
    X(margin_left) \
    X(margin_block) \
    X(margin_block_start) \
    X(margin_block_end) \
    X(margin_inline) \
    X(margin_inline_start) \
    X(margin_inline_end) \
    X(margin_trim) \
    X(padding_top) \
    X(padding_right) \
    X(padding_bottom) \
    X(padding_left) \
    X(padding_block) \
    X(padding_block_start) \
    X(padding_block_end) \
    X(padding_inline) \
    X(padding_inline_start) \
    X(padding_inline_end) \
    X(border_top_width) \
    X(border_right_width) \
    X(border_bottom_width) \
    X(border_left_width) \
    X(border_top_style) \
    X(border_right_style) \
    X(border_bottom_style) \
    X(border_left_style) \
    X(border_top_color) \
    X(border_right_color) \
    X(border_bottom_color) \
    X(border_left_color) \
    X(border_width) \
    X(border_style) \
    X(border_color) \
    X(border_top) \
    X(border_right) \
    X(border_bottom) \
    X(border_left) \
    X(border_inline) \
    X(border_inline_width) \
    X(border_inline_style) \
    X(border_inline_color) \
    X(border_inline_start) \
    X(border_inline_start_width) \
    X(border_inline_start_style) \
    X(border_inline_start_color) \
    X(border_inline_end) \
    X(border_inline_end_width) \
    X(border_inline_end_style) \
    X(border_inline_end_color) \
    X(border_block) \
    X(border_block_style) \
    X(border_block_start) \
    X(border_block_start_style) \
    X(border_block_end) \
    X(border_block_end_style) \
    X(border_block_width) \
    X(border_block_color) \
    X(border_block_start_width) \
    X(border_block_start_color) \
    X(border_block_end_color) \
    X(border_block_end_width) \
    X(border_start_start_radius) \
    X(border_start_end_radius) \
    X(border_end_start_radius) \
    X(border_end_end_radius) \
    X(box_sizing) \
    X(box_decoration_break) \
    X(aspect_ratio) \
    X(fill) \
    X(stroke) \
    X(stroke_width) \
    X(font_family) \
    X(font_size) \
    X(font_weight) \
    X(font_style) \
    X(font_variant) \
    X(font_size_adjust) \
    X(font_kerning) \
    X(font_variant_ligatures) \
    X(font_variant_caps) \
    X(font_variant_numeric) \
    X(font_variant_alternates) \
    X(font_variant_east_asian) \
    X(font_feature_settings) \
    X(font_language_override) \
    X(font_optical_sizing) \
    X(font_variation_settings) \
    X(font_display) \
    X(letter_spacing) \
    X(word_spacing) \
    X(text_shadow) \
    X(line_height) \
    X(text_align) \
    X(text_decoration) \
    X(text_transform) \
    X(initial_letter) \
    X(text_wrap_style) \
    X(text_spacing_trim) \
    X(text_autospace) \
    X(white_space) \
    X(vertical_align) \
    X(background_color) \
    X(background_image) \
    X(background_repeat) \
    X(background_position) \
    X(background_size) \
    X(flex_direction) \
    X(flex_wrap) \
    X(flex_flow) \
    X(justify_content) \
    X(align_items) \
    X(align_content) \
    X(place_content) \
    X(align_self) \
    X(flex_grow) \
    X(flex_shrink) \
    X(flex_basis) \
    X(order) \
    X(grid_template_columns) \
    X(grid_template_rows) \
    X(grid_column_start) \
    X(grid_column_end) \
    X(grid_row_start) \
    X(grid_row_end) \
    X(grid_column_gap) \
    X(grid_row_gap) \
    X(justify_items) \
    X(justify_self) \
    X(place_items) \
    X(place_self) \
    X(grid_template) \
    X(grid_template_areas) \
    X(grid_auto_rows) \
    X(grid_auto_columns) \
    X(grid_auto_flow) \
    X(grid_row) \
    X(grid_column) \
    X(grid_area) \
    X(grid_gap) \
    X(opacity) \
    X(cursor) \
    X(border_radius) \
    X(border_top_left_radius) \
    X(border_top_right_radius) \
    X(border_bottom_right_radius) \
    X(border_bottom_left_radius) \
    X(background_attachment) \
    X(background_origin) \
    X(background_clip) \
    X(background_position_x) \
    X(background_position_y) \
    X(background_blend_mode) \
    X(filter) \
    X(backdrop_filter) \
    X(transform) \
    X(transform_origin) \
    X(transform_style) \
    X(backface_visibility) \
    X(perspective) \
    X(perspective_origin) \
    X(animation) \
    X(animation_name) \
    X(animation_duration) \
    X(animation_timing_function) \
    X(animation_delay) \
    X(animation_iteration_count) \
    X(animation_direction) \
    X(animation_fill_mode) \
    X(animation_play_state) \
    X(transition) \
    X(margin) \
    X(padding) \
    X(border) \
    X(flex) \
    X(grid) \
    X(column_width) \
    X(column_count) \
    X(columns) \
    X(column_rule) \
    X(column_rule_width) \
    X(column_rule_style) \
    X(column_rule_color) \
    X(column_span) \
    X(column_fill) \
    X(column_height) \
    X(column_wrap) \
    X(gap) \
    X(row_gap) \
    X(column_gap) \
    X(block_size) \
    X(inline_size) \
    X(min_block_size) \
    X(min_inline_size) \
    X(max_block_size) \
    X(max_inline_size) \
    X(inset) \
    X(inset_block) \
    X(inset_block_start) \
    X(inset_block_end) \
    X(inset_inline) \
    X(inset_inline_start) \
    X(inset_inline_end) \
    X(text_decoration_line) \
    X(text_decoration_style) \
    X(text_decoration_color) \
    X(text_decoration_thickness) \
    X(text_emphasis) \
    X(text_emphasis_style) \
    X(text_emphasis_color) \
    X(text_emphasis_position) \
    X(text_overflow) \
    X(word_break) \
    X(line_break) \
    X(hyphens) \
    X(hyphenate_character) \
    X(overflow_wrap) \
    X(word_wrap) \
    X(tab_size) \
    X(hanging_punctuation) \
    X(text_justify) \
    X(text_align_all) \
    X(text_align_last) \
    X(list_style) \
    X(list_style_type) \
    X(list_style_position) \
    X(list_style_image) \
    X(counter_reset) \
    X(counter_increment) \
    X(counter_set) \
    X(content) \
    X(quotes) \
    X(font_stretch) \
    X(text_orientation) \
    X(text_combine_upright) \
    X(text_indent) \
    X(border_collapse) \
    X(border_spacing) \
    X(caption_side) \
    X(empty_cells) \
    X(table_layout) \
    X(resize) \
    X(accent_color) \
    X(caret_color) \
    X(caret_shape) \
    X(nav_index) \
    X(nav_up) \
    X(nav_right) \
    X(nav_down) \
    X(nav_left) \
    X(appearance) \
    X(field_sizing) \
    X(user_select) \
    X(box_shadow) \
    X(border_image) \
    X(border_image_source) \
    X(border_image_slice) \
    X(border_image_width) \
    X(border_image_outset) \
    X(border_image_repeat) \
    X(outline) \
    X(outline_style) \
    X(outline_width) \
    X(outline_color) \
    X(outline_offset) \
    X(break_before) \
    X(break_after) \
    X(break_inside) \
    X(page_break_before) \
    X(page_break_after) \
    X(page_break_inside) \
    X(orphans) \
    X(widows) \
    X(container) \
    X(container_type) \
    X(container_name) \
    X(contain) \
    X(contain_intrinsic_width) \
    X(contain_intrinsic_height) \
    X(contain_intrinsic_size) \
    X(alignment_baseline) \
    X(baseline_shift) \
    X(baseline_source) \
    X(dominant_baseline) \
    X(text_box) \
    X(text_box_trim) \
    X(text_box_edge) \
    X(isolation) \
    X(mix_blend_mode) \
    X(object_fit) \
    X(object_position) \
    X(object_view_box) \
    X(pointer_events) \
    X(float_defer) \
    X(float_offset) \
    X(float_reference) \
    X(image_orientation) \
    X(image_rendering) \
    X(marker_offset) \
    X(mask_image) \
    X(mask_type) \
    X(nesting) \
    X(overflow_block) \
    X(overflow_clip_margin) \
    X(overflow_inline) \
    X(overscroll_behavior) \
    X(ruby_align) \
    X(ruby_position) \
    X(scroll_behavior) \
    X(scroll_margin) \
    X(scroll_padding) \
    X(scroll_snap_align) \
    X(scroll_snap_type) \
    X(transition_delay) \
    X(transition_duration) \
    X(transition_property) \
    X(transition_timing_function) \
    X(wrap_flow) \
    X(wrap_through) \
    X(line_clamp) \
    X(_webkit_line_clamp) \
    X(contain_intrinsic_inline_size) \
    X(contain_intrinsic_block_size) \
    X(scrollbar_gutter) \
    X(content_visibility) \
    X(all) \
    X(zoom) \
    X(text_wrap) \
    X(text_wrap_mode) \
    X(text_underline_offset) \
    X(text_decoration_skip_ink) \
    X(text_underline_position) \
    X(overscroll_behavior_x) \
    X(overscroll_behavior_y) \
    X(scroll_margin_top) \
    X(scroll_margin_right) \
    X(scroll_margin_bottom) \
    X(scroll_margin_left) \
    X(scroll_margin_block) \
    X(scroll_margin_block_start) \
    X(scroll_margin_block_end) \
    X(scroll_margin_inline) \
    X(scroll_margin_inline_start) \
    X(scroll_margin_inline_end) \
    X(scroll_padding_top) \
    X(scroll_padding_right) \
    X(scroll_padding_bottom) \
    X(scroll_padding_left) \
    X(scroll_padding_block) \
    X(scroll_padding_block_start) \
    X(scroll_padding_block_end) \
    X(scroll_padding_inline) \
    X(scroll_padding_inline_start) \
    X(scroll_padding_inline_end) \
    X(translate) \
    X(rotate) \
    X(scale) \
    X(css_float)

#define CSS_STYLE_PROPERTIES_ATTRIBUTES(X) \
    X(display, "display", "display") \
    X(width, "width", "width") \
    X(height, "height", "height") \
    X(color, "color", "color") \
    X(background, "background", "background") \
    X(font, "font", "font") \
    X(position, "position", "position") \
    X(top, "top", "top") \
    X(right, "right", "right") \
    X(bottom, "bottom", "bottom") \
    X(left, "left", "left") \
    X(z_index, "zIndex", "z-index") \
    X(z_index, "z-index", "z-index") \
    X(float, "float", "float") \
    X(clear, "clear", "clear") \
    X(overflow, "overflow", "overflow") \
    X(overflow_x, "overflowX", "overflow-x") \
    X(overflow_x, "overflow-x", "overflow-x") \
    X(overflow_y, "overflowY", "overflow-y") \
    X(overflow_y, "overflow-y", "overflow-y") \
    X(visibility, "visibility", "visibility") \
    X(clip, "clip", "clip") \
    X(clip_path, "clipPath", "clip-path") \
    X(clip_path, "clip-path", "clip-path") \
    X(direction, "direction", "direction") \
    X(unicode_bidi, "unicodeBidi", "unicode-bidi") \
    X(unicode_bidi, "unicode-bidi", "unicode-bidi") \
    X(writing_mode, "writingMode", "writing-mode") \
    X(writing_mode, "writing-mode", "writing-mode") \
    X(min_width, "minWidth", "min-width") \
    X(min_width, "min-width", "min-width") \
    X(min_height, "minHeight", "min-height") \
    X(min_height, "min-height", "min-height") \
    X(max_width, "maxWidth", "max-width") \
    X(max_width, "max-width", "max-width") \
    X(max_height, "maxHeight", "max-height") \
    X(max_height, "max-height", "max-height") \
    X(margin_top, "marginTop", "margin-top") \
    X(margin_top, "margin-top", "margin-top") \
    X(margin_right, "marginRight", "margin-right") \
    X(margin_right, "margin-right", "margin-right") \
    X(margin_bottom, "marginBottom", "margin-bottom") \
    X(margin_bottom, "margin-bottom", "margin-bottom") \
    X(margin_left, "marginLeft", "margin-left") \
    X(margin_left, "margin-left", "margin-left") \
    X(margin_block, "marginBlock", "margin-block") \
    X(margin_block, "margin-block", "margin-block") \
    X(margin_block_start, "marginBlockStart", "margin-block-start") \
    X(margin_block_start, "margin-block-start", "margin-block-start") \
    X(margin_block_end, "marginBlockEnd", "margin-block-end") \
    X(margin_block_end, "margin-block-end", "margin-block-end") \
    X(margin_inline, "marginInline", "margin-inline") \
    X(margin_inline, "margin-inline", "margin-inline") \
    X(margin_inline_start, "marginInlineStart", "margin-inline-start") \
    X(margin_inline_start, "margin-inline-start", "margin-inline-start") \
    X(margin_inline_end, "marginInlineEnd", "margin-inline-end") \
    X(margin_inline_end, "margin-inline-end", "margin-inline-end") \
    X(margin_trim, "marginTrim", "margin-trim") \
    X(margin_trim, "margin-trim", "margin-trim") \
    X(padding_top, "paddingTop", "padding-top") \
    X(padding_top, "padding-top", "padding-top") \
    X(padding_right, "paddingRight", "padding-right") \
    X(padding_right, "padding-right", "padding-right") \
    X(padding_bottom, "paddingBottom", "padding-bottom") \
    X(padding_bottom, "padding-bottom", "padding-bottom") \
    X(padding_left, "paddingLeft", "padding-left") \
    X(padding_left, "padding-left", "padding-left") \
    X(padding_block, "paddingBlock", "padding-block") \
    X(padding_block, "padding-block", "padding-block") \
    X(padding_block_start, "paddingBlockStart", "padding-block-start") \
    X(padding_block_start, "padding-block-start", "padding-block-start") \
    X(padding_block_end, "paddingBlockEnd", "padding-block-end") \
    X(padding_block_end, "padding-block-end", "padding-block-end") \
    X(padding_inline, "paddingInline", "padding-inline") \
    X(padding_inline, "padding-inline", "padding-inline") \
    X(padding_inline_start, "paddingInlineStart", "padding-inline-start") \
    X(padding_inline_start, "padding-inline-start", "padding-inline-start") \
    X(padding_inline_end, "paddingInlineEnd", "padding-inline-end") \
    X(padding_inline_end, "padding-inline-end", "padding-inline-end") \
    X(border_top_width, "borderTopWidth", "border-top-width") \
    X(border_top_width, "border-top-width", "border-top-width") \
    X(border_right_width, "borderRightWidth", "border-right-width") \
    X(border_right_width, "border-right-width", "border-right-width") \
    X(border_bottom_width, "borderBottomWidth", "border-bottom-width") \
    X(border_bottom_width, "border-bottom-width", "border-bottom-width") \
    X(border_left_width, "borderLeftWidth", "border-left-width") \
    X(border_left_width, "border-left-width", "border-left-width") \
    X(border_top_style, "borderTopStyle", "border-top-style") \
    X(border_top_style, "border-top-style", "border-top-style") \
    X(border_right_style, "borderRightStyle", "border-right-style") \
    X(border_right_style, "border-right-style", "border-right-style") \
    X(border_bottom_style, "borderBottomStyle", "border-bottom-style") \
    X(border_bottom_style, "border-bottom-style", "border-bottom-style") \
    X(border_left_style, "borderLeftStyle", "border-left-style") \
    X(border_left_style, "border-left-style", "border-left-style") \
    X(border_top_color, "borderTopColor", "border-top-color") \
    X(border_top_color, "border-top-color", "border-top-color") \
    X(border_right_color, "borderRightColor", "border-right-color") \
    X(border_right_color, "border-right-color", "border-right-color") \
    X(border_bottom_color, "borderBottomColor", "border-bottom-color") \
    X(border_bottom_color, "border-bottom-color", "border-bottom-color") \
    X(border_left_color, "borderLeftColor", "border-left-color") \
    X(border_left_color, "border-left-color", "border-left-color") \
    X(border_width, "borderWidth", "border-width") \
    X(border_width, "border-width", "border-width") \
    X(border_style, "borderStyle", "border-style") \
    X(border_style, "border-style", "border-style") \
    X(border_color, "borderColor", "border-color") \
    X(border_color, "border-color", "border-color") \
    X(border_top, "borderTop", "border-top") \
    X(border_top, "border-top", "border-top") \
    X(border_right, "borderRight", "border-right") \
    X(border_right, "border-right", "border-right") \
    X(border_bottom, "borderBottom", "border-bottom") \
    X(border_bottom, "border-bottom", "border-bottom") \
    X(border_left, "borderLeft", "border-left") \
    X(border_left, "border-left", "border-left") \
    X(border_inline, "borderInline", "border-inline") \
    X(border_inline, "border-inline", "border-inline") \
    X(border_inline_width, "borderInlineWidth", "border-inline-width") \
    X(border_inline_width, "border-inline-width", "border-inline-width") \
    X(border_inline_style, "borderInlineStyle", "border-inline-style") \
    X(border_inline_style, "border-inline-style", "border-inline-style") \
    X(border_inline_color, "borderInlineColor", "border-inline-color") \
    X(border_inline_color, "border-inline-color", "border-inline-color") \
    X(border_inline_start, "borderInlineStart", "border-inline-start") \
    X(border_inline_start, "border-inline-start", "border-inline-start") \
    X(border_inline_start_width, "borderInlineStartWidth", "border-inline-start-width") \
    X(border_inline_start_width, "border-inline-start-width", "border-inline-start-width") \
    X(border_inline_start_style, "borderInlineStartStyle", "border-inline-start-style") \
    X(border_inline_start_style, "border-inline-start-style", "border-inline-start-style") \
    X(border_inline_start_color, "borderInlineStartColor", "border-inline-start-color") \
    X(border_inline_start_color, "border-inline-start-color", "border-inline-start-color") \
    X(border_inline_end, "borderInlineEnd", "border-inline-end") \
    X(border_inline_end, "border-inline-end", "border-inline-end") \
    X(border_inline_end_width, "borderInlineEndWidth", "border-inline-end-width") \
    X(border_inline_end_width, "border-inline-end-width", "border-inline-end-width") \
    X(border_inline_end_style, "borderInlineEndStyle", "border-inline-end-style") \
    X(border_inline_end_style, "border-inline-end-style", "border-inline-end-style") \
    X(border_inline_end_color, "borderInlineEndColor", "border-inline-end-color") \
    X(border_inline_end_color, "border-inline-end-color", "border-inline-end-color") \
    X(border_block, "borderBlock", "border-block") \
    X(border_block, "border-block", "border-block") \
    X(border_block_style, "borderBlockStyle", "border-block-style") \
    X(border_block_style, "border-block-style", "border-block-style") \
    X(border_block_start, "borderBlockStart", "border-block-start") \
    X(border_block_start, "border-block-start", "border-block-start") \
    X(border_block_start_style, "borderBlockStartStyle", "border-block-start-style") \
    X(border_block_start_style, "border-block-start-style", "border-block-start-style") \
    X(border_block_end, "borderBlockEnd", "border-block-end") \
    X(border_block_end, "border-block-end", "border-block-end") \
    X(border_block_end_style, "borderBlockEndStyle", "border-block-end-style") \
    X(border_block_end_style, "border-block-end-style", "border-block-end-style") \
    X(border_block_width, "borderBlockWidth", "border-block-width") \
    X(border_block_width, "border-block-width", "border-block-width") \
    X(border_block_color, "borderBlockColor", "border-block-color") \
    X(border_block_color, "border-block-color", "border-block-color") \
    X(border_block_start_width, "borderBlockStartWidth", "border-block-start-width") \
    X(border_block_start_width, "border-block-start-width", "border-block-start-width") \
    X(border_block_start_color, "borderBlockStartColor", "border-block-start-color") \
    X(border_block_start_color, "border-block-start-color", "border-block-start-color") \
    X(border_block_end_color, "borderBlockEndColor", "border-block-end-color") \
    X(border_block_end_color, "border-block-end-color", "border-block-end-color") \
    X(border_block_end_width, "borderBlockEndWidth", "border-block-end-width") \
    X(border_block_end_width, "border-block-end-width", "border-block-end-width") \
    X(border_start_start_radius, "borderStartStartRadius", "border-start-start-radius") \
    X(border_start_start_radius, "border-start-start-radius", "border-start-start-radius") \
    X(border_start_end_radius, "borderStartEndRadius", "border-start-end-radius") \
    X(border_start_end_radius, "border-start-end-radius", "border-start-end-radius") \
    X(border_end_start_radius, "borderEndStartRadius", "border-end-start-radius") \
    X(border_end_start_radius, "border-end-start-radius", "border-end-start-radius") \
    X(border_end_end_radius, "borderEndEndRadius", "border-end-end-radius") \
    X(border_end_end_radius, "border-end-end-radius", "border-end-end-radius") \
    X(box_sizing, "boxSizing", "box-sizing") \
    X(box_sizing, "box-sizing", "box-sizing") \
    X(box_decoration_break, "boxDecorationBreak", "box-decoration-break") \
    X(box_decoration_break, "box-decoration-break", "box-decoration-break") \
    X(aspect_ratio, "aspectRatio", "aspect-ratio") \
    X(aspect_ratio, "aspect-ratio", "aspect-ratio") \
    X(fill, "fill", "fill") \
    X(stroke, "stroke", "stroke") \
    X(stroke_width, "strokeWidth", "stroke-width") \
    X(stroke_width, "stroke-width", "stroke-width") \
    X(font_family, "fontFamily", "font-family") \
    X(font_family, "font-family", "font-family") \
    X(font_size, "fontSize", "font-size") \
    X(font_size, "font-size", "font-size") \
    X(font_weight, "fontWeight", "font-weight") \
    X(font_weight, "font-weight", "font-weight") \
    X(font_style, "fontStyle", "font-style") \
    X(font_style, "font-style", "font-style") \
    X(font_variant, "fontVariant", "font-variant") \
    X(font_variant, "font-variant", "font-variant") \
    X(font_size_adjust, "fontSizeAdjust", "font-size-adjust") \
    X(font_size_adjust, "font-size-adjust", "font-size-adjust") \
    X(font_kerning, "fontKerning", "font-kerning") \
    X(font_kerning, "font-kerning", "font-kerning") \
    X(font_variant_ligatures, "fontVariantLigatures", "font-variant-ligatures") \
    X(font_variant_ligatures, "font-variant-ligatures", "font-variant-ligatures") \
    X(font_variant_caps, "fontVariantCaps", "font-variant-caps") \
    X(font_variant_caps, "font-variant-caps", "font-variant-caps") \
    X(font_variant_numeric, "fontVariantNumeric", "font-variant-numeric") \
    X(font_variant_numeric, "font-variant-numeric", "font-variant-numeric") \
    X(font_variant_alternates, "fontVariantAlternates", "font-variant-alternates") \
    X(font_variant_alternates, "font-variant-alternates", "font-variant-alternates") \
    X(font_variant_east_asian, "fontVariantEastAsian", "font-variant-east-asian") \
    X(font_variant_east_asian, "font-variant-east-asian", "font-variant-east-asian") \
    X(font_feature_settings, "fontFeatureSettings", "font-feature-settings") \
    X(font_feature_settings, "font-feature-settings", "font-feature-settings") \
    X(font_language_override, "fontLanguageOverride", "font-language-override") \
    X(font_language_override, "font-language-override", "font-language-override") \
    X(font_optical_sizing, "fontOpticalSizing", "font-optical-sizing") \
    X(font_optical_sizing, "font-optical-sizing", "font-optical-sizing") \
    X(font_variation_settings, "fontVariationSettings", "font-variation-settings") \
    X(font_variation_settings, "font-variation-settings", "font-variation-settings") \
    X(font_display, "fontDisplay", "font-display") \
    X(font_display, "font-display", "font-display") \
    X(letter_spacing, "letterSpacing", "letter-spacing") \
    X(letter_spacing, "letter-spacing", "letter-spacing") \
    X(word_spacing, "wordSpacing", "word-spacing") \
    X(word_spacing, "word-spacing", "word-spacing") \
    X(text_shadow, "textShadow", "text-shadow") \
    X(text_shadow, "text-shadow", "text-shadow") \
    X(line_height, "lineHeight", "line-height") \
    X(line_height, "line-height", "line-height") \
    X(text_align, "textAlign", "text-align") \
    X(text_align, "text-align", "text-align") \
    X(text_decoration, "textDecoration", "text-decoration") \
    X(text_decoration, "text-decoration", "text-decoration") \
    X(text_transform, "textTransform", "text-transform") \
    X(text_transform, "text-transform", "text-transform") \
    X(initial_letter, "initialLetter", "initial-letter") \
    X(initial_letter, "initial-letter", "initial-letter") \
    X(text_wrap_style, "textWrapStyle", "text-wrap-style") \
    X(text_wrap_style, "text-wrap-style", "text-wrap-style") \
    X(text_spacing_trim, "textSpacingTrim", "text-spacing-trim") \
    X(text_spacing_trim, "text-spacing-trim", "text-spacing-trim") \
    X(text_autospace, "textAutospace", "text-autospace") \
    X(text_autospace, "text-autospace", "text-autospace") \
    X(white_space, "whiteSpace", "white-space") \
    X(white_space, "white-space", "white-space") \
    X(vertical_align, "verticalAlign", "vertical-align") \
    X(vertical_align, "vertical-align", "vertical-align") \
    X(background_color, "backgroundColor", "background-color") \
    X(background_color, "background-color", "background-color") \
    X(background_image, "backgroundImage", "background-image") \
    X(background_image, "background-image", "background-image") \
    X(background_repeat, "backgroundRepeat", "background-repeat") \
    X(background_repeat, "background-repeat", "background-repeat") \
    X(background_position, "backgroundPosition", "background-position") \
    X(background_position, "background-position", "background-position") \
    X(background_size, "backgroundSize", "background-size") \
    X(background_size, "background-size", "background-size") \
    X(flex_direction, "flexDirection", "flex-direction") \
    X(flex_direction, "flex-direction", "flex-direction") \
    X(flex_wrap, "flexWrap", "flex-wrap") \
    X(flex_wrap, "flex-wrap", "flex-wrap") \
    X(flex_flow, "flexFlow", "flex-flow") \
    X(flex_flow, "flex-flow", "flex-flow") \
    X(justify_content, "justifyContent", "justify-content") \
    X(justify_content, "justify-content", "justify-content") \
    X(align_items, "alignItems", "align-items") \
    X(align_items, "align-items", "align-items") \
    X(align_content, "alignContent", "align-content") \
    X(align_content, "align-content", "align-content") \
    X(place_content, "placeContent", "place-content") \
    X(place_content, "place-content", "place-content") \
    X(align_self, "alignSelf", "align-self") \
    X(align_self, "align-self", "align-self") \
    X(flex_grow, "flexGrow", "flex-grow") \
    X(flex_grow, "flex-grow", "flex-grow") \
    X(flex_shrink, "flexShrink", "flex-shrink") \
    X(flex_shrink, "flex-shrink", "flex-shrink") \
    X(flex_basis, "flexBasis", "flex-basis") \
    X(flex_basis, "flex-basis", "flex-basis") \
    X(order, "order", "order") \
    X(grid_template_columns, "gridTemplateColumns", "grid-template-columns") \
    X(grid_template_columns, "grid-template-columns", "grid-template-columns") \
    X(grid_template_rows, "gridTemplateRows", "grid-template-rows") \
    X(grid_template_rows, "grid-template-rows", "grid-template-rows") \
    X(grid_column_start, "gridColumnStart", "grid-column-start") \
    X(grid_column_start, "grid-column-start", "grid-column-start") \
    X(grid_column_end, "gridColumnEnd", "grid-column-end") \
    X(grid_column_end, "grid-column-end", "grid-column-end") \
    X(grid_row_start, "gridRowStart", "grid-row-start") \
    X(grid_row_start, "grid-row-start", "grid-row-start") \
    X(grid_row_end, "gridRowEnd", "grid-row-end") \
    X(grid_row_end, "grid-row-end", "grid-row-end") \
    X(grid_column_gap, "gridColumnGap", "grid-column-gap") \
    X(grid_column_gap, "grid-column-gap", "grid-column-gap") \
    X(grid_row_gap, "gridRowGap", "grid-row-gap") \
    X(grid_row_gap, "grid-row-gap", "grid-row-gap") \
    X(justify_items, "justifyItems", "justify-items") \
    X(justify_items, "justify-items", "justify-items") \
    X(justify_self, "justifySelf", "justify-self") \
    X(justify_self, "justify-self", "justify-self") \
    X(place_items, "placeItems", "place-items") \
    X(place_items, "place-items", "place-items") \
    X(place_self, "placeSelf", "place-self") \
    X(place_self, "place-self", "place-self") \
    X(grid_template, "gridTemplate", "grid-template") \
    X(grid_template, "grid-template", "grid-template") \
    X(grid_template_areas, "gridTemplateAreas", "grid-template-areas") \
    X(grid_template_areas, "grid-template-areas", "grid-template-areas") \
    X(grid_auto_rows, "gridAutoRows", "grid-auto-rows") \
    X(grid_auto_rows, "grid-auto-rows", "grid-auto-rows") \
    X(grid_auto_columns, "gridAutoColumns", "grid-auto-columns") \
    X(grid_auto_columns, "grid-auto-columns", "grid-auto-columns") \
    X(grid_auto_flow, "gridAutoFlow", "grid-auto-flow") \
    X(grid_auto_flow, "grid-auto-flow", "grid-auto-flow") \
    X(grid_row, "gridRow", "grid-row") \
    X(grid_row, "grid-row", "grid-row") \
    X(grid_column, "gridColumn", "grid-column") \
    X(grid_column, "grid-column", "grid-column") \
    X(grid_area, "gridArea", "grid-area") \
    X(grid_area, "grid-area", "grid-area") \
    X(grid_gap, "gridGap", "grid-gap") \
    X(grid_gap, "grid-gap", "grid-gap") \
    X(opacity, "opacity", "opacity") \
    X(cursor, "cursor", "cursor") \
    X(border_radius, "borderRadius", "border-radius") \
    X(border_radius, "border-radius", "border-radius") \
    X(border_top_left_radius, "borderTopLeftRadius", "border-top-left-radius") \
    X(border_top_left_radius, "border-top-left-radius", "border-top-left-radius") \
    X(border_top_right_radius, "borderTopRightRadius", "border-top-right-radius") \
    X(border_top_right_radius, "border-top-right-radius", "border-top-right-radius") \
    X(border_bottom_right_radius, "borderBottomRightRadius", "border-bottom-right-radius") \
    X(border_bottom_right_radius, "border-bottom-right-radius", "border-bottom-right-radius") \
    X(border_bottom_left_radius, "borderBottomLeftRadius", "border-bottom-left-radius") \
    X(border_bottom_left_radius, "border-bottom-left-radius", "border-bottom-left-radius") \
    X(background_attachment, "backgroundAttachment", "background-attachment") \
    X(background_attachment, "background-attachment", "background-attachment") \
    X(background_origin, "backgroundOrigin", "background-origin") \
    X(background_origin, "background-origin", "background-origin") \
    X(background_clip, "backgroundClip", "background-clip") \
    X(background_clip, "background-clip", "background-clip") \
    X(background_position_x, "backgroundPositionX", "background-position-x") \
    X(background_position_x, "background-position-x", "background-position-x") \
    X(background_position_y, "backgroundPositionY", "background-position-y") \
    X(background_position_y, "background-position-y", "background-position-y") \
    X(background_blend_mode, "backgroundBlendMode", "background-blend-mode") \
    X(background_blend_mode, "background-blend-mode", "background-blend-mode") \
    X(filter, "filter", "filter") \
    X(backdrop_filter, "backdropFilter", "backdrop-filter") \
    X(backdrop_filter, "backdrop-filter", "backdrop-filter") \
    X(transform, "transform", "transform") \
    X(transform_origin, "transformOrigin", "transform-origin") \
    X(transform_origin, "transform-origin", "transform-origin") \
    X(transform_style, "transformStyle", "transform-style") \
    X(transform_style, "transform-style", "transform-style") \
    X(backface_visibility, "backfaceVisibility", "backface-visibility") \
    X(backface_visibility, "backface-visibility", "backface-visibility") \
    X(perspective, "perspective", "perspective") \
    X(perspective_origin, "perspectiveOrigin", "perspective-origin") \
    X(perspective_origin, "perspective-origin", "perspective-origin") \
    X(animation, "animation", "animation") \
    X(animation_name, "animationName", "animation-name") \
    X(animation_name, "animation-name", "animation-name") \
    X(animation_duration, "animationDuration", "animation-duration") \
    X(animation_duration, "animation-duration", "animation-duration") \
    X(animation_timing_function, "animationTimingFunction", "animation-timing-function") \
    X(animation_timing_function, "animation-timing-function", "animation-timing-function") \
    X(animation_delay, "animationDelay", "animation-delay") \
    X(animation_delay, "animation-delay", "animation-delay") \
    X(animation_iteration_count, "animationIterationCount", "animation-iteration-count") \
    X(animation_iteration_count, "animation-iteration-count", "animation-iteration-count") \
    X(animation_direction, "animationDirection", "animation-direction") \
    X(animation_direction, "animation-direction", "animation-direction") \
    X(animation_fill_mode, "animationFillMode", "animation-fill-mode") \
    X(animation_fill_mode, "animation-fill-mode", "animation-fill-mode") \
    X(animation_play_state, "animationPlayState", "animation-play-state") \
    X(animation_play_state, "animation-play-state", "animation-play-state") \
    X(transition, "transition", "transition") \
    X(margin, "margin", "margin") \
    X(padding, "padding", "padding") \
    X(border, "border", "border") \
    X(flex, "flex", "flex") \
    X(grid, "grid", "grid") \
    X(column_width, "columnWidth", "column-width") \
    X(column_width, "column-width", "column-width") \
    X(column_count, "columnCount", "column-count") \
    X(column_count, "column-count", "column-count") \
    X(columns, "columns", "columns") \
    X(column_rule, "columnRule", "column-rule") \
    X(column_rule, "column-rule", "column-rule") \
    X(column_rule_width, "columnRuleWidth", "column-rule-width") \
    X(column_rule_width, "column-rule-width", "column-rule-width") \
    X(column_rule_style, "columnRuleStyle", "column-rule-style") \
    X(column_rule_style, "column-rule-style", "column-rule-style") \
    X(column_rule_color, "columnRuleColor", "column-rule-color") \
    X(column_rule_color, "column-rule-color", "column-rule-color") \
    X(column_span, "columnSpan", "column-span") \
    X(column_span, "column-span", "column-span") \
    X(column_fill, "columnFill", "column-fill") \
    X(column_fill, "column-fill", "column-fill") \
    X(column_height, "columnHeight", "column-height") \
    X(column_height, "column-height", "column-height") \
    X(column_wrap, "columnWrap", "column-wrap") \
    X(column_wrap, "column-wrap", "column-wrap") \
    X(gap, "gap", "gap") \
    X(row_gap, "rowGap", "row-gap") \
    X(row_gap, "row-gap", "row-gap") \
    X(column_gap, "columnGap", "column-gap") \
    X(column_gap, "column-gap", "column-gap") \
    X(block_size, "blockSize", "block-size") \
    X(block_size, "block-size", "block-size") \
    X(inline_size, "inlineSize", "inline-size") \
    X(inline_size, "inline-size", "inline-size") \
    X(min_block_size, "minBlockSize", "min-block-size") \
    X(min_block_size, "min-block-size", "min-block-size") \
    X(min_inline_size, "minInlineSize", "min-inline-size") \
    X(min_inline_size, "min-inline-size", "min-inline-size") \
    X(max_block_size, "maxBlockSize", "max-block-size") \
    X(max_block_size, "max-block-size", "max-block-size") \
    X(max_inline_size, "maxInlineSize", "max-inline-size") \
    X(max_inline_size, "max-inline-size", "max-inline-size") \
    X(inset, "inset", "inset") \
    X(inset_block, "insetBlock", "inset-block") \
    X(inset_block, "inset-block", "inset-block") \
    X(inset_block_start, "insetBlockStart", "inset-block-start") \
    X(inset_block_start, "inset-block-start", "inset-block-start") \
    X(inset_block_end, "insetBlockEnd", "inset-block-end") \
    X(inset_block_end, "inset-block-end", "inset-block-end") \
    X(inset_inline, "insetInline", "inset-inline") \
    X(inset_inline, "inset-inline", "inset-inline") \
    X(inset_inline_start, "insetInlineStart", "inset-inline-start") \
    X(inset_inline_start, "inset-inline-start", "inset-inline-start") \
    X(inset_inline_end, "insetInlineEnd", "inset-inline-end") \
    X(inset_inline_end, "inset-inline-end", "inset-inline-end") \
    X(text_decoration_line, "textDecorationLine", "text-decoration-line") \
    X(text_decoration_line, "text-decoration-line", "text-decoration-line") \
    X(text_decoration_style, "textDecorationStyle", "text-decoration-style") \
    X(text_decoration_style, "text-decoration-style", "text-decoration-style") \
    X(text_decoration_color, "textDecorationColor", "text-decoration-color") \
    X(text_decoration_color, "text-decoration-color", "text-decoration-color") \
    X(text_decoration_thickness, "textDecorationThickness", "text-decoration-thickness") \
    X(text_decoration_thickness, "text-decoration-thickness", "text-decoration-thickness") \
    X(text_emphasis, "textEmphasis", "text-emphasis") \
    X(text_emphasis, "text-emphasis", "text-emphasis") \
    X(text_emphasis_style, "textEmphasisStyle", "text-emphasis-style") \
    X(text_emphasis_style, "text-emphasis-style", "text-emphasis-style") \
    X(text_emphasis_color, "textEmphasisColor", "text-emphasis-color") \
    X(text_emphasis_color, "text-emphasis-color", "text-emphasis-color") \
    X(text_emphasis_position, "textEmphasisPosition", "text-emphasis-position") \
    X(text_emphasis_position, "text-emphasis-position", "text-emphasis-position") \
    X(text_overflow, "textOverflow", "text-overflow") \
    X(text_overflow, "text-overflow", "text-overflow") \
    X(word_break, "wordBreak", "word-break") \
    X(word_break, "word-break", "word-break") \
    X(line_break, "lineBreak", "line-break") \
    X(line_break, "line-break", "line-break") \
    X(hyphens, "hyphens", "hyphens") \
    X(hyphenate_character, "hyphenateCharacter", "hyphenate-character") \
    X(hyphenate_character, "hyphenate-character", "hyphenate-character") \
    X(overflow_wrap, "overflowWrap", "overflow-wrap") \
    X(overflow_wrap, "overflow-wrap", "overflow-wrap") \
    X(word_wrap, "wordWrap", "word-wrap") \
    X(word_wrap, "word-wrap", "word-wrap") \
    X(tab_size, "tabSize", "tab-size") \
    X(tab_size, "tab-size", "tab-size") \
    X(hanging_punctuation, "hangingPunctuation", "hanging-punctuation") \
    X(hanging_punctuation, "hanging-punctuation", "hanging-punctuation") \
    X(text_justify, "textJustify", "text-justify") \
    X(text_justify, "text-justify", "text-justify") \
    X(text_align_all, "textAlignAll", "text-align-all") \
    X(text_align_all, "text-align-all", "text-align-all") \
    X(text_align_last, "textAlignLast", "text-align-last") \
    X(text_align_last, "text-align-last", "text-align-last") \
    X(list_style, "listStyle", "list-style") \
    X(list_style, "list-style", "list-style") \
    X(list_style_type, "listStyleType", "list-style-type") \
    X(list_style_type, "list-style-type", "list-style-type") \
    X(list_style_position, "listStylePosition", "list-style-position") \
    X(list_style_position, "list-style-position", "list-style-position") \
    X(list_style_image, "listStyleImage", "list-style-image") \
    X(list_style_image, "list-style-image", "list-style-image") \
    X(counter_reset, "counterReset", "counter-reset") \
    X(counter_reset, "counter-reset", "counter-reset") \
    X(counter_increment, "counterIncrement", "counter-increment") \
    X(counter_increment, "counter-increment", "counter-increment") \
    X(counter_set, "counterSet", "counter-set") \
    X(counter_set, "counter-set", "counter-set") \
    X(content, "content", "content") \
    X(quotes, "quotes", "quotes") \
    X(font_stretch, "fontStretch", "font-stretch") \
    X(font_stretch, "font-stretch", "font-stretch") \
    X(text_orientation, "textOrientation", "text-orientation") \
    X(text_orientation, "text-orientation", "text-orientation") \
    X(text_combine_upright, "textCombineUpright", "text-combine-upright") \
    X(text_combine_upright, "text-combine-upright", "text-combine-upright") \
    X(text_indent, "textIndent", "text-indent") \
    X(text_indent, "text-indent", "text-indent") \
    X(border_collapse, "borderCollapse", "border-collapse") \
    X(border_collapse, "border-collapse", "border-collapse") \
    X(border_spacing, "borderSpacing", "border-spacing") \
    X(border_spacing, "border-spacing", "border-spacing") \
    X(caption_side, "captionSide", "caption-side") \
    X(caption_side, "caption-side", "caption-side") \
    X(empty_cells, "emptyCells", "empty-cells") \
    X(empty_cells, "empty-cells", "empty-cells") \
    X(table_layout, "tableLayout", "table-layout") \
    X(table_layout, "table-layout", "table-layout") \
    X(resize, "resize", "resize") \
    X(accent_color, "accentColor", "accent-color") \
    X(accent_color, "accent-color", "accent-color") \
    X(caret_color, "caretColor", "caret-color") \
    X(caret_color, "caret-color", "caret-color") \
    X(caret_shape, "caretShape", "caret-shape") \
    X(caret_shape, "caret-shape", "caret-shape") \
    X(nav_index, "navIndex", "nav-index") \
    X(nav_index, "nav-index", "nav-index") \
    X(nav_up, "navUp", "nav-up") \
    X(nav_up, "nav-up", "nav-up") \
    X(nav_right, "navRight", "nav-right") \
    X(nav_right, "nav-right", "nav-right") \
    X(nav_down, "navDown", "nav-down") \
    X(nav_down, "nav-down", "nav-down") \
    X(nav_left, "navLeft", "nav-left") \
    X(nav_left, "nav-left", "nav-left") \
    X(appearance, "appearance", "appearance") \
    X(field_sizing, "fieldSizing", "field-sizing") \
    X(field_sizing, "field-sizing", "field-sizing") \
    X(user_select, "userSelect", "user-select") \
    X(user_select, "user-select", "user-select") \
    X(box_shadow, "boxShadow", "box-shadow") \
    X(box_shadow, "box-shadow", "box-shadow") \
    X(border_image, "borderImage", "border-image") \
    X(border_image, "border-image", "border-image") \
    X(border_image_source, "borderImageSource", "border-image-source") \
    X(border_image_source, "border-image-source", "border-image-source") \
    X(border_image_slice, "borderImageSlice", "border-image-slice") \
    X(border_image_slice, "border-image-slice", "border-image-slice") \
    X(border_image_width, "borderImageWidth", "border-image-width") \
    X(border_image_width, "border-image-width", "border-image-width") \
    X(border_image_outset, "borderImageOutset", "border-image-outset") \
    X(border_image_outset, "border-image-outset", "border-image-outset") \
    X(border_image_repeat, "borderImageRepeat", "border-image-repeat") \
    X(border_image_repeat, "border-image-repeat", "border-image-repeat") \
    X(outline, "outline", "outline") \
    X(outline_style, "outlineStyle", "outline-style") \
    X(outline_style, "outline-style", "outline-style") \
    X(outline_width, "outlineWidth", "outline-width") \
    X(outline_width, "outline-width", "outline-width") \
    X(outline_color, "outlineColor", "outline-color") \
    X(outline_color, "outline-color", "outline-color") \
    X(outline_offset, "outlineOffset", "outline-offset") \
    X(outline_offset, "outline-offset", "outline-offset") \
    X(break_before, "breakBefore", "break-before") \
    X(break_before, "break-before", "break-before") \
    X(break_after, "breakAfter", "break-after") \
    X(break_after, "break-after", "break-after") \
    X(break_inside, "breakInside", "break-inside") \
    X(break_inside, "break-inside", "break-inside") \
    X(page_break_before, "pageBreakBefore", "page-break-before") \
    X(page_break_before, "page-break-before", "page-break-before") \
    X(page_break_after, "pageBreakAfter", "page-break-after") \
    X(page_break_after, "page-break-after", "page-break-after") \
    X(page_break_inside, "pageBreakInside", "page-break-inside") \
    X(page_break_inside, "page-break-inside", "page-break-inside") \
    X(orphans, "orphans", "orphans") \
    X(widows, "widows", "widows") \
    X(container, "container", "container") \
    X(container_type, "containerType", "container-type") \
    X(container_type, "container-type", "container-type") \
    X(container_name, "containerName", "container-name") \
    X(container_name, "container-name", "container-name") \
    X(contain, "contain", "contain") \
    X(contain_intrinsic_width, "containIntrinsicWidth", "contain-intrinsic-width") \
    X(contain_intrinsic_width, "contain-intrinsic-width", "contain-intrinsic-width") \
    X(contain_intrinsic_height, "containIntrinsicHeight", "contain-intrinsic-height") \
    X(contain_intrinsic_height, "contain-intrinsic-height", "contain-intrinsic-height") \
    X(contain_intrinsic_size, "containIntrinsicSize", "contain-intrinsic-size") \
    X(contain_intrinsic_size, "contain-intrinsic-size", "contain-intrinsic-size") \
    X(alignment_baseline, "alignmentBaseline", "alignment-baseline") \
    X(alignment_baseline, "alignment-baseline", "alignment-baseline") \
    X(baseline_shift, "baselineShift", "baseline-shift") \
    X(baseline_shift, "baseline-shift", "baseline-shift") \
    X(baseline_source, "baselineSource", "baseline-source") \
    X(baseline_source, "baseline-source", "baseline-source") \
    X(dominant_baseline, "dominantBaseline", "dominant-baseline") \
    X(dominant_baseline, "dominant-baseline", "dominant-baseline") \
    X(text_box, "textBox", "text-box") \
    X(text_box, "text-box", "text-box") \
    X(text_box_trim, "textBoxTrim", "text-box-trim") \
    X(text_box_trim, "text-box-trim", "text-box-trim") \
    X(text_box_edge, "textBoxEdge", "text-box-edge") \
    X(text_box_edge, "text-box-edge", "text-box-edge") \
    X(isolation, "isolation", "isolation") \
    X(mix_blend_mode, "mixBlendMode", "mix-blend-mode") \
    X(mix_blend_mode, "mix-blend-mode", "mix-blend-mode") \
    X(object_fit, "objectFit", "object-fit") \
    X(object_fit, "object-fit", "object-fit") \
    X(object_position, "objectPosition", "object-position") \
    X(object_position, "object-position", "object-position") \
    X(object_view_box, "objectViewBox", "object-view-box") \
    X(object_view_box, "object-view-box", "object-view-box") \
    X(pointer_events, "pointerEvents", "pointer-events") \
    X(pointer_events, "pointer-events", "pointer-events") \
    X(float_defer, "floatDefer", "float-defer") \
    X(float_defer, "float-defer", "float-defer") \
    X(float_offset, "floatOffset", "float-offset") \
    X(float_offset, "float-offset", "float-offset") \
    X(float_reference, "floatReference", "float-reference") \
    X(float_reference, "float-reference", "float-reference") \
    X(image_orientation, "imageOrientation", "image-orientation") \
    X(image_orientation, "image-orientation", "image-orientation") \
    X(image_rendering, "imageRendering", "image-rendering") \
    X(image_rendering, "image-rendering", "image-rendering") \
    X(marker_offset, "markerOffset", "marker-offset") \
    X(marker_offset, "marker-offset", "marker-offset") \
    X(mask_image, "maskImage", "mask-image") \
    X(mask_image, "mask-image", "mask-image") \
    X(mask_type, "maskType", "mask-type") \
    X(mask_type, "mask-type", "mask-type") \
    X(nesting, "nesting", "nesting") \
    X(overflow_block, "overflowBlock", "overflow-block") \
    X(overflow_block, "overflow-block", "overflow-block") \
    X(overflow_clip_margin, "overflowClipMargin", "overflow-clip-margin") \
    X(overflow_clip_margin, "overflow-clip-margin", "overflow-clip-margin") \
    X(overflow_inline, "overflowInline", "overflow-inline") \
    X(overflow_inline, "overflow-inline", "overflow-inline") \
    X(overscroll_behavior, "overscrollBehavior", "overscroll-behavior") \
    X(overscroll_behavior, "overscroll-behavior", "overscroll-behavior") \
    X(ruby_align, "rubyAlign", "ruby-align") \
    X(ruby_align, "ruby-align", "ruby-align") \
    X(ruby_position, "rubyPosition", "ruby-position") \
    X(ruby_position, "ruby-position", "ruby-position") \
    X(scroll_behavior, "scrollBehavior", "scroll-behavior") \
    X(scroll_behavior, "scroll-behavior", "scroll-behavior") \
    X(scroll_margin, "scrollMargin", "scroll-margin") \
    X(scroll_margin, "scroll-margin", "scroll-margin") \
    X(scroll_padding, "scrollPadding", "scroll-padding") \
    X(scroll_padding, "scroll-padding", "scroll-padding") \
    X(scroll_snap_align, "scrollSnapAlign", "scroll-snap-align") \
    X(scroll_snap_align, "scroll-snap-align", "scroll-snap-align") \
    X(scroll_snap_type, "scrollSnapType", "scroll-snap-type") \
    X(scroll_snap_type, "scroll-snap-type", "scroll-snap-type") \
    X(transition_delay, "transitionDelay", "transition-delay") \
    X(transition_delay, "transition-delay", "transition-delay") \
    X(transition_duration, "transitionDuration", "transition-duration") \
    X(transition_duration, "transition-duration", "transition-duration") \
    X(transition_property, "transitionProperty", "transition-property") \
    X(transition_property, "transition-property", "transition-property") \
    X(transition_timing_function, "transitionTimingFunction", "transition-timing-function") \
    X(transition_timing_function, "transition-timing-function", "transition-timing-function") \
    X(wrap_flow, "wrapFlow", "wrap-flow") \
    X(wrap_flow, "wrap-flow", "wrap-flow") \
    X(wrap_through, "wrapThrough", "wrap-through") \
    X(wrap_through, "wrap-through", "wrap-through") \
    X(line_clamp, "lineClamp", "line-clamp") \
    X(line_clamp, "line-clamp", "line-clamp") \
    X(_webkit_line_clamp, "WebkitLineClamp", "-webkit-line-clamp") \
    X(_webkit_line_clamp, "-webkit-line-clamp", "-webkit-line-clamp") \
    X(_webkit_line_clamp, "webkitLineClamp", "-webkit-line-clamp") \
    X(contain_intrinsic_inline_size, "containIntrinsicInlineSize", "contain-intrinsic-inline-size") \
    X(contain_intrinsic_inline_size, "contain-intrinsic-inline-size", "contain-intrinsic-inline-size") \
    X(contain_intrinsic_block_size, "containIntrinsicBlockSize", "contain-intrinsic-block-size") \
    X(contain_intrinsic_block_size, "contain-intrinsic-block-size", "contain-intrinsic-block-size") \
    X(scrollbar_gutter, "scrollbarGutter", "scrollbar-gutter") \
    X(scrollbar_gutter, "scrollbar-gutter", "scrollbar-gutter") \
    X(content_visibility, "contentVisibility", "content-visibility") \
    X(content_visibility, "content-visibility", "content-visibility") \
    X(all, "all", "all") \
    X(zoom, "zoom", "zoom") \
    X(text_wrap, "textWrap", "text-wrap") \
    X(text_wrap, "text-wrap", "text-wrap") \
    X(text_wrap_mode, "textWrapMode", "text-wrap-mode") \
    X(text_wrap_mode, "text-wrap-mode", "text-wrap-mode") \
    X(text_underline_offset, "textUnderlineOffset", "text-underline-offset") \
    X(text_underline_offset, "text-underline-offset", "text-underline-offset") \
    X(text_decoration_skip_ink, "textDecorationSkipInk", "text-decoration-skip-ink") \
    X(text_decoration_skip_ink, "text-decoration-skip-ink", "text-decoration-skip-ink") \
    X(text_underline_position, "textUnderlinePosition", "text-underline-position") \
    X(text_underline_position, "text-underline-position", "text-underline-position") \
    X(overscroll_behavior_x, "overscrollBehaviorX", "overscroll-behavior-x") \
    X(overscroll_behavior_x, "overscroll-behavior-x", "overscroll-behavior-x") \
    X(overscroll_behavior_y, "overscrollBehaviorY", "overscroll-behavior-y") \
    X(overscroll_behavior_y, "overscroll-behavior-y", "overscroll-behavior-y") \
    X(scroll_margin_top, "scrollMarginTop", "scroll-margin-top") \
    X(scroll_margin_top, "scroll-margin-top", "scroll-margin-top") \
    X(scroll_margin_right, "scrollMarginRight", "scroll-margin-right") \
    X(scroll_margin_right, "scroll-margin-right", "scroll-margin-right") \
    X(scroll_margin_bottom, "scrollMarginBottom", "scroll-margin-bottom") \
    X(scroll_margin_bottom, "scroll-margin-bottom", "scroll-margin-bottom") \
    X(scroll_margin_left, "scrollMarginLeft", "scroll-margin-left") \
    X(scroll_margin_left, "scroll-margin-left", "scroll-margin-left") \
    X(scroll_margin_block, "scrollMarginBlock", "scroll-margin-block") \
    X(scroll_margin_block, "scroll-margin-block", "scroll-margin-block") \
    X(scroll_margin_block_start, "scrollMarginBlockStart", "scroll-margin-block-start") \
    X(scroll_margin_block_start, "scroll-margin-block-start", "scroll-margin-block-start") \
    X(scroll_margin_block_end, "scrollMarginBlockEnd", "scroll-margin-block-end") \
    X(scroll_margin_block_end, "scroll-margin-block-end", "scroll-margin-block-end") \
    X(scroll_margin_inline, "scrollMarginInline", "scroll-margin-inline") \
    X(scroll_margin_inline, "scroll-margin-inline", "scroll-margin-inline") \
    X(scroll_margin_inline_start, "scrollMarginInlineStart", "scroll-margin-inline-start") \
    X(scroll_margin_inline_start, "scroll-margin-inline-start", "scroll-margin-inline-start") \
    X(scroll_margin_inline_end, "scrollMarginInlineEnd", "scroll-margin-inline-end") \
    X(scroll_margin_inline_end, "scroll-margin-inline-end", "scroll-margin-inline-end") \
    X(scroll_padding_top, "scrollPaddingTop", "scroll-padding-top") \
    X(scroll_padding_top, "scroll-padding-top", "scroll-padding-top") \
    X(scroll_padding_right, "scrollPaddingRight", "scroll-padding-right") \
    X(scroll_padding_right, "scroll-padding-right", "scroll-padding-right") \
    X(scroll_padding_bottom, "scrollPaddingBottom", "scroll-padding-bottom") \
    X(scroll_padding_bottom, "scroll-padding-bottom", "scroll-padding-bottom") \
    X(scroll_padding_left, "scrollPaddingLeft", "scroll-padding-left") \
    X(scroll_padding_left, "scroll-padding-left", "scroll-padding-left") \
    X(scroll_padding_block, "scrollPaddingBlock", "scroll-padding-block") \
    X(scroll_padding_block, "scroll-padding-block", "scroll-padding-block") \
    X(scroll_padding_block_start, "scrollPaddingBlockStart", "scroll-padding-block-start") \
    X(scroll_padding_block_start, "scroll-padding-block-start", "scroll-padding-block-start") \
    X(scroll_padding_block_end, "scrollPaddingBlockEnd", "scroll-padding-block-end") \
    X(scroll_padding_block_end, "scroll-padding-block-end", "scroll-padding-block-end") \
    X(scroll_padding_inline, "scrollPaddingInline", "scroll-padding-inline") \
    X(scroll_padding_inline, "scroll-padding-inline", "scroll-padding-inline") \
    X(scroll_padding_inline_start, "scrollPaddingInlineStart", "scroll-padding-inline-start") \
    X(scroll_padding_inline_start, "scroll-padding-inline-start", "scroll-padding-inline-start") \
    X(scroll_padding_inline_end, "scrollPaddingInlineEnd", "scroll-padding-inline-end") \
    X(scroll_padding_inline_end, "scroll-padding-inline-end", "scroll-padding-inline-end") \
    X(translate, "translate", "translate") \
    X(rotate, "rotate", "rotate") \
    X(scale, "scale", "scale") \
    X(css_float, "cssFloat", "float")

#define CSS_FONT_FACE_DESCRIPTORS_FIELDS(X) \
    X(src) \
    X(font_family) \
    X(font_style) \
    X(font_weight) \
    X(font_stretch) \
    X(font_width) \
    X(unicode_range) \
    X(font_feature_settings) \
    X(font_variation_settings) \
    X(font_named_instance) \
    X(font_display) \
    X(font_language_override) \
    X(ascent_override) \
    X(descent_override) \
    X(line_gap_override)

#define CSS_FONT_FACE_DESCRIPTORS_ATTRIBUTES(X) \
    X(src, "src", "src") \
    X(font_family, "fontFamily", "font-family") \
    X(font_family, "font-family", "font-family") \
    X(font_style, "fontStyle", "font-style") \
    X(font_style, "font-style", "font-style") \
    X(font_weight, "fontWeight", "font-weight") \
    X(font_weight, "font-weight", "font-weight") \
    X(font_stretch, "fontStretch", "font-stretch") \
    X(font_stretch, "font-stretch", "font-stretch") \
    X(font_width, "fontWidth", "font-width") \
    X(font_width, "font-width", "font-width") \
    X(unicode_range, "unicodeRange", "unicode-range") \
    X(unicode_range, "unicode-range", "unicode-range") \
    X(font_feature_settings, "fontFeatureSettings", "font-feature-settings") \
    X(font_feature_settings, "font-feature-settings", "font-feature-settings") \
    X(font_variation_settings, "fontVariationSettings", "font-variation-settings") \
    X(font_variation_settings, "font-variation-settings", "font-variation-settings") \
    X(font_named_instance, "fontNamedInstance", "font-named-instance") \
    X(font_named_instance, "font-named-instance", "font-named-instance") \
    X(font_display, "fontDisplay", "font-display") \
    X(font_display, "font-display", "font-display") \
    X(font_language_override, "fontLanguageOverride", "font-language-override") \
    X(font_language_override, "font-language-override", "font-language-override") \
    X(ascent_override, "ascentOverride", "ascent-override") \
    X(ascent_override, "ascent-override", "ascent-override") \
    X(descent_override, "descentOverride", "descent-override") \
    X(descent_override, "descent-override", "descent-override") \
    X(line_gap_override, "lineGapOverride", "line-gap-override") \
    X(line_gap_override, "line-gap-override", "line-gap-override")

#define CSS_PAGE_DESCRIPTORS_FIELDS(X) \
    X(margin) \
    X(margin_top) \
    X(margin_right) \
    X(margin_bottom) \
    X(margin_left) \
    X(size) \
    X(page_orientation) \
    X(marks) \
    X(bleed)

#define CSS_PAGE_DESCRIPTORS_ATTRIBUTES(X) \
    X(margin, "margin", "margin") \
    X(margin_top, "marginTop", "margin-top") \
    X(margin_top, "margin-top", "margin-top") \
    X(margin_right, "marginRight", "margin-right") \
    X(margin_right, "margin-right", "margin-right") \
    X(margin_bottom, "marginBottom", "margin-bottom") \
    X(margin_bottom, "margin-bottom", "margin-bottom") \
    X(margin_left, "marginLeft", "margin-left") \
    X(margin_left, "margin-left", "margin-left") \
    X(size, "size", "size") \
    X(page_orientation, "pageOrientation", "page-orientation") \
    X(page_orientation, "page-orientation", "page-orientation") \
    X(marks, "marks", "marks") \
    X(bleed, "bleed", "bleed")
